data grp;
set abt.train;
select;
when ( 0 < ACT_CINS_N_STATB or missing(ACT_CINS_N_STATB) ) do;
GRP_ACT_CINS_N_STATB  = 1 ;
end;
when ( not missing(ACT_CINS_N_STATB) and ACT_CINS_N_STATB <= 0 ) do;
GRP_ACT_CINS_N_STATB  = 2 ;
end;
otherwise GRP_ACT_CINS_N_STATB  = 3 ; end;
select;
when ( missing(ACT_CINS_N_STATC) or ACT_CINS_N_STATC <= 0 ) do;
GRP_ACT_CINS_N_STATC  = 1 ;
end;
when ( 0 < ACT_CINS_N_STATC <= 2 ) do;
GRP_ACT_CINS_N_STATC  = 2 ;
end;
when ( 2 < ACT_CINS_N_STATC ) do;
GRP_ACT_CINS_N_STATC  = 3 ;
end;
otherwise GRP_ACT_CINS_N_STATC  = 4 ; end;
select;
when ( missing(ACT_CINS_SENIORITY) or ACT_CINS_SENIORITY <= 103 ) do;
GRP_ACT_CINS_SENIORITY  = 1 ;
end;
when ( 103 < ACT_CINS_SENIORITY ) do;
GRP_ACT_CINS_SENIORITY  = 2 ;
end;
otherwise GRP_ACT_CINS_SENIORITY  = 3 ; end;
select (APP_CHAR_GENDER );
  when ('Female')   do;
GRP_APP_CHAR_GENDER  = 1 ;
end;
  when ('Male')   do;
GRP_APP_CHAR_GENDER  = 2 ;
end;
otherwise GRP_APP_CHAR_GENDER  = 3 ; end;
select (APP_CHAR_JOB_CODE );
  when ('Owner company')   do;
GRP_APP_CHAR_JOB_CODE  = 1 ;
end;
  when ('Retired')   do;
GRP_APP_CHAR_JOB_CODE  = 2 ;
end;
  when ('Permanent')   do;
GRP_APP_CHAR_JOB_CODE  = 3 ;
end;
  when ('Contract')   do;
GRP_APP_CHAR_JOB_CODE  = 4 ;
end;
otherwise GRP_APP_CHAR_JOB_CODE  = 5 ; end;
select;
when ( (not missing(APP_INCOME) and APP_INCOME <= 1503) or 4923 < APP_INCOME ) do;
GRP_APP_INCOME  = 1 ;
end;
when ( 1503 < APP_INCOME <= 4923 ) do;
GRP_APP_INCOME  = 2 ;
end;
otherwise GRP_APP_INCOME  = 3 ; end;
select;
when ( 11376 < APP_LOAN_AMOUNT ) do;
GRP_APP_LOAN_AMOUNT  = 1 ;
end;
when ( 8880 < APP_LOAN_AMOUNT <= 11376 ) do;
GRP_APP_LOAN_AMOUNT  = 2 ;
end;
when ( 4824 < APP_LOAN_AMOUNT <= 8880 ) do;
GRP_APP_LOAN_AMOUNT  = 3 ;
end;
when ( 1956 < APP_LOAN_AMOUNT <= 4824 ) do;
GRP_APP_LOAN_AMOUNT  = 4 ;
end;
when ( not missing(APP_LOAN_AMOUNT) and APP_LOAN_AMOUNT <= 1956 ) do;
GRP_APP_LOAN_AMOUNT  = 5 ;
end;
otherwise GRP_APP_LOAN_AMOUNT  = 6 ; end;
select;
when ( (not missing(APP_SPENDINGS) and APP_SPENDINGS <= 240) or 2220 < APP_SPENDINGS ) do;
GRP_APP_SPENDINGS  = 1 ;
end;
when ( 240 < APP_SPENDINGS <= 2220 ) do;
GRP_APP_SPENDINGS  = 2 ;
end;
otherwise GRP_APP_SPENDINGS  = 3 ; end;
run;
