data grp;
set abt.train;
select;
when ( not missing(ACT12_N_ARREARS) ) do;
GRP_ACT12_N_ARREARS  = 1 ;
end;
when ( missing(ACT12_N_ARREARS) ) do;
GRP_ACT12_N_ARREARS  = 2 ;
end;
otherwise GRP_ACT12_N_ARREARS  = 3 ; end;
select;
when ( not missing(ACT12_N_ARREARS_DAYS) ) do;
GRP_ACT12_N_ARREARS_DAYS  = 1 ;
end;
when ( missing(ACT12_N_ARREARS_DAYS) ) do;
GRP_ACT12_N_ARREARS_DAYS  = 2 ;
end;
otherwise GRP_ACT12_N_ARREARS_DAYS  = 3 ; end;
select;
when ( not missing(ACT12_N_GOOD_DAYS) ) do;
GRP_ACT12_N_GOOD_DAYS  = 1 ;
end;
when ( missing(ACT12_N_GOOD_DAYS) ) do;
GRP_ACT12_N_GOOD_DAYS  = 2 ;
end;
otherwise GRP_ACT12_N_GOOD_DAYS  = 3 ; end;
select;
when ( not missing(ACT3_N_ARREARS) ) do;
GRP_ACT3_N_ARREARS  = 1 ;
end;
when ( missing(ACT3_N_ARREARS) ) do;
GRP_ACT3_N_ARREARS  = 2 ;
end;
otherwise GRP_ACT3_N_ARREARS  = 3 ; end;
select;
when ( not missing(ACT3_N_ARREARS_DAYS) ) do;
GRP_ACT3_N_ARREARS_DAYS  = 1 ;
end;
when ( missing(ACT3_N_ARREARS_DAYS) ) do;
GRP_ACT3_N_ARREARS_DAYS  = 2 ;
end;
otherwise GRP_ACT3_N_ARREARS_DAYS  = 3 ; end;
select;
when ( not missing(ACT3_N_GOOD_DAYS) ) do;
GRP_ACT3_N_GOOD_DAYS  = 1 ;
end;
when ( missing(ACT3_N_GOOD_DAYS) ) do;
GRP_ACT3_N_GOOD_DAYS  = 2 ;
end;
otherwise GRP_ACT3_N_GOOD_DAYS  = 3 ; end;
select;
when ( not missing(ACT6_N_ARREARS) ) do;
GRP_ACT6_N_ARREARS  = 1 ;
end;
when ( missing(ACT6_N_ARREARS) ) do;
GRP_ACT6_N_ARREARS  = 2 ;
end;
otherwise GRP_ACT6_N_ARREARS  = 3 ; end;
select;
when ( not missing(ACT6_N_ARREARS_DAYS) ) do;
GRP_ACT6_N_ARREARS_DAYS  = 1 ;
end;
when ( missing(ACT6_N_ARREARS_DAYS) ) do;
GRP_ACT6_N_ARREARS_DAYS  = 2 ;
end;
otherwise GRP_ACT6_N_ARREARS_DAYS  = 3 ; end;
select;
when ( not missing(ACT6_N_GOOD_DAYS) ) do;
GRP_ACT6_N_GOOD_DAYS  = 1 ;
end;
when ( missing(ACT6_N_GOOD_DAYS) ) do;
GRP_ACT6_N_GOOD_DAYS  = 2 ;
end;
otherwise GRP_ACT6_N_GOOD_DAYS  = 3 ; end;
select;
when ( not missing(ACT9_N_ARREARS) ) do;
GRP_ACT9_N_ARREARS  = 1 ;
end;
when ( missing(ACT9_N_ARREARS) ) do;
GRP_ACT9_N_ARREARS  = 2 ;
end;
otherwise GRP_ACT9_N_ARREARS  = 3 ; end;
select;
when ( not missing(ACT9_N_ARREARS_DAYS) ) do;
GRP_ACT9_N_ARREARS_DAYS  = 1 ;
end;
when ( missing(ACT9_N_ARREARS_DAYS) ) do;
GRP_ACT9_N_ARREARS_DAYS  = 2 ;
end;
otherwise GRP_ACT9_N_ARREARS_DAYS  = 3 ; end;
select;
when ( not missing(ACT9_N_GOOD_DAYS) ) do;
GRP_ACT9_N_GOOD_DAYS  = 1 ;
end;
when ( missing(ACT9_N_GOOD_DAYS) ) do;
GRP_ACT9_N_GOOD_DAYS  = 2 ;
end;
otherwise GRP_ACT9_N_GOOD_DAYS  = 3 ; end;
select;
when ( not missing(ACT_AGE) and ACT_AGE <= 37 ) do;
GRP_ACT_AGE  = 1 ;
end;
when ( 37 < ACT_AGE <= 43 ) do;
GRP_ACT_AGE  = 2 ;
end;
when ( 43 < ACT_AGE <= 55 ) do;
GRP_ACT_AGE  = 3 ;
end;
when ( 55 < ACT_AGE <= 58 ) do;
GRP_ACT_AGE  = 4 ;
end;
when ( 58 < ACT_AGE <= 65 ) do;
GRP_ACT_AGE  = 5 ;
end;
when ( 65 < ACT_AGE ) do;
GRP_ACT_AGE  = 6 ;
end;
when ( missing(ACT_AGE) ) do;
GRP_ACT_AGE  = 7 ;
end;
otherwise GRP_ACT_AGE  = 8 ; end;
select;
when ( not missing(ACT_CALL_CC) and ACT_CALL_CC <= 0.2236893204 ) do;
GRP_ACT_CALL_CC  = 1 ;
end;
when ( 0.2236893204 < ACT_CALL_CC <= 0.2649882268 ) do;
GRP_ACT_CALL_CC  = 2 ;
end;
when ( 0.2649882268 < ACT_CALL_CC <= 0.828313253 ) do;
GRP_ACT_CALL_CC  = 3 ;
end;
when ( 0.828313253 < ACT_CALL_CC <= 0.9644268775 ) do;
GRP_ACT_CALL_CC  = 4 ;
end;
when ( 0.9644268775 < ACT_CALL_CC <= 1.1508379888 ) do;
GRP_ACT_CALL_CC  = 5 ;
end;
when ( 1.1508379888 < ACT_CALL_CC ) do;
GRP_ACT_CALL_CC  = 6 ;
end;
when ( missing(ACT_CALL_CC) ) do;
GRP_ACT_CALL_CC  = 7 ;
end;
otherwise GRP_ACT_CALL_CC  = 8 ; end;
select;
when ( not missing(ACT_CALL_N_LOAN) ) do;
GRP_ACT_CALL_N_LOAN  = 1 ;
end;
when ( missing(ACT_CALL_N_LOAN) ) do;
GRP_ACT_CALL_N_LOAN  = 2 ;
end;
otherwise GRP_ACT_CALL_N_LOAN  = 3 ; end;
select;
when ( not missing(ACT_CC) and ACT_CC <= 0.2236893204 ) do;
GRP_ACT_CC  = 1 ;
end;
when ( 0.2236893204 < ACT_CC <= 0.2649882268 ) do;
GRP_ACT_CC  = 2 ;
end;
when ( 0.2649882268 < ACT_CC <= 0.828313253 ) do;
GRP_ACT_CC  = 3 ;
end;
when ( 0.828313253 < ACT_CC <= 0.9644268775 ) do;
GRP_ACT_CC  = 4 ;
end;
when ( 0.9644268775 < ACT_CC <= 1.1508379888 ) do;
GRP_ACT_CC  = 5 ;
end;
when ( 1.1508379888 < ACT_CC ) do;
GRP_ACT_CC  = 6 ;
end;
when ( missing(ACT_CC) ) do;
GRP_ACT_CC  = 7 ;
end;
otherwise GRP_ACT_CC  = 8 ; end;
select;
when ( not missing(ACT_CCSS_CC) ) do;
GRP_ACT_CCSS_CC  = 1 ;
end;
when ( missing(ACT_CCSS_CC) ) do;
GRP_ACT_CCSS_CC  = 2 ;
end;
otherwise GRP_ACT_CCSS_CC  = 3 ; end;
select;
when ( not missing(ACT_CCSS_DUEUTL) ) do;
GRP_ACT_CCSS_DUEUTL  = 1 ;
end;
when ( missing(ACT_CCSS_DUEUTL) ) do;
GRP_ACT_CCSS_DUEUTL  = 2 ;
end;
otherwise GRP_ACT_CCSS_DUEUTL  = 3 ; end;
select;
when ( not missing(ACT_CCSS_MAXDUE) ) do;
GRP_ACT_CCSS_MAXDUE  = 1 ;
end;
when ( missing(ACT_CCSS_MAXDUE) ) do;
GRP_ACT_CCSS_MAXDUE  = 2 ;
end;
otherwise GRP_ACT_CCSS_MAXDUE  = 3 ; end;
select;
when ( not missing(ACT_CCSS_MIN_LNINST) ) do;
GRP_ACT_CCSS_MIN_LNINST  = 1 ;
end;
when ( missing(ACT_CCSS_MIN_LNINST) ) do;
GRP_ACT_CCSS_MIN_LNINST  = 2 ;
end;
otherwise GRP_ACT_CCSS_MIN_LNINST  = 3 ; end;
select;
when ( not missing(ACT_CCSS_MIN_PNINST) ) do;
GRP_ACT_CCSS_MIN_PNINST  = 1 ;
end;
when ( missing(ACT_CCSS_MIN_PNINST) ) do;
GRP_ACT_CCSS_MIN_PNINST  = 2 ;
end;
otherwise GRP_ACT_CCSS_MIN_PNINST  = 3 ; end;
select;
when ( not missing(ACT_CCSS_MIN_SENIORITY) ) do;
GRP_ACT_CCSS_MIN_SENIORITY  = 1 ;
end;
when ( missing(ACT_CCSS_MIN_SENIORITY) ) do;
GRP_ACT_CCSS_MIN_SENIORITY  = 2 ;
end;
otherwise GRP_ACT_CCSS_MIN_SENIORITY  = 3 ; end;
select;
when ( not missing(ACT_CCSS_N_LOAN) ) do;
GRP_ACT_CCSS_N_LOAN  = 1 ;
end;
when ( missing(ACT_CCSS_N_LOAN) ) do;
GRP_ACT_CCSS_N_LOAN  = 2 ;
end;
otherwise GRP_ACT_CCSS_N_LOAN  = 3 ; end;
select;
when ( not missing(ACT_CCSS_N_LOANS_ACT) ) do;
GRP_ACT_CCSS_N_LOANS_ACT  = 1 ;
end;
when ( missing(ACT_CCSS_N_LOANS_ACT) ) do;
GRP_ACT_CCSS_N_LOANS_ACT  = 2 ;
end;
otherwise GRP_ACT_CCSS_N_LOANS_ACT  = 3 ; end;
select;
when ( not missing(ACT_CCSS_N_LOANS_HIST) ) do;
GRP_ACT_CCSS_N_LOANS_HIST  = 1 ;
end;
when ( missing(ACT_CCSS_N_LOANS_HIST) ) do;
GRP_ACT_CCSS_N_LOANS_HIST  = 2 ;
end;
otherwise GRP_ACT_CCSS_N_LOANS_HIST  = 3 ; end;
select;
when ( not missing(ACT_CCSS_N_STATB) ) do;
GRP_ACT_CCSS_N_STATB  = 1 ;
end;
when ( missing(ACT_CCSS_N_STATB) ) do;
GRP_ACT_CCSS_N_STATB  = 2 ;
end;
otherwise GRP_ACT_CCSS_N_STATB  = 3 ; end;
select;
when ( not missing(ACT_CCSS_N_STATC) ) do;
GRP_ACT_CCSS_N_STATC  = 1 ;
end;
when ( missing(ACT_CCSS_N_STATC) ) do;
GRP_ACT_CCSS_N_STATC  = 2 ;
end;
otherwise GRP_ACT_CCSS_N_STATC  = 3 ; end;
select;
when ( not missing(ACT_CCSS_SENIORITY) ) do;
GRP_ACT_CCSS_SENIORITY  = 1 ;
end;
when ( missing(ACT_CCSS_SENIORITY) ) do;
GRP_ACT_CCSS_SENIORITY  = 2 ;
end;
otherwise GRP_ACT_CCSS_SENIORITY  = 3 ; end;
select;
when ( not missing(ACT_CCSS_UTL) ) do;
GRP_ACT_CCSS_UTL  = 1 ;
end;
when ( missing(ACT_CCSS_UTL) ) do;
GRP_ACT_CCSS_UTL  = 2 ;
end;
otherwise GRP_ACT_CCSS_UTL  = 3 ; end;
select;
when ( not missing(ACT_CINS_CC) ) do;
GRP_ACT_CINS_CC  = 1 ;
end;
when ( missing(ACT_CINS_CC) ) do;
GRP_ACT_CINS_CC  = 2 ;
end;
otherwise GRP_ACT_CINS_CC  = 3 ; end;
select;
when ( not missing(ACT_CINS_DUEUTL) ) do;
GRP_ACT_CINS_DUEUTL  = 1 ;
end;
when ( missing(ACT_CINS_DUEUTL) ) do;
GRP_ACT_CINS_DUEUTL  = 2 ;
end;
otherwise GRP_ACT_CINS_DUEUTL  = 3 ; end;
select;
when ( not missing(ACT_CINS_MAXDUE) ) do;
GRP_ACT_CINS_MAXDUE  = 1 ;
end;
when ( missing(ACT_CINS_MAXDUE) ) do;
GRP_ACT_CINS_MAXDUE  = 2 ;
end;
otherwise GRP_ACT_CINS_MAXDUE  = 3 ; end;
select;
when ( not missing(ACT_CINS_MIN_LNINST) ) do;
GRP_ACT_CINS_MIN_LNINST  = 1 ;
end;
when ( missing(ACT_CINS_MIN_LNINST) ) do;
GRP_ACT_CINS_MIN_LNINST  = 2 ;
end;
otherwise GRP_ACT_CINS_MIN_LNINST  = 3 ; end;
select;
when ( not missing(ACT_CINS_MIN_PNINST) ) do;
GRP_ACT_CINS_MIN_PNINST  = 1 ;
end;
when ( missing(ACT_CINS_MIN_PNINST) ) do;
GRP_ACT_CINS_MIN_PNINST  = 2 ;
end;
otherwise GRP_ACT_CINS_MIN_PNINST  = 3 ; end;
select;
when ( not missing(ACT_CINS_MIN_SENIORITY) ) do;
GRP_ACT_CINS_MIN_SENIORITY  = 1 ;
end;
when ( missing(ACT_CINS_MIN_SENIORITY) ) do;
GRP_ACT_CINS_MIN_SENIORITY  = 2 ;
end;
otherwise GRP_ACT_CINS_MIN_SENIORITY  = 3 ; end;
select;
when ( not missing(ACT_CINS_N_LOAN) ) do;
GRP_ACT_CINS_N_LOAN  = 1 ;
end;
when ( missing(ACT_CINS_N_LOAN) ) do;
GRP_ACT_CINS_N_LOAN  = 2 ;
end;
otherwise GRP_ACT_CINS_N_LOAN  = 3 ; end;
select;
when ( not missing(ACT_CINS_N_LOANS_ACT) ) do;
GRP_ACT_CINS_N_LOANS_ACT  = 1 ;
end;
when ( missing(ACT_CINS_N_LOANS_ACT) ) do;
GRP_ACT_CINS_N_LOANS_ACT  = 2 ;
end;
otherwise GRP_ACT_CINS_N_LOANS_ACT  = 3 ; end;
select;
when ( not missing(ACT_CINS_N_LOANS_HIST) ) do;
GRP_ACT_CINS_N_LOANS_HIST  = 1 ;
end;
when ( missing(ACT_CINS_N_LOANS_HIST) ) do;
GRP_ACT_CINS_N_LOANS_HIST  = 2 ;
end;
otherwise GRP_ACT_CINS_N_LOANS_HIST  = 3 ; end;
select;
when ( not missing(ACT_CINS_N_STATB) ) do;
GRP_ACT_CINS_N_STATB  = 1 ;
end;
when ( missing(ACT_CINS_N_STATB) ) do;
GRP_ACT_CINS_N_STATB  = 2 ;
end;
otherwise GRP_ACT_CINS_N_STATB  = 3 ; end;
select;
when ( not missing(ACT_CINS_N_STATC) ) do;
GRP_ACT_CINS_N_STATC  = 1 ;
end;
when ( missing(ACT_CINS_N_STATC) ) do;
GRP_ACT_CINS_N_STATC  = 2 ;
end;
otherwise GRP_ACT_CINS_N_STATC  = 3 ; end;
select;
when ( not missing(ACT_CINS_SENIORITY) ) do;
GRP_ACT_CINS_SENIORITY  = 1 ;
end;
when ( missing(ACT_CINS_SENIORITY) ) do;
GRP_ACT_CINS_SENIORITY  = 2 ;
end;
otherwise GRP_ACT_CINS_SENIORITY  = 3 ; end;
select;
when ( not missing(ACT_CINS_UTL) ) do;
GRP_ACT_CINS_UTL  = 1 ;
end;
when ( missing(ACT_CINS_UTL) ) do;
GRP_ACT_CINS_UTL  = 2 ;
end;
otherwise GRP_ACT_CINS_UTL  = 3 ; end;
select;
when ( not missing(ACT_CUS_ACTIVE) ) do;
GRP_ACT_CUS_ACTIVE  = 1 ;
end;
when ( missing(ACT_CUS_ACTIVE) ) do;
GRP_ACT_CUS_ACTIVE  = 2 ;
end;
otherwise GRP_ACT_CUS_ACTIVE  = 3 ; end;
select;
when ( not missing(ACT_LOANINC) and ACT_LOANINC <= 1.9841840403 ) do;
GRP_ACT_LOANINC  = 1 ;
end;
when ( 1.9841840403 < ACT_LOANINC <= 2.5159620362 ) do;
GRP_ACT_LOANINC  = 2 ;
end;
when ( 2.5159620362 < ACT_LOANINC <= 5.6727272727 ) do;
GRP_ACT_LOANINC  = 3 ;
end;
when ( 5.6727272727 < ACT_LOANINC <= 8.600422833 ) do;
GRP_ACT_LOANINC  = 4 ;
end;
when ( 8.600422833 < ACT_LOANINC <= 15.348837209 ) do;
GRP_ACT_LOANINC  = 5 ;
end;
when ( 15.348837209 < ACT_LOANINC ) do;
GRP_ACT_LOANINC  = 6 ;
end;
when ( missing(ACT_LOANINC) ) do;
GRP_ACT_LOANINC  = 7 ;
end;
otherwise GRP_ACT_LOANINC  = 8 ; end;
select;
when ( not missing(AGR12_MAX_CMAXA_DAYS) ) do;
GRP_AGR12_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR12_MAX_CMAXA_DAYS) ) do;
GRP_AGR12_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MAX_CMAXA_DUE) ) do;
GRP_AGR12_MAX_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR12_MAX_CMAXA_DUE) ) do;
GRP_AGR12_MAX_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR12_MAX_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MAX_CMAXC_DAYS) ) do;
GRP_AGR12_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR12_MAX_CMAXC_DAYS) ) do;
GRP_AGR12_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MAX_CMAXC_DUE) ) do;
GRP_AGR12_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR12_MAX_CMAXC_DUE) ) do;
GRP_AGR12_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR12_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MAX_CMAXI_DAYS) ) do;
GRP_AGR12_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR12_MAX_CMAXI_DAYS) ) do;
GRP_AGR12_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MAX_CMAXI_DUE) ) do;
GRP_AGR12_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR12_MAX_CMAXI_DUE) ) do;
GRP_AGR12_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR12_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXA_DAYS) ) do;
GRP_AGR12_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR12_MEAN_CMAXA_DAYS) ) do;
GRP_AGR12_MEAN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MEAN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXA_DUE) ) do;
GRP_AGR12_MEAN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR12_MEAN_CMAXA_DUE) ) do;
GRP_AGR12_MEAN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR12_MEAN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXC_DAYS) ) do;
GRP_AGR12_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR12_MEAN_CMAXC_DAYS) ) do;
GRP_AGR12_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXC_DUE) ) do;
GRP_AGR12_MEAN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR12_MEAN_CMAXC_DUE) ) do;
GRP_AGR12_MEAN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR12_MEAN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXI_DAYS) ) do;
GRP_AGR12_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR12_MEAN_CMAXI_DAYS) ) do;
GRP_AGR12_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXI_DUE) ) do;
GRP_AGR12_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR12_MEAN_CMAXI_DUE) ) do;
GRP_AGR12_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR12_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MIN_CMAXA_DAYS) ) do;
GRP_AGR12_MIN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR12_MIN_CMAXA_DAYS) ) do;
GRP_AGR12_MIN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MIN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MIN_CMAXA_DUE) ) do;
GRP_AGR12_MIN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR12_MIN_CMAXA_DUE) ) do;
GRP_AGR12_MIN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR12_MIN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MIN_CMAXC_DAYS) ) do;
GRP_AGR12_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR12_MIN_CMAXC_DAYS) ) do;
GRP_AGR12_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MIN_CMAXC_DUE) ) do;
GRP_AGR12_MIN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR12_MIN_CMAXC_DUE) ) do;
GRP_AGR12_MIN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR12_MIN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MIN_CMAXI_DAYS) ) do;
GRP_AGR12_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR12_MIN_CMAXI_DAYS) ) do;
GRP_AGR12_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MIN_CMAXI_DUE) ) do;
GRP_AGR12_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR12_MIN_CMAXI_DUE) ) do;
GRP_AGR12_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR12_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MAX_CMAXA_DAYS) ) do;
GRP_AGR3_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR3_MAX_CMAXA_DAYS) ) do;
GRP_AGR3_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MAX_CMAXA_DUE) ) do;
GRP_AGR3_MAX_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR3_MAX_CMAXA_DUE) ) do;
GRP_AGR3_MAX_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR3_MAX_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MAX_CMAXC_DAYS) ) do;
GRP_AGR3_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR3_MAX_CMAXC_DAYS) ) do;
GRP_AGR3_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MAX_CMAXC_DUE) ) do;
GRP_AGR3_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR3_MAX_CMAXC_DUE) ) do;
GRP_AGR3_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR3_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MAX_CMAXI_DAYS) ) do;
GRP_AGR3_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR3_MAX_CMAXI_DAYS) ) do;
GRP_AGR3_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MAX_CMAXI_DUE) ) do;
GRP_AGR3_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR3_MAX_CMAXI_DUE) ) do;
GRP_AGR3_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR3_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXA_DAYS) ) do;
GRP_AGR3_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR3_MEAN_CMAXA_DAYS) ) do;
GRP_AGR3_MEAN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MEAN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXA_DUE) ) do;
GRP_AGR3_MEAN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR3_MEAN_CMAXA_DUE) ) do;
GRP_AGR3_MEAN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR3_MEAN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXC_DAYS) ) do;
GRP_AGR3_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR3_MEAN_CMAXC_DAYS) ) do;
GRP_AGR3_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXC_DUE) ) do;
GRP_AGR3_MEAN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR3_MEAN_CMAXC_DUE) ) do;
GRP_AGR3_MEAN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR3_MEAN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXI_DAYS) ) do;
GRP_AGR3_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR3_MEAN_CMAXI_DAYS) ) do;
GRP_AGR3_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXI_DUE) ) do;
GRP_AGR3_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR3_MEAN_CMAXI_DUE) ) do;
GRP_AGR3_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR3_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MIN_CMAXA_DAYS) ) do;
GRP_AGR3_MIN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR3_MIN_CMAXA_DAYS) ) do;
GRP_AGR3_MIN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MIN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MIN_CMAXA_DUE) ) do;
GRP_AGR3_MIN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR3_MIN_CMAXA_DUE) ) do;
GRP_AGR3_MIN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR3_MIN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MIN_CMAXC_DAYS) ) do;
GRP_AGR3_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR3_MIN_CMAXC_DAYS) ) do;
GRP_AGR3_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MIN_CMAXC_DUE) ) do;
GRP_AGR3_MIN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR3_MIN_CMAXC_DUE) ) do;
GRP_AGR3_MIN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR3_MIN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MIN_CMAXI_DAYS) ) do;
GRP_AGR3_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR3_MIN_CMAXI_DAYS) ) do;
GRP_AGR3_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MIN_CMAXI_DUE) ) do;
GRP_AGR3_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR3_MIN_CMAXI_DUE) ) do;
GRP_AGR3_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR3_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MAX_CMAXA_DAYS) ) do;
GRP_AGR6_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR6_MAX_CMAXA_DAYS) ) do;
GRP_AGR6_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MAX_CMAXA_DUE) ) do;
GRP_AGR6_MAX_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR6_MAX_CMAXA_DUE) ) do;
GRP_AGR6_MAX_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR6_MAX_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MAX_CMAXC_DAYS) ) do;
GRP_AGR6_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR6_MAX_CMAXC_DAYS) ) do;
GRP_AGR6_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MAX_CMAXC_DUE) ) do;
GRP_AGR6_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR6_MAX_CMAXC_DUE) ) do;
GRP_AGR6_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR6_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MAX_CMAXI_DAYS) ) do;
GRP_AGR6_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR6_MAX_CMAXI_DAYS) ) do;
GRP_AGR6_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MAX_CMAXI_DUE) ) do;
GRP_AGR6_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR6_MAX_CMAXI_DUE) ) do;
GRP_AGR6_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR6_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXA_DAYS) ) do;
GRP_AGR6_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR6_MEAN_CMAXA_DAYS) ) do;
GRP_AGR6_MEAN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MEAN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXA_DUE) ) do;
GRP_AGR6_MEAN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR6_MEAN_CMAXA_DUE) ) do;
GRP_AGR6_MEAN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR6_MEAN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXC_DAYS) ) do;
GRP_AGR6_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR6_MEAN_CMAXC_DAYS) ) do;
GRP_AGR6_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXC_DUE) ) do;
GRP_AGR6_MEAN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR6_MEAN_CMAXC_DUE) ) do;
GRP_AGR6_MEAN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR6_MEAN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXI_DAYS) ) do;
GRP_AGR6_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR6_MEAN_CMAXI_DAYS) ) do;
GRP_AGR6_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXI_DUE) ) do;
GRP_AGR6_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR6_MEAN_CMAXI_DUE) ) do;
GRP_AGR6_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR6_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MIN_CMAXA_DAYS) ) do;
GRP_AGR6_MIN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR6_MIN_CMAXA_DAYS) ) do;
GRP_AGR6_MIN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MIN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MIN_CMAXA_DUE) ) do;
GRP_AGR6_MIN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR6_MIN_CMAXA_DUE) ) do;
GRP_AGR6_MIN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR6_MIN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MIN_CMAXC_DAYS) ) do;
GRP_AGR6_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR6_MIN_CMAXC_DAYS) ) do;
GRP_AGR6_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MIN_CMAXC_DUE) ) do;
GRP_AGR6_MIN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR6_MIN_CMAXC_DUE) ) do;
GRP_AGR6_MIN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR6_MIN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MIN_CMAXI_DAYS) ) do;
GRP_AGR6_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR6_MIN_CMAXI_DAYS) ) do;
GRP_AGR6_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MIN_CMAXI_DUE) ) do;
GRP_AGR6_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR6_MIN_CMAXI_DUE) ) do;
GRP_AGR6_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR6_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MAX_CMAXA_DAYS) ) do;
GRP_AGR9_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR9_MAX_CMAXA_DAYS) ) do;
GRP_AGR9_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MAX_CMAXA_DUE) ) do;
GRP_AGR9_MAX_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR9_MAX_CMAXA_DUE) ) do;
GRP_AGR9_MAX_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR9_MAX_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MAX_CMAXC_DAYS) ) do;
GRP_AGR9_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR9_MAX_CMAXC_DAYS) ) do;
GRP_AGR9_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MAX_CMAXC_DUE) ) do;
GRP_AGR9_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR9_MAX_CMAXC_DUE) ) do;
GRP_AGR9_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR9_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MAX_CMAXI_DAYS) ) do;
GRP_AGR9_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR9_MAX_CMAXI_DAYS) ) do;
GRP_AGR9_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MAX_CMAXI_DUE) ) do;
GRP_AGR9_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR9_MAX_CMAXI_DUE) ) do;
GRP_AGR9_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR9_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXA_DAYS) ) do;
GRP_AGR9_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR9_MEAN_CMAXA_DAYS) ) do;
GRP_AGR9_MEAN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MEAN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXA_DUE) ) do;
GRP_AGR9_MEAN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR9_MEAN_CMAXA_DUE) ) do;
GRP_AGR9_MEAN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR9_MEAN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXC_DAYS) ) do;
GRP_AGR9_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR9_MEAN_CMAXC_DAYS) ) do;
GRP_AGR9_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXC_DUE) ) do;
GRP_AGR9_MEAN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR9_MEAN_CMAXC_DUE) ) do;
GRP_AGR9_MEAN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR9_MEAN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXI_DAYS) ) do;
GRP_AGR9_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR9_MEAN_CMAXI_DAYS) ) do;
GRP_AGR9_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXI_DUE) ) do;
GRP_AGR9_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR9_MEAN_CMAXI_DUE) ) do;
GRP_AGR9_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR9_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MIN_CMAXA_DAYS) ) do;
GRP_AGR9_MIN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR9_MIN_CMAXA_DAYS) ) do;
GRP_AGR9_MIN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MIN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MIN_CMAXA_DUE) ) do;
GRP_AGR9_MIN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR9_MIN_CMAXA_DUE) ) do;
GRP_AGR9_MIN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR9_MIN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MIN_CMAXC_DAYS) ) do;
GRP_AGR9_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR9_MIN_CMAXC_DAYS) ) do;
GRP_AGR9_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MIN_CMAXC_DUE) ) do;
GRP_AGR9_MIN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR9_MIN_CMAXC_DUE) ) do;
GRP_AGR9_MIN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR9_MIN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MIN_CMAXI_DAYS) ) do;
GRP_AGR9_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR9_MIN_CMAXI_DAYS) ) do;
GRP_AGR9_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MIN_CMAXI_DUE) ) do;
GRP_AGR9_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR9_MIN_CMAXI_DUE) ) do;
GRP_AGR9_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR9_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS12_MAX_CMAXA_DAYS) ) do;
GRP_AGS12_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS12_MAX_CMAXA_DAYS) ) do;
GRP_AGS12_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MAX_CMAXA_DUE) ) do;
GRP_AGS12_MAX_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS12_MAX_CMAXA_DUE) ) do;
GRP_AGS12_MAX_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS12_MAX_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS12_MAX_CMAXC_DAYS) ) do;
GRP_AGS12_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS12_MAX_CMAXC_DAYS) ) do;
GRP_AGS12_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MAX_CMAXC_DUE) ) do;
GRP_AGS12_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS12_MAX_CMAXC_DUE) ) do;
GRP_AGS12_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS12_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS12_MAX_CMAXI_DAYS) ) do;
GRP_AGS12_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS12_MAX_CMAXI_DAYS) ) do;
GRP_AGS12_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MAX_CMAXI_DUE) ) do;
GRP_AGS12_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS12_MAX_CMAXI_DUE) ) do;
GRP_AGS12_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS12_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXA_DAYS) ) do;
GRP_AGS12_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS12_MEAN_CMAXA_DAYS) ) do;
GRP_AGS12_MEAN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MEAN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXA_DUE) ) do;
GRP_AGS12_MEAN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS12_MEAN_CMAXA_DUE) ) do;
GRP_AGS12_MEAN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS12_MEAN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXC_DAYS) ) do;
GRP_AGS12_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS12_MEAN_CMAXC_DAYS) ) do;
GRP_AGS12_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXC_DUE) ) do;
GRP_AGS12_MEAN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS12_MEAN_CMAXC_DUE) ) do;
GRP_AGS12_MEAN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS12_MEAN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXI_DAYS) ) do;
GRP_AGS12_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS12_MEAN_CMAXI_DAYS) ) do;
GRP_AGS12_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXI_DUE) ) do;
GRP_AGS12_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS12_MEAN_CMAXI_DUE) ) do;
GRP_AGS12_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS12_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS12_MIN_CMAXA_DAYS) ) do;
GRP_AGS12_MIN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS12_MIN_CMAXA_DAYS) ) do;
GRP_AGS12_MIN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MIN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MIN_CMAXA_DUE) ) do;
GRP_AGS12_MIN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS12_MIN_CMAXA_DUE) ) do;
GRP_AGS12_MIN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS12_MIN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS12_MIN_CMAXC_DAYS) ) do;
GRP_AGS12_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS12_MIN_CMAXC_DAYS) ) do;
GRP_AGS12_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MIN_CMAXC_DUE) ) do;
GRP_AGS12_MIN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS12_MIN_CMAXC_DUE) ) do;
GRP_AGS12_MIN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS12_MIN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS12_MIN_CMAXI_DAYS) ) do;
GRP_AGS12_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS12_MIN_CMAXI_DAYS) ) do;
GRP_AGS12_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MIN_CMAXI_DUE) ) do;
GRP_AGS12_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS12_MIN_CMAXI_DUE) ) do;
GRP_AGS12_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS12_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MAX_CMAXA_DAYS) ) do;
GRP_AGS3_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS3_MAX_CMAXA_DAYS) ) do;
GRP_AGS3_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MAX_CMAXA_DUE) ) do;
GRP_AGS3_MAX_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS3_MAX_CMAXA_DUE) ) do;
GRP_AGS3_MAX_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS3_MAX_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MAX_CMAXC_DAYS) ) do;
GRP_AGS3_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS3_MAX_CMAXC_DAYS) ) do;
GRP_AGS3_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MAX_CMAXC_DUE) ) do;
GRP_AGS3_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS3_MAX_CMAXC_DUE) ) do;
GRP_AGS3_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS3_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MAX_CMAXI_DAYS) ) do;
GRP_AGS3_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS3_MAX_CMAXI_DAYS) ) do;
GRP_AGS3_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MAX_CMAXI_DUE) ) do;
GRP_AGS3_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS3_MAX_CMAXI_DUE) ) do;
GRP_AGS3_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS3_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXA_DAYS) ) do;
GRP_AGS3_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS3_MEAN_CMAXA_DAYS) ) do;
GRP_AGS3_MEAN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MEAN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXA_DUE) ) do;
GRP_AGS3_MEAN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS3_MEAN_CMAXA_DUE) ) do;
GRP_AGS3_MEAN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS3_MEAN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXC_DAYS) ) do;
GRP_AGS3_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS3_MEAN_CMAXC_DAYS) ) do;
GRP_AGS3_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXC_DUE) ) do;
GRP_AGS3_MEAN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS3_MEAN_CMAXC_DUE) ) do;
GRP_AGS3_MEAN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS3_MEAN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXI_DAYS) ) do;
GRP_AGS3_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS3_MEAN_CMAXI_DAYS) ) do;
GRP_AGS3_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXI_DUE) ) do;
GRP_AGS3_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS3_MEAN_CMAXI_DUE) ) do;
GRP_AGS3_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS3_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MIN_CMAXA_DAYS) ) do;
GRP_AGS3_MIN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS3_MIN_CMAXA_DAYS) ) do;
GRP_AGS3_MIN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MIN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MIN_CMAXA_DUE) ) do;
GRP_AGS3_MIN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS3_MIN_CMAXA_DUE) ) do;
GRP_AGS3_MIN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS3_MIN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MIN_CMAXC_DAYS) ) do;
GRP_AGS3_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS3_MIN_CMAXC_DAYS) ) do;
GRP_AGS3_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MIN_CMAXC_DUE) ) do;
GRP_AGS3_MIN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS3_MIN_CMAXC_DUE) ) do;
GRP_AGS3_MIN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS3_MIN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MIN_CMAXI_DAYS) ) do;
GRP_AGS3_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS3_MIN_CMAXI_DAYS) ) do;
GRP_AGS3_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MIN_CMAXI_DUE) ) do;
GRP_AGS3_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS3_MIN_CMAXI_DUE) ) do;
GRP_AGS3_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS3_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MAX_CMAXA_DAYS) ) do;
GRP_AGS6_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS6_MAX_CMAXA_DAYS) ) do;
GRP_AGS6_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MAX_CMAXA_DUE) ) do;
GRP_AGS6_MAX_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS6_MAX_CMAXA_DUE) ) do;
GRP_AGS6_MAX_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS6_MAX_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MAX_CMAXC_DAYS) ) do;
GRP_AGS6_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS6_MAX_CMAXC_DAYS) ) do;
GRP_AGS6_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MAX_CMAXC_DUE) ) do;
GRP_AGS6_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS6_MAX_CMAXC_DUE) ) do;
GRP_AGS6_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS6_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MAX_CMAXI_DAYS) ) do;
GRP_AGS6_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS6_MAX_CMAXI_DAYS) ) do;
GRP_AGS6_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MAX_CMAXI_DUE) ) do;
GRP_AGS6_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS6_MAX_CMAXI_DUE) ) do;
GRP_AGS6_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS6_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXA_DAYS) ) do;
GRP_AGS6_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS6_MEAN_CMAXA_DAYS) ) do;
GRP_AGS6_MEAN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MEAN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXA_DUE) ) do;
GRP_AGS6_MEAN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS6_MEAN_CMAXA_DUE) ) do;
GRP_AGS6_MEAN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS6_MEAN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXC_DAYS) ) do;
GRP_AGS6_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS6_MEAN_CMAXC_DAYS) ) do;
GRP_AGS6_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXC_DUE) ) do;
GRP_AGS6_MEAN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS6_MEAN_CMAXC_DUE) ) do;
GRP_AGS6_MEAN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS6_MEAN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXI_DAYS) ) do;
GRP_AGS6_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS6_MEAN_CMAXI_DAYS) ) do;
GRP_AGS6_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXI_DUE) ) do;
GRP_AGS6_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS6_MEAN_CMAXI_DUE) ) do;
GRP_AGS6_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS6_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MIN_CMAXA_DAYS) ) do;
GRP_AGS6_MIN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS6_MIN_CMAXA_DAYS) ) do;
GRP_AGS6_MIN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MIN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MIN_CMAXA_DUE) ) do;
GRP_AGS6_MIN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS6_MIN_CMAXA_DUE) ) do;
GRP_AGS6_MIN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS6_MIN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MIN_CMAXC_DAYS) ) do;
GRP_AGS6_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS6_MIN_CMAXC_DAYS) ) do;
GRP_AGS6_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MIN_CMAXC_DUE) ) do;
GRP_AGS6_MIN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS6_MIN_CMAXC_DUE) ) do;
GRP_AGS6_MIN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS6_MIN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MIN_CMAXI_DAYS) ) do;
GRP_AGS6_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS6_MIN_CMAXI_DAYS) ) do;
GRP_AGS6_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MIN_CMAXI_DUE) ) do;
GRP_AGS6_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS6_MIN_CMAXI_DUE) ) do;
GRP_AGS6_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS6_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MAX_CMAXA_DAYS) ) do;
GRP_AGS9_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS9_MAX_CMAXA_DAYS) ) do;
GRP_AGS9_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MAX_CMAXA_DUE) ) do;
GRP_AGS9_MAX_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS9_MAX_CMAXA_DUE) ) do;
GRP_AGS9_MAX_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS9_MAX_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MAX_CMAXC_DAYS) ) do;
GRP_AGS9_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS9_MAX_CMAXC_DAYS) ) do;
GRP_AGS9_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MAX_CMAXC_DUE) ) do;
GRP_AGS9_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS9_MAX_CMAXC_DUE) ) do;
GRP_AGS9_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS9_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MAX_CMAXI_DAYS) ) do;
GRP_AGS9_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS9_MAX_CMAXI_DAYS) ) do;
GRP_AGS9_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MAX_CMAXI_DUE) ) do;
GRP_AGS9_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS9_MAX_CMAXI_DUE) ) do;
GRP_AGS9_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS9_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXA_DAYS) ) do;
GRP_AGS9_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS9_MEAN_CMAXA_DAYS) ) do;
GRP_AGS9_MEAN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MEAN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXA_DUE) ) do;
GRP_AGS9_MEAN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS9_MEAN_CMAXA_DUE) ) do;
GRP_AGS9_MEAN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS9_MEAN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXC_DAYS) ) do;
GRP_AGS9_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS9_MEAN_CMAXC_DAYS) ) do;
GRP_AGS9_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXC_DUE) ) do;
GRP_AGS9_MEAN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS9_MEAN_CMAXC_DUE) ) do;
GRP_AGS9_MEAN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS9_MEAN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXI_DAYS) ) do;
GRP_AGS9_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS9_MEAN_CMAXI_DAYS) ) do;
GRP_AGS9_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXI_DUE) ) do;
GRP_AGS9_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS9_MEAN_CMAXI_DUE) ) do;
GRP_AGS9_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS9_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MIN_CMAXA_DAYS) ) do;
GRP_AGS9_MIN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS9_MIN_CMAXA_DAYS) ) do;
GRP_AGS9_MIN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MIN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MIN_CMAXA_DUE) ) do;
GRP_AGS9_MIN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS9_MIN_CMAXA_DUE) ) do;
GRP_AGS9_MIN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS9_MIN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MIN_CMAXC_DAYS) ) do;
GRP_AGS9_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS9_MIN_CMAXC_DAYS) ) do;
GRP_AGS9_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MIN_CMAXC_DUE) ) do;
GRP_AGS9_MIN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS9_MIN_CMAXC_DUE) ) do;
GRP_AGS9_MIN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS9_MIN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MIN_CMAXI_DAYS) ) do;
GRP_AGS9_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS9_MIN_CMAXI_DAYS) ) do;
GRP_AGS9_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MIN_CMAXI_DUE) ) do;
GRP_AGS9_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS9_MIN_CMAXI_DUE) ) do;
GRP_AGS9_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS9_MIN_CMAXI_DUE  = 3 ; end;
select (APP_CHAR_BRANCH );
  when ('Computers')   do;
GRP_APP_CHAR_BRANCH  = 1 ;
end;
  when ('Radio-TV')   do;
GRP_APP_CHAR_BRANCH  = 2 ;
end;
  when ('Fenitures')   do;
GRP_APP_CHAR_BRANCH  = 3 ;
end;
  when ('DiY')   do;
GRP_APP_CHAR_BRANCH  = 4 ;
end;
otherwise GRP_APP_CHAR_BRANCH  = 5 ; end;
select (APP_CHAR_CARS );
  when ('No')   do;
GRP_APP_CHAR_CARS  = 1 ;
end;
  when ('Owner')   do;
GRP_APP_CHAR_CARS  = 2 ;
end;
otherwise GRP_APP_CHAR_CARS  = 3 ; end;
select (APP_CHAR_CITY );
  when ('Large')   do;
GRP_APP_CHAR_CITY  = 1 ;
end;
  when ('Medium')   do;
GRP_APP_CHAR_CITY  = 2 ;
end;
  when ('Small')   do;
GRP_APP_CHAR_CITY  = 3 ;
end;
  when ('Big')   do;
GRP_APP_CHAR_CITY  = 4 ;
end;
otherwise GRP_APP_CHAR_CITY  = 5 ; end;
select (APP_CHAR_GENDER );
  when ('Female')   do;
GRP_APP_CHAR_GENDER  = 1 ;
end;
  when ('Male')   do;
GRP_APP_CHAR_GENDER  = 2 ;
end;
otherwise GRP_APP_CHAR_GENDER  = 3 ; end;
select (APP_CHAR_HOME_STATUS );
  when ('Owner')   do;
GRP_APP_CHAR_HOME_STATUS  = 1 ;
end;
  when ('Rental')   do;
GRP_APP_CHAR_HOME_STATUS  = 2 ;
end;
otherwise GRP_APP_CHAR_HOME_STATUS  = 3 ; end;
select (APP_CHAR_JOB_CODE );
  when ('Permanent')   do;
GRP_APP_CHAR_JOB_CODE  = 1 ;
end;
  when ('Retired')   do;
GRP_APP_CHAR_JOB_CODE  = 2 ;
end;
  when ('Owner company')   do;
GRP_APP_CHAR_JOB_CODE  = 3 ;
end;
  when ('Contract')   do;
GRP_APP_CHAR_JOB_CODE  = 4 ;
end;
otherwise GRP_APP_CHAR_JOB_CODE  = 5 ; end;
select (APP_CHAR_MARITAL_STATUS );
  when ('Maried')   do;
GRP_APP_CHAR_MARITAL_STATUS  = 1 ;
end;
  when ('Widowed')   do;
GRP_APP_CHAR_MARITAL_STATUS  = 2 ;
end;
  when ('Divorced')   do;
GRP_APP_CHAR_MARITAL_STATUS  = 3 ;
end;
  when ('Singiel')   do;
GRP_APP_CHAR_MARITAL_STATUS  = 4 ;
end;
otherwise GRP_APP_CHAR_MARITAL_STATUS  = 5 ; end;
select;
when ( not missing(APP_INCOME) and APP_INCOME <= 421 ) do;
GRP_APP_INCOME  = 1 ;
end;
when ( 421 < APP_INCOME <= 605 ) do;
GRP_APP_INCOME  = 2 ;
end;
when ( 605 < APP_INCOME <= 906 ) do;
GRP_APP_INCOME  = 3 ;
end;
when ( 906 < APP_INCOME <= 1225 ) do;
GRP_APP_INCOME  = 4 ;
end;
when ( 1225 < APP_INCOME <= 4626 ) do;
GRP_APP_INCOME  = 5 ;
end;
when ( 4626 < APP_INCOME ) do;
GRP_APP_INCOME  = 6 ;
end;
when ( missing(APP_INCOME) ) do;
GRP_APP_INCOME  = 7 ;
end;
otherwise GRP_APP_INCOME  = 8 ; end;
select;
when ( not missing(APP_INSTALLMENT) and APP_INSTALLMENT <= 108 ) do;
GRP_APP_INSTALLMENT  = 1 ;
end;
when ( 108 < APP_INSTALLMENT <= 192 ) do;
GRP_APP_INSTALLMENT  = 2 ;
end;
when ( 192 < APP_INSTALLMENT <= 230 ) do;
GRP_APP_INSTALLMENT  = 3 ;
end;
when ( 230 < APP_INSTALLMENT <= 271 ) do;
GRP_APP_INSTALLMENT  = 4 ;
end;
when ( 271 < APP_INSTALLMENT <= 507 ) do;
GRP_APP_INSTALLMENT  = 5 ;
end;
when ( 507 < APP_INSTALLMENT ) do;
GRP_APP_INSTALLMENT  = 6 ;
end;
when ( missing(APP_INSTALLMENT) ) do;
GRP_APP_INSTALLMENT  = 7 ;
end;
otherwise GRP_APP_INSTALLMENT  = 8 ; end;
select;
when ( not missing(APP_LOAN_AMOUNT) and APP_LOAN_AMOUNT <= 1884 ) do;
GRP_APP_LOAN_AMOUNT  = 1 ;
end;
when ( 1884 < APP_LOAN_AMOUNT <= 4836 ) do;
GRP_APP_LOAN_AMOUNT  = 2 ;
end;
when ( 4836 < APP_LOAN_AMOUNT <= 5520 ) do;
GRP_APP_LOAN_AMOUNT  = 3 ;
end;
when ( 5520 < APP_LOAN_AMOUNT <= 6696 ) do;
GRP_APP_LOAN_AMOUNT  = 4 ;
end;
when ( 6696 < APP_LOAN_AMOUNT <= 10872 ) do;
GRP_APP_LOAN_AMOUNT  = 5 ;
end;
when ( 10872 < APP_LOAN_AMOUNT ) do;
GRP_APP_LOAN_AMOUNT  = 6 ;
end;
when ( missing(APP_LOAN_AMOUNT) ) do;
GRP_APP_LOAN_AMOUNT  = 7 ;
end;
otherwise GRP_APP_LOAN_AMOUNT  = 8 ; end;
select;
when ( not missing(APP_NUMBER_OF_CHILDREN) and APP_NUMBER_OF_CHILDREN <= 0 ) do;
GRP_APP_NUMBER_OF_CHILDREN  = 1 ;
end;
when ( 0 < APP_NUMBER_OF_CHILDREN <= 1 ) do;
GRP_APP_NUMBER_OF_CHILDREN  = 2 ;
end;
when ( 1 < APP_NUMBER_OF_CHILDREN ) do;
GRP_APP_NUMBER_OF_CHILDREN  = 3 ;
end;
when ( missing(APP_NUMBER_OF_CHILDREN) ) do;
GRP_APP_NUMBER_OF_CHILDREN  = 4 ;
end;
otherwise GRP_APP_NUMBER_OF_CHILDREN  = 5 ; end;
select;
when ( not missing(APP_N_INSTALLMENTS) and APP_N_INSTALLMENTS <= 12 ) do;
GRP_APP_N_INSTALLMENTS  = 1 ;
end;
when ( 12 < APP_N_INSTALLMENTS <= 24 ) do;
GRP_APP_N_INSTALLMENTS  = 2 ;
end;
when ( 24 < APP_N_INSTALLMENTS ) do;
GRP_APP_N_INSTALLMENTS  = 3 ;
end;
when ( missing(APP_N_INSTALLMENTS) ) do;
GRP_APP_N_INSTALLMENTS  = 4 ;
end;
otherwise GRP_APP_N_INSTALLMENTS  = 5 ; end;
select;
when ( not missing(APP_SPENDINGS) and APP_SPENDINGS <= 180 ) do;
GRP_APP_SPENDINGS  = 1 ;
end;
when ( 180 < APP_SPENDINGS <= 240 ) do;
GRP_APP_SPENDINGS  = 2 ;
end;
when ( 240 < APP_SPENDINGS <= 460 ) do;
GRP_APP_SPENDINGS  = 3 ;
end;
when ( 460 < APP_SPENDINGS <= 1260 ) do;
GRP_APP_SPENDINGS  = 4 ;
end;
when ( 1260 < APP_SPENDINGS <= 2340 ) do;
GRP_APP_SPENDINGS  = 5 ;
end;
when ( 2340 < APP_SPENDINGS ) do;
GRP_APP_SPENDINGS  = 6 ;
end;
when ( missing(APP_SPENDINGS) ) do;
GRP_APP_SPENDINGS  = 7 ;
end;
otherwise GRP_APP_SPENDINGS  = 8 ; end;
run;
