data grp;
set abt.train;
select;
when ( not missing(ACT12_N_ARREARS) ) do;
GRP_ACT12_N_ARREARS  = 1 ;
end;
when ( missing(ACT12_N_ARREARS) ) do;
GRP_ACT12_N_ARREARS  = 2 ;
end;
otherwise GRP_ACT12_N_ARREARS  = 3 ; end;
select;
when ( not missing(ACT12_N_ARREARS_DAYS) ) do;
GRP_ACT12_N_ARREARS_DAYS  = 1 ;
end;
when ( missing(ACT12_N_ARREARS_DAYS) ) do;
GRP_ACT12_N_ARREARS_DAYS  = 2 ;
end;
otherwise GRP_ACT12_N_ARREARS_DAYS  = 3 ; end;
select;
when ( not missing(ACT12_N_GOOD_DAYS) ) do;
GRP_ACT12_N_GOOD_DAYS  = 1 ;
end;
when ( missing(ACT12_N_GOOD_DAYS) ) do;
GRP_ACT12_N_GOOD_DAYS  = 2 ;
end;
otherwise GRP_ACT12_N_GOOD_DAYS  = 3 ; end;
select;
when ( not missing(ACT3_N_ARREARS) ) do;
GRP_ACT3_N_ARREARS  = 1 ;
end;
when ( missing(ACT3_N_ARREARS) ) do;
GRP_ACT3_N_ARREARS  = 2 ;
end;
otherwise GRP_ACT3_N_ARREARS  = 3 ; end;
select;
when ( not missing(ACT3_N_ARREARS_DAYS) ) do;
GRP_ACT3_N_ARREARS_DAYS  = 1 ;
end;
when ( missing(ACT3_N_ARREARS_DAYS) ) do;
GRP_ACT3_N_ARREARS_DAYS  = 2 ;
end;
otherwise GRP_ACT3_N_ARREARS_DAYS  = 3 ; end;
select;
when ( not missing(ACT3_N_GOOD_DAYS) ) do;
GRP_ACT3_N_GOOD_DAYS  = 1 ;
end;
when ( missing(ACT3_N_GOOD_DAYS) ) do;
GRP_ACT3_N_GOOD_DAYS  = 2 ;
end;
otherwise GRP_ACT3_N_GOOD_DAYS  = 3 ; end;
select;
when ( not missing(ACT6_N_ARREARS) ) do;
GRP_ACT6_N_ARREARS  = 1 ;
end;
when ( missing(ACT6_N_ARREARS) ) do;
GRP_ACT6_N_ARREARS  = 2 ;
end;
otherwise GRP_ACT6_N_ARREARS  = 3 ; end;
select;
when ( not missing(ACT6_N_ARREARS_DAYS) ) do;
GRP_ACT6_N_ARREARS_DAYS  = 1 ;
end;
when ( missing(ACT6_N_ARREARS_DAYS) ) do;
GRP_ACT6_N_ARREARS_DAYS  = 2 ;
end;
otherwise GRP_ACT6_N_ARREARS_DAYS  = 3 ; end;
select;
when ( not missing(ACT6_N_GOOD_DAYS) ) do;
GRP_ACT6_N_GOOD_DAYS  = 1 ;
end;
when ( missing(ACT6_N_GOOD_DAYS) ) do;
GRP_ACT6_N_GOOD_DAYS  = 2 ;
end;
otherwise GRP_ACT6_N_GOOD_DAYS  = 3 ; end;
select;
when ( not missing(ACT9_N_ARREARS) ) do;
GRP_ACT9_N_ARREARS  = 1 ;
end;
when ( missing(ACT9_N_ARREARS) ) do;
GRP_ACT9_N_ARREARS  = 2 ;
end;
otherwise GRP_ACT9_N_ARREARS  = 3 ; end;
select;
when ( not missing(ACT9_N_ARREARS_DAYS) ) do;
GRP_ACT9_N_ARREARS_DAYS  = 1 ;
end;
when ( missing(ACT9_N_ARREARS_DAYS) ) do;
GRP_ACT9_N_ARREARS_DAYS  = 2 ;
end;
otherwise GRP_ACT9_N_ARREARS_DAYS  = 3 ; end;
select;
when ( not missing(ACT9_N_GOOD_DAYS) ) do;
GRP_ACT9_N_GOOD_DAYS  = 1 ;
end;
when ( missing(ACT9_N_GOOD_DAYS) ) do;
GRP_ACT9_N_GOOD_DAYS  = 2 ;
end;
otherwise GRP_ACT9_N_GOOD_DAYS  = 3 ; end;
select;
when ( not missing(ACT_AGE) and ACT_AGE <= 40 ) do;
GRP_ACT_AGE  = 1 ;
end;
when ( 40 < ACT_AGE <= 57 ) do;
GRP_ACT_AGE  = 2 ;
end;
when ( 57 < ACT_AGE <= 61 ) do;
GRP_ACT_AGE  = 3 ;
end;
when ( 61 < ACT_AGE <= 68 ) do;
GRP_ACT_AGE  = 4 ;
end;
when ( 68 < ACT_AGE <= 78 ) do;
GRP_ACT_AGE  = 5 ;
end;
when ( 78 < ACT_AGE ) do;
GRP_ACT_AGE  = 6 ;
end;
when ( missing(ACT_AGE) ) do;
GRP_ACT_AGE  = 7 ;
end;
otherwise GRP_ACT_AGE  = 8 ; end;
select;
when ( not missing(ACT_CALL_CC) and ACT_CALL_CC <= 0.1952595937 ) do;
GRP_ACT_CALL_CC  = 1 ;
end;
when ( 0.1952595937 < ACT_CALL_CC <= 0.2820395039 ) do;
GRP_ACT_CALL_CC  = 2 ;
end;
when ( 0.2820395039 < ACT_CALL_CC <= 0.3156015709 ) do;
GRP_ACT_CALL_CC  = 3 ;
end;
when ( 0.3156015709 < ACT_CALL_CC <= 0.3600303183 ) do;
GRP_ACT_CALL_CC  = 4 ;
end;
when ( 0.3600303183 < ACT_CALL_CC ) do;
GRP_ACT_CALL_CC  = 5 ;
end;
when ( missing(ACT_CALL_CC) ) do;
GRP_ACT_CALL_CC  = 6 ;
end;
otherwise GRP_ACT_CALL_CC  = 7 ; end;
select;
when ( not missing(ACT_CALL_N_LOAN) ) do;
GRP_ACT_CALL_N_LOAN  = 1 ;
end;
when ( missing(ACT_CALL_N_LOAN) ) do;
GRP_ACT_CALL_N_LOAN  = 2 ;
end;
otherwise GRP_ACT_CALL_N_LOAN  = 3 ; end;
select;
when ( not missing(ACT_CC) and ACT_CC <= 0.1952595937 ) do;
GRP_ACT_CC  = 1 ;
end;
when ( 0.1952595937 < ACT_CC <= 0.5457148701 ) do;
GRP_ACT_CC  = 2 ;
end;
when ( 0.5457148701 < ACT_CC <= 0.8087431694 ) do;
GRP_ACT_CC  = 3 ;
end;
when ( 0.8087431694 < ACT_CC <= 0.867881549 ) do;
GRP_ACT_CC  = 4 ;
end;
when ( 0.867881549 < ACT_CC ) do;
GRP_ACT_CC  = 5 ;
end;
when ( missing(ACT_CC) ) do;
GRP_ACT_CC  = 6 ;
end;
otherwise GRP_ACT_CC  = 7 ; end;
select;
when ( not missing(ACT_CCSS_CC) ) do;
GRP_ACT_CCSS_CC  = 1 ;
end;
when ( missing(ACT_CCSS_CC) ) do;
GRP_ACT_CCSS_CC  = 2 ;
end;
otherwise GRP_ACT_CCSS_CC  = 3 ; end;
select;
when ( not missing(ACT_CCSS_DUEUTL) ) do;
GRP_ACT_CCSS_DUEUTL  = 1 ;
end;
when ( missing(ACT_CCSS_DUEUTL) ) do;
GRP_ACT_CCSS_DUEUTL  = 2 ;
end;
otherwise GRP_ACT_CCSS_DUEUTL  = 3 ; end;
select;
when ( not missing(ACT_CCSS_MAXDUE) ) do;
GRP_ACT_CCSS_MAXDUE  = 1 ;
end;
when ( missing(ACT_CCSS_MAXDUE) ) do;
GRP_ACT_CCSS_MAXDUE  = 2 ;
end;
otherwise GRP_ACT_CCSS_MAXDUE  = 3 ; end;
select;
when ( not missing(ACT_CCSS_MIN_LNINST) ) do;
GRP_ACT_CCSS_MIN_LNINST  = 1 ;
end;
when ( missing(ACT_CCSS_MIN_LNINST) ) do;
GRP_ACT_CCSS_MIN_LNINST  = 2 ;
end;
otherwise GRP_ACT_CCSS_MIN_LNINST  = 3 ; end;
select;
when ( not missing(ACT_CCSS_MIN_PNINST) ) do;
GRP_ACT_CCSS_MIN_PNINST  = 1 ;
end;
when ( missing(ACT_CCSS_MIN_PNINST) ) do;
GRP_ACT_CCSS_MIN_PNINST  = 2 ;
end;
otherwise GRP_ACT_CCSS_MIN_PNINST  = 3 ; end;
select;
when ( not missing(ACT_CCSS_MIN_SENIORITY) and ACT_CCSS_MIN_SENIORITY <= 49 ) do;
GRP_ACT_CCSS_MIN_SENIORITY  = 1 ;
end;
when ( 49 < ACT_CCSS_MIN_SENIORITY <= 104 ) do;
GRP_ACT_CCSS_MIN_SENIORITY  = 2 ;
end;
when ( 104 < ACT_CCSS_MIN_SENIORITY ) do;
GRP_ACT_CCSS_MIN_SENIORITY  = 3 ;
end;
when ( missing(ACT_CCSS_MIN_SENIORITY) ) do;
GRP_ACT_CCSS_MIN_SENIORITY  = 4 ;
end;
otherwise GRP_ACT_CCSS_MIN_SENIORITY  = 5 ; end;
select;
when ( not missing(ACT_CCSS_N_LOAN) ) do;
GRP_ACT_CCSS_N_LOAN  = 1 ;
end;
when ( missing(ACT_CCSS_N_LOAN) ) do;
GRP_ACT_CCSS_N_LOAN  = 2 ;
end;
otherwise GRP_ACT_CCSS_N_LOAN  = 3 ; end;
select;
when ( not missing(ACT_CCSS_N_LOANS_ACT) ) do;
GRP_ACT_CCSS_N_LOANS_ACT  = 1 ;
end;
when ( missing(ACT_CCSS_N_LOANS_ACT) ) do;
GRP_ACT_CCSS_N_LOANS_ACT  = 2 ;
end;
otherwise GRP_ACT_CCSS_N_LOANS_ACT  = 3 ; end;
select;
when ( not missing(ACT_CCSS_N_LOANS_HIST) and ACT_CCSS_N_LOANS_HIST <= 3 ) do;
GRP_ACT_CCSS_N_LOANS_HIST  = 1 ;
end;
when ( 3 < ACT_CCSS_N_LOANS_HIST ) do;
GRP_ACT_CCSS_N_LOANS_HIST  = 2 ;
end;
when ( missing(ACT_CCSS_N_LOANS_HIST) ) do;
GRP_ACT_CCSS_N_LOANS_HIST  = 3 ;
end;
otherwise GRP_ACT_CCSS_N_LOANS_HIST  = 4 ; end;
select;
when ( not missing(ACT_CCSS_N_STATB) and ACT_CCSS_N_STATB <= 3 ) do;
GRP_ACT_CCSS_N_STATB  = 1 ;
end;
when ( 3 < ACT_CCSS_N_STATB ) do;
GRP_ACT_CCSS_N_STATB  = 2 ;
end;
when ( missing(ACT_CCSS_N_STATB) ) do;
GRP_ACT_CCSS_N_STATB  = 3 ;
end;
otherwise GRP_ACT_CCSS_N_STATB  = 4 ; end;
select;
when ( not missing(ACT_CCSS_N_STATC) and ACT_CCSS_N_STATC <= 0 ) do;
GRP_ACT_CCSS_N_STATC  = 1 ;
end;
when ( 0 < ACT_CCSS_N_STATC ) do;
GRP_ACT_CCSS_N_STATC  = 2 ;
end;
when ( missing(ACT_CCSS_N_STATC) ) do;
GRP_ACT_CCSS_N_STATC  = 3 ;
end;
otherwise GRP_ACT_CCSS_N_STATC  = 4 ; end;
select;
when ( not missing(ACT_CCSS_SENIORITY) and ACT_CCSS_SENIORITY <= 94 ) do;
GRP_ACT_CCSS_SENIORITY  = 1 ;
end;
when ( 94 < ACT_CCSS_SENIORITY <= 162 ) do;
GRP_ACT_CCSS_SENIORITY  = 2 ;
end;
when ( 162 < ACT_CCSS_SENIORITY ) do;
GRP_ACT_CCSS_SENIORITY  = 3 ;
end;
when ( missing(ACT_CCSS_SENIORITY) ) do;
GRP_ACT_CCSS_SENIORITY  = 4 ;
end;
otherwise GRP_ACT_CCSS_SENIORITY  = 5 ; end;
select;
when ( not missing(ACT_CCSS_UTL) ) do;
GRP_ACT_CCSS_UTL  = 1 ;
end;
when ( missing(ACT_CCSS_UTL) ) do;
GRP_ACT_CCSS_UTL  = 2 ;
end;
otherwise GRP_ACT_CCSS_UTL  = 3 ; end;
select;
when ( not missing(ACT_CINS_CC) ) do;
GRP_ACT_CINS_CC  = 1 ;
end;
when ( missing(ACT_CINS_CC) ) do;
GRP_ACT_CINS_CC  = 2 ;
end;
otherwise GRP_ACT_CINS_CC  = 3 ; end;
select;
when ( not missing(ACT_CINS_DUEUTL) ) do;
GRP_ACT_CINS_DUEUTL  = 1 ;
end;
when ( missing(ACT_CINS_DUEUTL) ) do;
GRP_ACT_CINS_DUEUTL  = 2 ;
end;
otherwise GRP_ACT_CINS_DUEUTL  = 3 ; end;
select;
when ( not missing(ACT_CINS_MAXDUE) ) do;
GRP_ACT_CINS_MAXDUE  = 1 ;
end;
when ( missing(ACT_CINS_MAXDUE) ) do;
GRP_ACT_CINS_MAXDUE  = 2 ;
end;
otherwise GRP_ACT_CINS_MAXDUE  = 3 ; end;
select;
when ( not missing(ACT_CINS_MIN_LNINST) ) do;
GRP_ACT_CINS_MIN_LNINST  = 1 ;
end;
when ( missing(ACT_CINS_MIN_LNINST) ) do;
GRP_ACT_CINS_MIN_LNINST  = 2 ;
end;
otherwise GRP_ACT_CINS_MIN_LNINST  = 3 ; end;
select;
when ( not missing(ACT_CINS_MIN_PNINST) ) do;
GRP_ACT_CINS_MIN_PNINST  = 1 ;
end;
when ( missing(ACT_CINS_MIN_PNINST) ) do;
GRP_ACT_CINS_MIN_PNINST  = 2 ;
end;
otherwise GRP_ACT_CINS_MIN_PNINST  = 3 ; end;
select;
when ( not missing(ACT_CINS_MIN_SENIORITY) and ACT_CINS_MIN_SENIORITY <= 48 ) do;
GRP_ACT_CINS_MIN_SENIORITY  = 1 ;
end;
when ( 48 < ACT_CINS_MIN_SENIORITY <= 82 ) do;
GRP_ACT_CINS_MIN_SENIORITY  = 2 ;
end;
when ( 82 < ACT_CINS_MIN_SENIORITY <= 216 ) do;
GRP_ACT_CINS_MIN_SENIORITY  = 3 ;
end;
when ( 216 < ACT_CINS_MIN_SENIORITY ) do;
GRP_ACT_CINS_MIN_SENIORITY  = 4 ;
end;
when ( missing(ACT_CINS_MIN_SENIORITY) ) do;
GRP_ACT_CINS_MIN_SENIORITY  = 5 ;
end;
otherwise GRP_ACT_CINS_MIN_SENIORITY  = 6 ; end;
select;
when ( not missing(ACT_CINS_N_LOAN) ) do;
GRP_ACT_CINS_N_LOAN  = 1 ;
end;
when ( missing(ACT_CINS_N_LOAN) ) do;
GRP_ACT_CINS_N_LOAN  = 2 ;
end;
otherwise GRP_ACT_CINS_N_LOAN  = 3 ; end;
select;
when ( not missing(ACT_CINS_N_LOANS_ACT) ) do;
GRP_ACT_CINS_N_LOANS_ACT  = 1 ;
end;
when ( missing(ACT_CINS_N_LOANS_ACT) ) do;
GRP_ACT_CINS_N_LOANS_ACT  = 2 ;
end;
otherwise GRP_ACT_CINS_N_LOANS_ACT  = 3 ; end;
select;
when ( not missing(ACT_CINS_N_LOANS_HIST) and ACT_CINS_N_LOANS_HIST <= 1 ) do;
GRP_ACT_CINS_N_LOANS_HIST  = 1 ;
end;
when ( 1 < ACT_CINS_N_LOANS_HIST <= 2 ) do;
GRP_ACT_CINS_N_LOANS_HIST  = 2 ;
end;
when ( 2 < ACT_CINS_N_LOANS_HIST <= 3 ) do;
GRP_ACT_CINS_N_LOANS_HIST  = 3 ;
end;
when ( 3 < ACT_CINS_N_LOANS_HIST ) do;
GRP_ACT_CINS_N_LOANS_HIST  = 4 ;
end;
when ( missing(ACT_CINS_N_LOANS_HIST) ) do;
GRP_ACT_CINS_N_LOANS_HIST  = 5 ;
end;
otherwise GRP_ACT_CINS_N_LOANS_HIST  = 6 ; end;
select;
when ( not missing(ACT_CINS_N_STATB) and ACT_CINS_N_STATB <= 0 ) do;
GRP_ACT_CINS_N_STATB  = 1 ;
end;
when ( 0 < ACT_CINS_N_STATB ) do;
GRP_ACT_CINS_N_STATB  = 2 ;
end;
when ( missing(ACT_CINS_N_STATB) ) do;
GRP_ACT_CINS_N_STATB  = 3 ;
end;
otherwise GRP_ACT_CINS_N_STATB  = 4 ; end;
select;
when ( not missing(ACT_CINS_N_STATC) and ACT_CINS_N_STATC <= 1 ) do;
GRP_ACT_CINS_N_STATC  = 1 ;
end;
when ( 1 < ACT_CINS_N_STATC <= 2 ) do;
GRP_ACT_CINS_N_STATC  = 2 ;
end;
when ( 2 < ACT_CINS_N_STATC <= 3 ) do;
GRP_ACT_CINS_N_STATC  = 3 ;
end;
when ( 3 < ACT_CINS_N_STATC ) do;
GRP_ACT_CINS_N_STATC  = 4 ;
end;
when ( missing(ACT_CINS_N_STATC) ) do;
GRP_ACT_CINS_N_STATC  = 5 ;
end;
otherwise GRP_ACT_CINS_N_STATC  = 6 ; end;
select;
when ( not missing(ACT_CINS_SENIORITY) and ACT_CINS_SENIORITY <= 96 ) do;
GRP_ACT_CINS_SENIORITY  = 1 ;
end;
when ( 96 < ACT_CINS_SENIORITY <= 132 ) do;
GRP_ACT_CINS_SENIORITY  = 2 ;
end;
when ( 132 < ACT_CINS_SENIORITY <= 167 ) do;
GRP_ACT_CINS_SENIORITY  = 3 ;
end;
when ( 167 < ACT_CINS_SENIORITY <= 227 ) do;
GRP_ACT_CINS_SENIORITY  = 4 ;
end;
when ( 227 < ACT_CINS_SENIORITY ) do;
GRP_ACT_CINS_SENIORITY  = 5 ;
end;
when ( missing(ACT_CINS_SENIORITY) ) do;
GRP_ACT_CINS_SENIORITY  = 6 ;
end;
otherwise GRP_ACT_CINS_SENIORITY  = 7 ; end;
select;
when ( not missing(ACT_CINS_UTL) ) do;
GRP_ACT_CINS_UTL  = 1 ;
end;
when ( missing(ACT_CINS_UTL) ) do;
GRP_ACT_CINS_UTL  = 2 ;
end;
otherwise GRP_ACT_CINS_UTL  = 3 ; end;
select;
when ( not missing(ACT_CUS_ACTIVE) ) do;
GRP_ACT_CUS_ACTIVE  = 1 ;
end;
when ( missing(ACT_CUS_ACTIVE) ) do;
GRP_ACT_CUS_ACTIVE  = 2 ;
end;
otherwise GRP_ACT_CUS_ACTIVE  = 3 ; end;
select;
when ( not missing(ACT_LOANINC) and ACT_LOANINC <= 0.4158844765 ) do;
GRP_ACT_LOANINC  = 1 ;
end;
when ( 0.4158844765 < ACT_LOANINC <= 3.1447587354 ) do;
GRP_ACT_LOANINC  = 2 ;
end;
when ( 3.1447587354 < ACT_LOANINC <= 3.6532769556 ) do;
GRP_ACT_LOANINC  = 3 ;
end;
when ( 3.6532769556 < ACT_LOANINC <= 5.7148288973 ) do;
GRP_ACT_LOANINC  = 4 ;
end;
when ( 5.7148288973 < ACT_LOANINC ) do;
GRP_ACT_LOANINC  = 5 ;
end;
when ( missing(ACT_LOANINC) ) do;
GRP_ACT_LOANINC  = 6 ;
end;
otherwise GRP_ACT_LOANINC  = 7 ; end;
select;
when ( not missing(AGR12_MAX_CMAXA_DAYS) ) do;
GRP_AGR12_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR12_MAX_CMAXA_DAYS) ) do;
GRP_AGR12_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MAX_CMAXA_DUE) ) do;
GRP_AGR12_MAX_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR12_MAX_CMAXA_DUE) ) do;
GRP_AGR12_MAX_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR12_MAX_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MAX_CMAXC_DAYS) ) do;
GRP_AGR12_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR12_MAX_CMAXC_DAYS) ) do;
GRP_AGR12_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MAX_CMAXC_DUE) ) do;
GRP_AGR12_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR12_MAX_CMAXC_DUE) ) do;
GRP_AGR12_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR12_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MAX_CMAXI_DAYS) ) do;
GRP_AGR12_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR12_MAX_CMAXI_DAYS) ) do;
GRP_AGR12_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MAX_CMAXI_DUE) ) do;
GRP_AGR12_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR12_MAX_CMAXI_DUE) ) do;
GRP_AGR12_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR12_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXA_DAYS) ) do;
GRP_AGR12_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR12_MEAN_CMAXA_DAYS) ) do;
GRP_AGR12_MEAN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MEAN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXA_DUE) ) do;
GRP_AGR12_MEAN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR12_MEAN_CMAXA_DUE) ) do;
GRP_AGR12_MEAN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR12_MEAN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXC_DAYS) ) do;
GRP_AGR12_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR12_MEAN_CMAXC_DAYS) ) do;
GRP_AGR12_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXC_DUE) ) do;
GRP_AGR12_MEAN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR12_MEAN_CMAXC_DUE) ) do;
GRP_AGR12_MEAN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR12_MEAN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXI_DAYS) ) do;
GRP_AGR12_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR12_MEAN_CMAXI_DAYS) ) do;
GRP_AGR12_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXI_DUE) ) do;
GRP_AGR12_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR12_MEAN_CMAXI_DUE) ) do;
GRP_AGR12_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR12_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MIN_CMAXA_DAYS) ) do;
GRP_AGR12_MIN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR12_MIN_CMAXA_DAYS) ) do;
GRP_AGR12_MIN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MIN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MIN_CMAXA_DUE) ) do;
GRP_AGR12_MIN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR12_MIN_CMAXA_DUE) ) do;
GRP_AGR12_MIN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR12_MIN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MIN_CMAXC_DAYS) ) do;
GRP_AGR12_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR12_MIN_CMAXC_DAYS) ) do;
GRP_AGR12_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MIN_CMAXC_DUE) ) do;
GRP_AGR12_MIN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR12_MIN_CMAXC_DUE) ) do;
GRP_AGR12_MIN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR12_MIN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MIN_CMAXI_DAYS) ) do;
GRP_AGR12_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR12_MIN_CMAXI_DAYS) ) do;
GRP_AGR12_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MIN_CMAXI_DUE) ) do;
GRP_AGR12_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR12_MIN_CMAXI_DUE) ) do;
GRP_AGR12_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR12_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MAX_CMAXA_DAYS) ) do;
GRP_AGR3_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR3_MAX_CMAXA_DAYS) ) do;
GRP_AGR3_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MAX_CMAXA_DUE) ) do;
GRP_AGR3_MAX_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR3_MAX_CMAXA_DUE) ) do;
GRP_AGR3_MAX_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR3_MAX_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MAX_CMAXC_DAYS) ) do;
GRP_AGR3_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR3_MAX_CMAXC_DAYS) ) do;
GRP_AGR3_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MAX_CMAXC_DUE) ) do;
GRP_AGR3_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR3_MAX_CMAXC_DUE) ) do;
GRP_AGR3_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR3_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MAX_CMAXI_DAYS) ) do;
GRP_AGR3_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR3_MAX_CMAXI_DAYS) ) do;
GRP_AGR3_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MAX_CMAXI_DUE) ) do;
GRP_AGR3_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR3_MAX_CMAXI_DUE) ) do;
GRP_AGR3_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR3_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXA_DAYS) ) do;
GRP_AGR3_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR3_MEAN_CMAXA_DAYS) ) do;
GRP_AGR3_MEAN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MEAN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXA_DUE) ) do;
GRP_AGR3_MEAN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR3_MEAN_CMAXA_DUE) ) do;
GRP_AGR3_MEAN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR3_MEAN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXC_DAYS) ) do;
GRP_AGR3_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR3_MEAN_CMAXC_DAYS) ) do;
GRP_AGR3_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXC_DUE) ) do;
GRP_AGR3_MEAN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR3_MEAN_CMAXC_DUE) ) do;
GRP_AGR3_MEAN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR3_MEAN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXI_DAYS) ) do;
GRP_AGR3_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR3_MEAN_CMAXI_DAYS) ) do;
GRP_AGR3_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXI_DUE) ) do;
GRP_AGR3_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR3_MEAN_CMAXI_DUE) ) do;
GRP_AGR3_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR3_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MIN_CMAXA_DAYS) ) do;
GRP_AGR3_MIN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR3_MIN_CMAXA_DAYS) ) do;
GRP_AGR3_MIN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MIN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MIN_CMAXA_DUE) ) do;
GRP_AGR3_MIN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR3_MIN_CMAXA_DUE) ) do;
GRP_AGR3_MIN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR3_MIN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MIN_CMAXC_DAYS) ) do;
GRP_AGR3_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR3_MIN_CMAXC_DAYS) ) do;
GRP_AGR3_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MIN_CMAXC_DUE) ) do;
GRP_AGR3_MIN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR3_MIN_CMAXC_DUE) ) do;
GRP_AGR3_MIN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR3_MIN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MIN_CMAXI_DAYS) ) do;
GRP_AGR3_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR3_MIN_CMAXI_DAYS) ) do;
GRP_AGR3_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MIN_CMAXI_DUE) ) do;
GRP_AGR3_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR3_MIN_CMAXI_DUE) ) do;
GRP_AGR3_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR3_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MAX_CMAXA_DAYS) ) do;
GRP_AGR6_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR6_MAX_CMAXA_DAYS) ) do;
GRP_AGR6_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MAX_CMAXA_DUE) ) do;
GRP_AGR6_MAX_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR6_MAX_CMAXA_DUE) ) do;
GRP_AGR6_MAX_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR6_MAX_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MAX_CMAXC_DAYS) ) do;
GRP_AGR6_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR6_MAX_CMAXC_DAYS) ) do;
GRP_AGR6_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MAX_CMAXC_DUE) ) do;
GRP_AGR6_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR6_MAX_CMAXC_DUE) ) do;
GRP_AGR6_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR6_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MAX_CMAXI_DAYS) ) do;
GRP_AGR6_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR6_MAX_CMAXI_DAYS) ) do;
GRP_AGR6_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MAX_CMAXI_DUE) ) do;
GRP_AGR6_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR6_MAX_CMAXI_DUE) ) do;
GRP_AGR6_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR6_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXA_DAYS) ) do;
GRP_AGR6_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR6_MEAN_CMAXA_DAYS) ) do;
GRP_AGR6_MEAN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MEAN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXA_DUE) ) do;
GRP_AGR6_MEAN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR6_MEAN_CMAXA_DUE) ) do;
GRP_AGR6_MEAN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR6_MEAN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXC_DAYS) ) do;
GRP_AGR6_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR6_MEAN_CMAXC_DAYS) ) do;
GRP_AGR6_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXC_DUE) ) do;
GRP_AGR6_MEAN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR6_MEAN_CMAXC_DUE) ) do;
GRP_AGR6_MEAN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR6_MEAN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXI_DAYS) ) do;
GRP_AGR6_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR6_MEAN_CMAXI_DAYS) ) do;
GRP_AGR6_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXI_DUE) ) do;
GRP_AGR6_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR6_MEAN_CMAXI_DUE) ) do;
GRP_AGR6_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR6_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MIN_CMAXA_DAYS) ) do;
GRP_AGR6_MIN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR6_MIN_CMAXA_DAYS) ) do;
GRP_AGR6_MIN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MIN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MIN_CMAXA_DUE) ) do;
GRP_AGR6_MIN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR6_MIN_CMAXA_DUE) ) do;
GRP_AGR6_MIN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR6_MIN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MIN_CMAXC_DAYS) ) do;
GRP_AGR6_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR6_MIN_CMAXC_DAYS) ) do;
GRP_AGR6_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MIN_CMAXC_DUE) ) do;
GRP_AGR6_MIN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR6_MIN_CMAXC_DUE) ) do;
GRP_AGR6_MIN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR6_MIN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MIN_CMAXI_DAYS) ) do;
GRP_AGR6_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR6_MIN_CMAXI_DAYS) ) do;
GRP_AGR6_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MIN_CMAXI_DUE) ) do;
GRP_AGR6_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR6_MIN_CMAXI_DUE) ) do;
GRP_AGR6_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR6_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MAX_CMAXA_DAYS) ) do;
GRP_AGR9_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR9_MAX_CMAXA_DAYS) ) do;
GRP_AGR9_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MAX_CMAXA_DUE) ) do;
GRP_AGR9_MAX_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR9_MAX_CMAXA_DUE) ) do;
GRP_AGR9_MAX_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR9_MAX_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MAX_CMAXC_DAYS) ) do;
GRP_AGR9_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR9_MAX_CMAXC_DAYS) ) do;
GRP_AGR9_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MAX_CMAXC_DUE) ) do;
GRP_AGR9_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR9_MAX_CMAXC_DUE) ) do;
GRP_AGR9_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR9_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MAX_CMAXI_DAYS) ) do;
GRP_AGR9_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR9_MAX_CMAXI_DAYS) ) do;
GRP_AGR9_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MAX_CMAXI_DUE) ) do;
GRP_AGR9_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR9_MAX_CMAXI_DUE) ) do;
GRP_AGR9_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR9_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXA_DAYS) ) do;
GRP_AGR9_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR9_MEAN_CMAXA_DAYS) ) do;
GRP_AGR9_MEAN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MEAN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXA_DUE) ) do;
GRP_AGR9_MEAN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR9_MEAN_CMAXA_DUE) ) do;
GRP_AGR9_MEAN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR9_MEAN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXC_DAYS) ) do;
GRP_AGR9_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR9_MEAN_CMAXC_DAYS) ) do;
GRP_AGR9_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXC_DUE) ) do;
GRP_AGR9_MEAN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR9_MEAN_CMAXC_DUE) ) do;
GRP_AGR9_MEAN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR9_MEAN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXI_DAYS) ) do;
GRP_AGR9_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR9_MEAN_CMAXI_DAYS) ) do;
GRP_AGR9_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXI_DUE) ) do;
GRP_AGR9_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR9_MEAN_CMAXI_DUE) ) do;
GRP_AGR9_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR9_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MIN_CMAXA_DAYS) ) do;
GRP_AGR9_MIN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR9_MIN_CMAXA_DAYS) ) do;
GRP_AGR9_MIN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MIN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MIN_CMAXA_DUE) ) do;
GRP_AGR9_MIN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR9_MIN_CMAXA_DUE) ) do;
GRP_AGR9_MIN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR9_MIN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MIN_CMAXC_DAYS) ) do;
GRP_AGR9_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR9_MIN_CMAXC_DAYS) ) do;
GRP_AGR9_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MIN_CMAXC_DUE) ) do;
GRP_AGR9_MIN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR9_MIN_CMAXC_DUE) ) do;
GRP_AGR9_MIN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR9_MIN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MIN_CMAXI_DAYS) ) do;
GRP_AGR9_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR9_MIN_CMAXI_DAYS) ) do;
GRP_AGR9_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MIN_CMAXI_DUE) ) do;
GRP_AGR9_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR9_MIN_CMAXI_DUE) ) do;
GRP_AGR9_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR9_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS12_MAX_CMAXA_DAYS) ) do;
GRP_AGS12_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS12_MAX_CMAXA_DAYS) ) do;
GRP_AGS12_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MAX_CMAXA_DUE) ) do;
GRP_AGS12_MAX_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS12_MAX_CMAXA_DUE) ) do;
GRP_AGS12_MAX_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS12_MAX_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS12_MAX_CMAXC_DAYS) ) do;
GRP_AGS12_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS12_MAX_CMAXC_DAYS) ) do;
GRP_AGS12_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MAX_CMAXC_DUE) ) do;
GRP_AGS12_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS12_MAX_CMAXC_DUE) ) do;
GRP_AGS12_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS12_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS12_MAX_CMAXI_DAYS) ) do;
GRP_AGS12_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS12_MAX_CMAXI_DAYS) ) do;
GRP_AGS12_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MAX_CMAXI_DUE) ) do;
GRP_AGS12_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS12_MAX_CMAXI_DUE) ) do;
GRP_AGS12_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS12_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXA_DAYS) ) do;
GRP_AGS12_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS12_MEAN_CMAXA_DAYS) ) do;
GRP_AGS12_MEAN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MEAN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXA_DUE) ) do;
GRP_AGS12_MEAN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS12_MEAN_CMAXA_DUE) ) do;
GRP_AGS12_MEAN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS12_MEAN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXC_DAYS) ) do;
GRP_AGS12_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS12_MEAN_CMAXC_DAYS) ) do;
GRP_AGS12_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXC_DUE) ) do;
GRP_AGS12_MEAN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS12_MEAN_CMAXC_DUE) ) do;
GRP_AGS12_MEAN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS12_MEAN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXI_DAYS) ) do;
GRP_AGS12_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS12_MEAN_CMAXI_DAYS) ) do;
GRP_AGS12_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXI_DUE) ) do;
GRP_AGS12_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS12_MEAN_CMAXI_DUE) ) do;
GRP_AGS12_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS12_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS12_MIN_CMAXA_DAYS) ) do;
GRP_AGS12_MIN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS12_MIN_CMAXA_DAYS) ) do;
GRP_AGS12_MIN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MIN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MIN_CMAXA_DUE) ) do;
GRP_AGS12_MIN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS12_MIN_CMAXA_DUE) ) do;
GRP_AGS12_MIN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS12_MIN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS12_MIN_CMAXC_DAYS) ) do;
GRP_AGS12_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS12_MIN_CMAXC_DAYS) ) do;
GRP_AGS12_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MIN_CMAXC_DUE) ) do;
GRP_AGS12_MIN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS12_MIN_CMAXC_DUE) ) do;
GRP_AGS12_MIN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS12_MIN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS12_MIN_CMAXI_DAYS) ) do;
GRP_AGS12_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS12_MIN_CMAXI_DAYS) ) do;
GRP_AGS12_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MIN_CMAXI_DUE) ) do;
GRP_AGS12_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS12_MIN_CMAXI_DUE) ) do;
GRP_AGS12_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS12_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MAX_CMAXA_DAYS) ) do;
GRP_AGS3_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS3_MAX_CMAXA_DAYS) ) do;
GRP_AGS3_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MAX_CMAXA_DUE) ) do;
GRP_AGS3_MAX_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS3_MAX_CMAXA_DUE) ) do;
GRP_AGS3_MAX_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS3_MAX_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MAX_CMAXC_DAYS) ) do;
GRP_AGS3_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS3_MAX_CMAXC_DAYS) ) do;
GRP_AGS3_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MAX_CMAXC_DUE) ) do;
GRP_AGS3_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS3_MAX_CMAXC_DUE) ) do;
GRP_AGS3_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS3_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MAX_CMAXI_DAYS) ) do;
GRP_AGS3_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS3_MAX_CMAXI_DAYS) ) do;
GRP_AGS3_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MAX_CMAXI_DUE) ) do;
GRP_AGS3_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS3_MAX_CMAXI_DUE) ) do;
GRP_AGS3_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS3_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXA_DAYS) ) do;
GRP_AGS3_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS3_MEAN_CMAXA_DAYS) ) do;
GRP_AGS3_MEAN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MEAN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXA_DUE) ) do;
GRP_AGS3_MEAN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS3_MEAN_CMAXA_DUE) ) do;
GRP_AGS3_MEAN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS3_MEAN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXC_DAYS) ) do;
GRP_AGS3_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS3_MEAN_CMAXC_DAYS) ) do;
GRP_AGS3_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXC_DUE) ) do;
GRP_AGS3_MEAN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS3_MEAN_CMAXC_DUE) ) do;
GRP_AGS3_MEAN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS3_MEAN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXI_DAYS) ) do;
GRP_AGS3_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS3_MEAN_CMAXI_DAYS) ) do;
GRP_AGS3_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXI_DUE) ) do;
GRP_AGS3_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS3_MEAN_CMAXI_DUE) ) do;
GRP_AGS3_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS3_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MIN_CMAXA_DAYS) ) do;
GRP_AGS3_MIN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS3_MIN_CMAXA_DAYS) ) do;
GRP_AGS3_MIN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MIN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MIN_CMAXA_DUE) ) do;
GRP_AGS3_MIN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS3_MIN_CMAXA_DUE) ) do;
GRP_AGS3_MIN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS3_MIN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MIN_CMAXC_DAYS) ) do;
GRP_AGS3_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS3_MIN_CMAXC_DAYS) ) do;
GRP_AGS3_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MIN_CMAXC_DUE) ) do;
GRP_AGS3_MIN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS3_MIN_CMAXC_DUE) ) do;
GRP_AGS3_MIN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS3_MIN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MIN_CMAXI_DAYS) ) do;
GRP_AGS3_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS3_MIN_CMAXI_DAYS) ) do;
GRP_AGS3_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MIN_CMAXI_DUE) ) do;
GRP_AGS3_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS3_MIN_CMAXI_DUE) ) do;
GRP_AGS3_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS3_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MAX_CMAXA_DAYS) ) do;
GRP_AGS6_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS6_MAX_CMAXA_DAYS) ) do;
GRP_AGS6_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MAX_CMAXA_DUE) ) do;
GRP_AGS6_MAX_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS6_MAX_CMAXA_DUE) ) do;
GRP_AGS6_MAX_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS6_MAX_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MAX_CMAXC_DAYS) ) do;
GRP_AGS6_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS6_MAX_CMAXC_DAYS) ) do;
GRP_AGS6_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MAX_CMAXC_DUE) ) do;
GRP_AGS6_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS6_MAX_CMAXC_DUE) ) do;
GRP_AGS6_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS6_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MAX_CMAXI_DAYS) ) do;
GRP_AGS6_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS6_MAX_CMAXI_DAYS) ) do;
GRP_AGS6_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MAX_CMAXI_DUE) ) do;
GRP_AGS6_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS6_MAX_CMAXI_DUE) ) do;
GRP_AGS6_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS6_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXA_DAYS) ) do;
GRP_AGS6_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS6_MEAN_CMAXA_DAYS) ) do;
GRP_AGS6_MEAN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MEAN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXA_DUE) ) do;
GRP_AGS6_MEAN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS6_MEAN_CMAXA_DUE) ) do;
GRP_AGS6_MEAN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS6_MEAN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXC_DAYS) ) do;
GRP_AGS6_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS6_MEAN_CMAXC_DAYS) ) do;
GRP_AGS6_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXC_DUE) ) do;
GRP_AGS6_MEAN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS6_MEAN_CMAXC_DUE) ) do;
GRP_AGS6_MEAN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS6_MEAN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXI_DAYS) ) do;
GRP_AGS6_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS6_MEAN_CMAXI_DAYS) ) do;
GRP_AGS6_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXI_DUE) ) do;
GRP_AGS6_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS6_MEAN_CMAXI_DUE) ) do;
GRP_AGS6_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS6_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MIN_CMAXA_DAYS) ) do;
GRP_AGS6_MIN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS6_MIN_CMAXA_DAYS) ) do;
GRP_AGS6_MIN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MIN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MIN_CMAXA_DUE) ) do;
GRP_AGS6_MIN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS6_MIN_CMAXA_DUE) ) do;
GRP_AGS6_MIN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS6_MIN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MIN_CMAXC_DAYS) ) do;
GRP_AGS6_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS6_MIN_CMAXC_DAYS) ) do;
GRP_AGS6_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MIN_CMAXC_DUE) ) do;
GRP_AGS6_MIN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS6_MIN_CMAXC_DUE) ) do;
GRP_AGS6_MIN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS6_MIN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MIN_CMAXI_DAYS) ) do;
GRP_AGS6_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS6_MIN_CMAXI_DAYS) ) do;
GRP_AGS6_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MIN_CMAXI_DUE) ) do;
GRP_AGS6_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS6_MIN_CMAXI_DUE) ) do;
GRP_AGS6_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS6_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MAX_CMAXA_DAYS) ) do;
GRP_AGS9_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS9_MAX_CMAXA_DAYS) ) do;
GRP_AGS9_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MAX_CMAXA_DUE) ) do;
GRP_AGS9_MAX_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS9_MAX_CMAXA_DUE) ) do;
GRP_AGS9_MAX_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS9_MAX_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MAX_CMAXC_DAYS) ) do;
GRP_AGS9_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS9_MAX_CMAXC_DAYS) ) do;
GRP_AGS9_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MAX_CMAXC_DUE) ) do;
GRP_AGS9_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS9_MAX_CMAXC_DUE) ) do;
GRP_AGS9_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS9_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MAX_CMAXI_DAYS) ) do;
GRP_AGS9_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS9_MAX_CMAXI_DAYS) ) do;
GRP_AGS9_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MAX_CMAXI_DUE) ) do;
GRP_AGS9_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS9_MAX_CMAXI_DUE) ) do;
GRP_AGS9_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS9_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXA_DAYS) ) do;
GRP_AGS9_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS9_MEAN_CMAXA_DAYS) ) do;
GRP_AGS9_MEAN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MEAN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXA_DUE) ) do;
GRP_AGS9_MEAN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS9_MEAN_CMAXA_DUE) ) do;
GRP_AGS9_MEAN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS9_MEAN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXC_DAYS) ) do;
GRP_AGS9_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS9_MEAN_CMAXC_DAYS) ) do;
GRP_AGS9_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXC_DUE) ) do;
GRP_AGS9_MEAN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS9_MEAN_CMAXC_DUE) ) do;
GRP_AGS9_MEAN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS9_MEAN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXI_DAYS) ) do;
GRP_AGS9_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS9_MEAN_CMAXI_DAYS) ) do;
GRP_AGS9_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXI_DUE) ) do;
GRP_AGS9_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS9_MEAN_CMAXI_DUE) ) do;
GRP_AGS9_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS9_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MIN_CMAXA_DAYS) ) do;
GRP_AGS9_MIN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS9_MIN_CMAXA_DAYS) ) do;
GRP_AGS9_MIN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MIN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MIN_CMAXA_DUE) ) do;
GRP_AGS9_MIN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGS9_MIN_CMAXA_DUE) ) do;
GRP_AGS9_MIN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGS9_MIN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MIN_CMAXC_DAYS) ) do;
GRP_AGS9_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS9_MIN_CMAXC_DAYS) ) do;
GRP_AGS9_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MIN_CMAXC_DUE) ) do;
GRP_AGS9_MIN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS9_MIN_CMAXC_DUE) ) do;
GRP_AGS9_MIN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS9_MIN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MIN_CMAXI_DAYS) ) do;
GRP_AGS9_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS9_MIN_CMAXI_DAYS) ) do;
GRP_AGS9_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MIN_CMAXI_DUE) ) do;
GRP_AGS9_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS9_MIN_CMAXI_DUE) ) do;
GRP_AGS9_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS9_MIN_CMAXI_DUE  = 3 ; end;
select (APP_CHAR_BRANCH );
  when ('Computers')   do;
GRP_APP_CHAR_BRANCH  = 1 ;
end;
  when ('Radio-TV')   do;
GRP_APP_CHAR_BRANCH  = 2 ;
end;
  when ('Fenitures')   do;
GRP_APP_CHAR_BRANCH  = 3 ;
end;
  when ('DiY')   do;
GRP_APP_CHAR_BRANCH  = 4 ;
end;
otherwise GRP_APP_CHAR_BRANCH  = 5 ; end;
select (APP_CHAR_CARS );
  when ('No')   do;
GRP_APP_CHAR_CARS  = 1 ;
end;
  when ('Owner')   do;
GRP_APP_CHAR_CARS  = 2 ;
end;
otherwise GRP_APP_CHAR_CARS  = 3 ; end;
select (APP_CHAR_CITY );
  when ('Large')   do;
GRP_APP_CHAR_CITY  = 1 ;
end;
  when ('Small')   do;
GRP_APP_CHAR_CITY  = 2 ;
end;
  when ('Medium')   do;
GRP_APP_CHAR_CITY  = 3 ;
end;
  when ('Big')   do;
GRP_APP_CHAR_CITY  = 4 ;
end;
otherwise GRP_APP_CHAR_CITY  = 5 ; end;
select (APP_CHAR_GENDER );
  when ('Female')   do;
GRP_APP_CHAR_GENDER  = 1 ;
end;
  when ('Male')   do;
GRP_APP_CHAR_GENDER  = 2 ;
end;
otherwise GRP_APP_CHAR_GENDER  = 3 ; end;
select (APP_CHAR_HOME_STATUS );
  when ('Owner')   do;
GRP_APP_CHAR_HOME_STATUS  = 1 ;
end;
  when ('Rental')   do;
GRP_APP_CHAR_HOME_STATUS  = 2 ;
end;
otherwise GRP_APP_CHAR_HOME_STATUS  = 3 ; end;
select (APP_CHAR_JOB_CODE );
  when ('Owner company')   do;
GRP_APP_CHAR_JOB_CODE  = 1 ;
end;
  when ('Permanent')   do;
GRP_APP_CHAR_JOB_CODE  = 2 ;
end;
  when ('Retired')   do;
GRP_APP_CHAR_JOB_CODE  = 3 ;
end;
otherwise GRP_APP_CHAR_JOB_CODE  = 4 ; end;
select (APP_CHAR_MARITAL_STATUS );
  when ('Divorced')   do;
GRP_APP_CHAR_MARITAL_STATUS  = 1 ;
end;
  when ('Maried')   do;
GRP_APP_CHAR_MARITAL_STATUS  = 2 ;
end;
  when ('Widowed')   do;
GRP_APP_CHAR_MARITAL_STATUS  = 3 ;
end;
otherwise GRP_APP_CHAR_MARITAL_STATUS  = 4 ; end;
select;
when ( not missing(APP_INCOME) and APP_INCOME <= 539 ) do;
GRP_APP_INCOME  = 1 ;
end;
when ( 539 < APP_INCOME <= 1013 ) do;
GRP_APP_INCOME  = 2 ;
end;
when ( 1013 < APP_INCOME <= 1306 ) do;
GRP_APP_INCOME  = 3 ;
end;
when ( 1306 < APP_INCOME <= 1500 ) do;
GRP_APP_INCOME  = 4 ;
end;
when ( 1500 < APP_INCOME <= 4923 ) do;
GRP_APP_INCOME  = 5 ;
end;
when ( 4923 < APP_INCOME ) do;
GRP_APP_INCOME  = 6 ;
end;
when ( missing(APP_INCOME) ) do;
GRP_APP_INCOME  = 7 ;
end;
otherwise GRP_APP_INCOME  = 8 ; end;
select;
when ( not missing(APP_INSTALLMENT) and APP_INSTALLMENT <= 83 ) do;
GRP_APP_INSTALLMENT  = 1 ;
end;
when ( 83 < APP_INSTALLMENT <= 144 ) do;
GRP_APP_INSTALLMENT  = 2 ;
end;
when ( 144 < APP_INSTALLMENT <= 154 ) do;
GRP_APP_INSTALLMENT  = 3 ;
end;
when ( 154 < APP_INSTALLMENT <= 166 ) do;
GRP_APP_INSTALLMENT  = 4 ;
end;
when ( 166 < APP_INSTALLMENT <= 293 ) do;
GRP_APP_INSTALLMENT  = 5 ;
end;
when ( 293 < APP_INSTALLMENT ) do;
GRP_APP_INSTALLMENT  = 6 ;
end;
when ( missing(APP_INSTALLMENT) ) do;
GRP_APP_INSTALLMENT  = 7 ;
end;
otherwise GRP_APP_INSTALLMENT  = 8 ; end;
select;
when ( not missing(APP_LOAN_AMOUNT) and APP_LOAN_AMOUNT <= 1800 ) do;
GRP_APP_LOAN_AMOUNT  = 1 ;
end;
when ( 1800 < APP_LOAN_AMOUNT <= 1968 ) do;
GRP_APP_LOAN_AMOUNT  = 2 ;
end;
when ( 1968 < APP_LOAN_AMOUNT <= 2964 ) do;
GRP_APP_LOAN_AMOUNT  = 3 ;
end;
when ( 2964 < APP_LOAN_AMOUNT <= 7668 ) do;
GRP_APP_LOAN_AMOUNT  = 4 ;
end;
when ( 7668 < APP_LOAN_AMOUNT <= 9384 ) do;
GRP_APP_LOAN_AMOUNT  = 5 ;
end;
when ( 9384 < APP_LOAN_AMOUNT ) do;
GRP_APP_LOAN_AMOUNT  = 6 ;
end;
when ( missing(APP_LOAN_AMOUNT) ) do;
GRP_APP_LOAN_AMOUNT  = 7 ;
end;
otherwise GRP_APP_LOAN_AMOUNT  = 8 ; end;
select;
when ( not missing(APP_NUMBER_OF_CHILDREN) and APP_NUMBER_OF_CHILDREN <= 0 ) do;
GRP_APP_NUMBER_OF_CHILDREN  = 1 ;
end;
when ( 0 < APP_NUMBER_OF_CHILDREN <= 1 ) do;
GRP_APP_NUMBER_OF_CHILDREN  = 2 ;
end;
when ( 1 < APP_NUMBER_OF_CHILDREN ) do;
GRP_APP_NUMBER_OF_CHILDREN  = 3 ;
end;
when ( missing(APP_NUMBER_OF_CHILDREN) ) do;
GRP_APP_NUMBER_OF_CHILDREN  = 4 ;
end;
otherwise GRP_APP_NUMBER_OF_CHILDREN  = 5 ; end;
select;
when ( not missing(APP_N_INSTALLMENTS) and APP_N_INSTALLMENTS <= 12 ) do;
GRP_APP_N_INSTALLMENTS  = 1 ;
end;
when ( 12 < APP_N_INSTALLMENTS <= 24 ) do;
GRP_APP_N_INSTALLMENTS  = 2 ;
end;
when ( 24 < APP_N_INSTALLMENTS ) do;
GRP_APP_N_INSTALLMENTS  = 3 ;
end;
when ( missing(APP_N_INSTALLMENTS) ) do;
GRP_APP_N_INSTALLMENTS  = 4 ;
end;
otherwise GRP_APP_N_INSTALLMENTS  = 5 ; end;
select;
when ( not missing(APP_SPENDINGS) and APP_SPENDINGS <= 220 ) do;
GRP_APP_SPENDINGS  = 1 ;
end;
when ( 220 < APP_SPENDINGS <= 620 ) do;
GRP_APP_SPENDINGS  = 2 ;
end;
when ( 620 < APP_SPENDINGS <= 700 ) do;
GRP_APP_SPENDINGS  = 3 ;
end;
when ( 700 < APP_SPENDINGS <= 960 ) do;
GRP_APP_SPENDINGS  = 4 ;
end;
when ( 960 < APP_SPENDINGS <= 2260 ) do;
GRP_APP_SPENDINGS  = 5 ;
end;
when ( 2260 < APP_SPENDINGS ) do;
GRP_APP_SPENDINGS  = 6 ;
end;
when ( missing(APP_SPENDINGS) ) do;
GRP_APP_SPENDINGS  = 7 ;
end;
otherwise GRP_APP_SPENDINGS  = 8 ; end;
run;
