data grp;
set abt.train;
select;
when ( 1.00 < ACT_CC ) do;
GRP_ACT_CC  = 1 ;
end;
when ( 0.85 < ACT_CC <= 1.00 ) do;
GRP_ACT_CC  = 2 ;
end;
when ( 0.25 < ACT_CC <= 0.85 ) do;
GRP_ACT_CC  = 3 ;
end;
when ( not missing(ACT_CC) and ACT_CC <= 0.25 ) do;
GRP_ACT_CC  = 4 ;
end;
otherwise GRP_ACT_CC  = 5 ; end;
select;
when ( missing(ACT_CINS_MIN_SENIORITY) or ACT_CINS_MIN_SENIORITY <= 22 ) do;
GRP_ACT_CINS_MIN_SENIORITY  = 1 ;
end;
when ( 22 < ACT_CINS_MIN_SENIORITY ) do;
GRP_ACT_CINS_MIN_SENIORITY  = 2 ;
end;
otherwise GRP_ACT_CINS_MIN_SENIORITY  = 3 ; end;
select;
when ( not missing(ACT_CINS_N_STATC) and ACT_CINS_N_STATC <= 0 ) do;
GRP_ACT_CINS_N_STATC  = 1 ;
end;
when ( missing(ACT_CINS_N_STATC) ) do;
GRP_ACT_CINS_N_STATC  = 2 ;
end;
when ( 0 < ACT_CINS_N_STATC <= 2 ) do;
GRP_ACT_CINS_N_STATC  = 3 ;
end;
when ( 2 < ACT_CINS_N_STATC ) do;
GRP_ACT_CINS_N_STATC  = 4 ;
end;
otherwise GRP_ACT_CINS_N_STATC  = 5 ; end;
select (APP_CHAR_JOB_CODE );
  when ('Owner company')   do;
GRP_APP_CHAR_JOB_CODE  = 1 ;
end;
  when ('Retired')   do;
GRP_APP_CHAR_JOB_CODE  = 2 ;
end;
  when ('Permanent')   do;
GRP_APP_CHAR_JOB_CODE  = 3 ;
end;
  when ('Contract')   do;
GRP_APP_CHAR_JOB_CODE  = 4 ;
end;
otherwise GRP_APP_CHAR_JOB_CODE  = 5 ; end;
select (APP_CHAR_MARITAL_STATUS );
  when ('Singiel','Divorced')   do;
GRP_APP_CHAR_MARITAL_STATUS  = 1 ;
end;
  when ('Maried','Widowed')   do;
GRP_APP_CHAR_MARITAL_STATUS  = 2 ;
end;
otherwise GRP_APP_CHAR_MARITAL_STATUS  = 3 ; end;
select;
when ( 11376 < APP_LOAN_AMOUNT ) do;
GRP_APP_LOAN_AMOUNT  = 1 ;
end;
when ( 8880 < APP_LOAN_AMOUNT <= 11376 ) do;
GRP_APP_LOAN_AMOUNT  = 2 ;
end;
when ( 4824 < APP_LOAN_AMOUNT <= 8880 ) do;
GRP_APP_LOAN_AMOUNT  = 3 ;
end;
when ( 1968 < APP_LOAN_AMOUNT <= 4824 ) do;
GRP_APP_LOAN_AMOUNT  = 4 ;
end;
when ( not missing(APP_LOAN_AMOUNT) and APP_LOAN_AMOUNT <= 1968 ) do;
GRP_APP_LOAN_AMOUNT  = 5 ;
end;
otherwise GRP_APP_LOAN_AMOUNT  = 6 ; end;
select;
when ( not missing(APP_NUMBER_OF_CHILDREN) and APP_NUMBER_OF_CHILDREN <= 0 ) do;
GRP_APP_NUMBER_OF_CHILDREN  = 1 ;
end;
when ( 0 < APP_NUMBER_OF_CHILDREN <= 1 ) do;
GRP_APP_NUMBER_OF_CHILDREN  = 2 ;
end;
when ( 1 < APP_NUMBER_OF_CHILDREN ) do;
GRP_APP_NUMBER_OF_CHILDREN  = 3 ;
end;
when ( missing(APP_NUMBER_OF_CHILDREN) ) do;
GRP_APP_NUMBER_OF_CHILDREN  = 4 ;
end;
otherwise GRP_APP_NUMBER_OF_CHILDREN  = 5 ; end;
run;
