data grp;
set abt.train;
select;
when ( not missing(ACT12_N_ARREARS) and ACT12_N_ARREARS <= 6 ) do;
GRP_ACT12_N_ARREARS  = 1 ;
end;
when ( 6 < ACT12_N_ARREARS <= 9 ) do;
GRP_ACT12_N_ARREARS  = 2 ;
end;
when ( 9 < ACT12_N_ARREARS <= 11 ) do;
GRP_ACT12_N_ARREARS  = 3 ;
end;
when ( 11 < ACT12_N_ARREARS ) do;
GRP_ACT12_N_ARREARS  = 4 ;
end;
when ( missing(ACT12_N_ARREARS) ) do;
GRP_ACT12_N_ARREARS  = 5 ;
end;
otherwise GRP_ACT12_N_ARREARS  = 6 ; end;
select;
when ( not missing(ACT12_N_ARREARS_DAYS) and ACT12_N_ARREARS_DAYS <= 0 ) do;
GRP_ACT12_N_ARREARS_DAYS  = 1 ;
end;
when ( 0 < ACT12_N_ARREARS_DAYS <= 1 ) do;
GRP_ACT12_N_ARREARS_DAYS  = 2 ;
end;
when ( 1 < ACT12_N_ARREARS_DAYS ) do;
GRP_ACT12_N_ARREARS_DAYS  = 3 ;
end;
when ( missing(ACT12_N_ARREARS_DAYS) ) do;
GRP_ACT12_N_ARREARS_DAYS  = 4 ;
end;
otherwise GRP_ACT12_N_ARREARS_DAYS  = 5 ; end;
select;
when ( not missing(ACT12_N_GOOD_DAYS) and ACT12_N_GOOD_DAYS <= 0 ) do;
GRP_ACT12_N_GOOD_DAYS  = 1 ;
end;
when ( 0 < ACT12_N_GOOD_DAYS <= 2 ) do;
GRP_ACT12_N_GOOD_DAYS  = 2 ;
end;
when ( 2 < ACT12_N_GOOD_DAYS <= 4 ) do;
GRP_ACT12_N_GOOD_DAYS  = 3 ;
end;
when ( 4 < ACT12_N_GOOD_DAYS <= 8 ) do;
GRP_ACT12_N_GOOD_DAYS  = 4 ;
end;
when ( 8 < ACT12_N_GOOD_DAYS ) do;
GRP_ACT12_N_GOOD_DAYS  = 5 ;
end;
when ( missing(ACT12_N_GOOD_DAYS) ) do;
GRP_ACT12_N_GOOD_DAYS  = 6 ;
end;
otherwise GRP_ACT12_N_GOOD_DAYS  = 7 ; end;
select;
when ( not missing(ACT3_N_ARREARS) and ACT3_N_ARREARS <= 0 ) do;
GRP_ACT3_N_ARREARS  = 1 ;
end;
when ( 0 < ACT3_N_ARREARS <= 2 ) do;
GRP_ACT3_N_ARREARS  = 2 ;
end;
when ( 2 < ACT3_N_ARREARS ) do;
GRP_ACT3_N_ARREARS  = 3 ;
end;
when ( missing(ACT3_N_ARREARS) ) do;
GRP_ACT3_N_ARREARS  = 4 ;
end;
otherwise GRP_ACT3_N_ARREARS  = 5 ; end;
select;
when ( not missing(ACT3_N_ARREARS_DAYS) and ACT3_N_ARREARS_DAYS <= 0 ) do;
GRP_ACT3_N_ARREARS_DAYS  = 1 ;
end;
when ( 0 < ACT3_N_ARREARS_DAYS ) do;
GRP_ACT3_N_ARREARS_DAYS  = 2 ;
end;
when ( missing(ACT3_N_ARREARS_DAYS) ) do;
GRP_ACT3_N_ARREARS_DAYS  = 3 ;
end;
otherwise GRP_ACT3_N_ARREARS_DAYS  = 4 ; end;
select;
when ( not missing(ACT3_N_GOOD_DAYS) and ACT3_N_GOOD_DAYS <= 0 ) do;
GRP_ACT3_N_GOOD_DAYS  = 1 ;
end;
when ( 0 < ACT3_N_GOOD_DAYS <= 1 ) do;
GRP_ACT3_N_GOOD_DAYS  = 2 ;
end;
when ( 1 < ACT3_N_GOOD_DAYS <= 2 ) do;
GRP_ACT3_N_GOOD_DAYS  = 3 ;
end;
when ( 2 < ACT3_N_GOOD_DAYS ) do;
GRP_ACT3_N_GOOD_DAYS  = 4 ;
end;
when ( missing(ACT3_N_GOOD_DAYS) ) do;
GRP_ACT3_N_GOOD_DAYS  = 5 ;
end;
otherwise GRP_ACT3_N_GOOD_DAYS  = 6 ; end;
select;
when ( not missing(ACT6_N_ARREARS) and ACT6_N_ARREARS <= 0 ) do;
GRP_ACT6_N_ARREARS  = 1 ;
end;
when ( 0 < ACT6_N_ARREARS <= 2 ) do;
GRP_ACT6_N_ARREARS  = 2 ;
end;
when ( 2 < ACT6_N_ARREARS <= 5 ) do;
GRP_ACT6_N_ARREARS  = 3 ;
end;
when ( 5 < ACT6_N_ARREARS ) do;
GRP_ACT6_N_ARREARS  = 4 ;
end;
when ( missing(ACT6_N_ARREARS) ) do;
GRP_ACT6_N_ARREARS  = 5 ;
end;
otherwise GRP_ACT6_N_ARREARS  = 6 ; end;
select;
when ( not missing(ACT6_N_ARREARS_DAYS) and ACT6_N_ARREARS_DAYS <= 0 ) do;
GRP_ACT6_N_ARREARS_DAYS  = 1 ;
end;
when ( 0 < ACT6_N_ARREARS_DAYS ) do;
GRP_ACT6_N_ARREARS_DAYS  = 2 ;
end;
when ( missing(ACT6_N_ARREARS_DAYS) ) do;
GRP_ACT6_N_ARREARS_DAYS  = 3 ;
end;
otherwise GRP_ACT6_N_ARREARS_DAYS  = 4 ; end;
select;
when ( not missing(ACT6_N_GOOD_DAYS) and ACT6_N_GOOD_DAYS <= 0 ) do;
GRP_ACT6_N_GOOD_DAYS  = 1 ;
end;
when ( 0 < ACT6_N_GOOD_DAYS <= 1 ) do;
GRP_ACT6_N_GOOD_DAYS  = 2 ;
end;
when ( 1 < ACT6_N_GOOD_DAYS <= 2 ) do;
GRP_ACT6_N_GOOD_DAYS  = 3 ;
end;
when ( 2 < ACT6_N_GOOD_DAYS ) do;
GRP_ACT6_N_GOOD_DAYS  = 4 ;
end;
when ( missing(ACT6_N_GOOD_DAYS) ) do;
GRP_ACT6_N_GOOD_DAYS  = 5 ;
end;
otherwise GRP_ACT6_N_GOOD_DAYS  = 6 ; end;
select;
when ( not missing(ACT9_N_ARREARS) and ACT9_N_ARREARS <= 3 ) do;
GRP_ACT9_N_ARREARS  = 1 ;
end;
when ( 3 < ACT9_N_ARREARS <= 6 ) do;
GRP_ACT9_N_ARREARS  = 2 ;
end;
when ( 6 < ACT9_N_ARREARS <= 8 ) do;
GRP_ACT9_N_ARREARS  = 3 ;
end;
when ( 8 < ACT9_N_ARREARS ) do;
GRP_ACT9_N_ARREARS  = 4 ;
end;
when ( missing(ACT9_N_ARREARS) ) do;
GRP_ACT9_N_ARREARS  = 5 ;
end;
otherwise GRP_ACT9_N_ARREARS  = 6 ; end;
select;
when ( not missing(ACT9_N_ARREARS_DAYS) and ACT9_N_ARREARS_DAYS <= 0 ) do;
GRP_ACT9_N_ARREARS_DAYS  = 1 ;
end;
when ( 0 < ACT9_N_ARREARS_DAYS ) do;
GRP_ACT9_N_ARREARS_DAYS  = 2 ;
end;
when ( missing(ACT9_N_ARREARS_DAYS) ) do;
GRP_ACT9_N_ARREARS_DAYS  = 3 ;
end;
otherwise GRP_ACT9_N_ARREARS_DAYS  = 4 ; end;
select;
when ( not missing(ACT9_N_GOOD_DAYS) and ACT9_N_GOOD_DAYS <= 1 ) do;
GRP_ACT9_N_GOOD_DAYS  = 1 ;
end;
when ( 1 < ACT9_N_GOOD_DAYS <= 3 ) do;
GRP_ACT9_N_GOOD_DAYS  = 2 ;
end;
when ( 3 < ACT9_N_GOOD_DAYS <= 4 ) do;
GRP_ACT9_N_GOOD_DAYS  = 3 ;
end;
when ( 4 < ACT9_N_GOOD_DAYS <= 5 ) do;
GRP_ACT9_N_GOOD_DAYS  = 4 ;
end;
when ( 5 < ACT9_N_GOOD_DAYS ) do;
GRP_ACT9_N_GOOD_DAYS  = 5 ;
end;
when ( missing(ACT9_N_GOOD_DAYS) ) do;
GRP_ACT9_N_GOOD_DAYS  = 6 ;
end;
otherwise GRP_ACT9_N_GOOD_DAYS  = 7 ; end;
select;
when ( not missing(ACT_AGE) and ACT_AGE <= 49 ) do;
GRP_ACT_AGE  = 1 ;
end;
when ( 49 < ACT_AGE <= 67 ) do;
GRP_ACT_AGE  = 2 ;
end;
when ( 67 < ACT_AGE <= 76 ) do;
GRP_ACT_AGE  = 3 ;
end;
when ( 76 < ACT_AGE <= 78 ) do;
GRP_ACT_AGE  = 4 ;
end;
when ( 78 < ACT_AGE <= 82 ) do;
GRP_ACT_AGE  = 5 ;
end;
when ( 82 < ACT_AGE ) do;
GRP_ACT_AGE  = 6 ;
end;
when ( missing(ACT_AGE) ) do;
GRP_ACT_AGE  = 7 ;
end;
otherwise GRP_ACT_AGE  = 8 ; end;
select;
when ( not missing(ACT_CALL_CC) and ACT_CALL_CC <= 0.2597431355 ) do;
GRP_ACT_CALL_CC  = 1 ;
end;
when ( 0.2597431355 < ACT_CALL_CC <= 0.6728187919 ) do;
GRP_ACT_CALL_CC  = 2 ;
end;
when ( 0.6728187919 < ACT_CALL_CC <= 0.6977491961 ) do;
GRP_ACT_CALL_CC  = 3 ;
end;
when ( 0.6977491961 < ACT_CALL_CC <= 0.9438202247 ) do;
GRP_ACT_CALL_CC  = 4 ;
end;
when ( 0.9438202247 < ACT_CALL_CC <= 1.73828125 ) do;
GRP_ACT_CALL_CC  = 5 ;
end;
when ( 1.73828125 < ACT_CALL_CC ) do;
GRP_ACT_CALL_CC  = 6 ;
end;
when ( missing(ACT_CALL_CC) ) do;
GRP_ACT_CALL_CC  = 7 ;
end;
otherwise GRP_ACT_CALL_CC  = 8 ; end;
select;
when ( not missing(ACT_CALL_N_LOAN) and ACT_CALL_N_LOAN <= 1 ) do;
GRP_ACT_CALL_N_LOAN  = 1 ;
end;
when ( 1 < ACT_CALL_N_LOAN <= 3 ) do;
GRP_ACT_CALL_N_LOAN  = 2 ;
end;
when ( 3 < ACT_CALL_N_LOAN <= 4 ) do;
GRP_ACT_CALL_N_LOAN  = 3 ;
end;
when ( 4 < ACT_CALL_N_LOAN ) do;
GRP_ACT_CALL_N_LOAN  = 4 ;
end;
when ( missing(ACT_CALL_N_LOAN) ) do;
GRP_ACT_CALL_N_LOAN  = 5 ;
end;
otherwise GRP_ACT_CALL_N_LOAN  = 6 ; end;
select;
when ( not missing(ACT_CC) and ACT_CC <= 0.2352191235 ) do;
GRP_ACT_CC  = 1 ;
end;
when ( 0.2352191235 < ACT_CC <= 0.5475871314 ) do;
GRP_ACT_CC  = 2 ;
end;
when ( 0.5475871314 < ACT_CC <= 1.0269503546 ) do;
GRP_ACT_CC  = 3 ;
end;
when ( 1.0269503546 < ACT_CC <= 1.2189189189 ) do;
GRP_ACT_CC  = 4 ;
end;
when ( 1.2189189189 < ACT_CC ) do;
GRP_ACT_CC  = 5 ;
end;
when ( missing(ACT_CC) ) do;
GRP_ACT_CC  = 6 ;
end;
otherwise GRP_ACT_CC  = 7 ; end;
select;
when ( not missing(ACT_CCSS_CC) and ACT_CCSS_CC <= 0.4909810823 ) do;
GRP_ACT_CCSS_CC  = 1 ;
end;
when ( 0.4909810823 < ACT_CCSS_CC <= 0.8892045455 ) do;
GRP_ACT_CCSS_CC  = 2 ;
end;
when ( 0.8892045455 < ACT_CCSS_CC <= 1.1485148515 ) do;
GRP_ACT_CCSS_CC  = 3 ;
end;
when ( 1.1485148515 < ACT_CCSS_CC ) do;
GRP_ACT_CCSS_CC  = 4 ;
end;
when ( missing(ACT_CCSS_CC) ) do;
GRP_ACT_CCSS_CC  = 5 ;
end;
otherwise GRP_ACT_CCSS_CC  = 6 ; end;
select;
when ( not missing(ACT_CCSS_DUEUTL) and ACT_CCSS_DUEUTL <= 0 ) do;
GRP_ACT_CCSS_DUEUTL  = 1 ;
end;
when ( 0 < ACT_CCSS_DUEUTL <= 0.09375 ) do;
GRP_ACT_CCSS_DUEUTL  = 2 ;
end;
when ( 0.09375 < ACT_CCSS_DUEUTL <= 0.15 ) do;
GRP_ACT_CCSS_DUEUTL  = 3 ;
end;
when ( 0.15 < ACT_CCSS_DUEUTL ) do;
GRP_ACT_CCSS_DUEUTL  = 4 ;
end;
when ( missing(ACT_CCSS_DUEUTL) ) do;
GRP_ACT_CCSS_DUEUTL  = 5 ;
end;
otherwise GRP_ACT_CCSS_DUEUTL  = 6 ; end;
select;
when ( not missing(ACT_CCSS_MAXDUE) and ACT_CCSS_MAXDUE <= 0 ) do;
GRP_ACT_CCSS_MAXDUE  = 1 ;
end;
when ( 0 < ACT_CCSS_MAXDUE <= 2 ) do;
GRP_ACT_CCSS_MAXDUE  = 2 ;
end;
when ( 2 < ACT_CCSS_MAXDUE <= 5 ) do;
GRP_ACT_CCSS_MAXDUE  = 3 ;
end;
when ( 5 < ACT_CCSS_MAXDUE ) do;
GRP_ACT_CCSS_MAXDUE  = 4 ;
end;
when ( missing(ACT_CCSS_MAXDUE) ) do;
GRP_ACT_CCSS_MAXDUE  = 5 ;
end;
otherwise GRP_ACT_CCSS_MAXDUE  = 6 ; end;
select;
when ( not missing(ACT_CCSS_MIN_LNINST) and ACT_CCSS_MIN_LNINST <= 3 ) do;
GRP_ACT_CCSS_MIN_LNINST  = 1 ;
end;
when ( 3 < ACT_CCSS_MIN_LNINST <= 8 ) do;
GRP_ACT_CCSS_MIN_LNINST  = 2 ;
end;
when ( 8 < ACT_CCSS_MIN_LNINST <= 14 ) do;
GRP_ACT_CCSS_MIN_LNINST  = 3 ;
end;
when ( 14 < ACT_CCSS_MIN_LNINST ) do;
GRP_ACT_CCSS_MIN_LNINST  = 4 ;
end;
when ( missing(ACT_CCSS_MIN_LNINST) ) do;
GRP_ACT_CCSS_MIN_LNINST  = 5 ;
end;
otherwise GRP_ACT_CCSS_MIN_LNINST  = 6 ; end;
select;
when ( not missing(ACT_CCSS_MIN_PNINST) and ACT_CCSS_MIN_PNINST <= 0 ) do;
GRP_ACT_CCSS_MIN_PNINST  = 1 ;
end;
when ( 0 < ACT_CCSS_MIN_PNINST <= 2 ) do;
GRP_ACT_CCSS_MIN_PNINST  = 2 ;
end;
when ( 2 < ACT_CCSS_MIN_PNINST ) do;
GRP_ACT_CCSS_MIN_PNINST  = 3 ;
end;
when ( missing(ACT_CCSS_MIN_PNINST) ) do;
GRP_ACT_CCSS_MIN_PNINST  = 4 ;
end;
otherwise GRP_ACT_CCSS_MIN_PNINST  = 5 ; end;
select;
when ( not missing(ACT_CCSS_MIN_SENIORITY) and ACT_CCSS_MIN_SENIORITY <= 4 ) do;
GRP_ACT_CCSS_MIN_SENIORITY  = 1 ;
end;
when ( 4 < ACT_CCSS_MIN_SENIORITY <= 23 ) do;
GRP_ACT_CCSS_MIN_SENIORITY  = 2 ;
end;
when ( 23 < ACT_CCSS_MIN_SENIORITY <= 48 ) do;
GRP_ACT_CCSS_MIN_SENIORITY  = 3 ;
end;
when ( 48 < ACT_CCSS_MIN_SENIORITY <= 78 ) do;
GRP_ACT_CCSS_MIN_SENIORITY  = 4 ;
end;
when ( 78 < ACT_CCSS_MIN_SENIORITY ) do;
GRP_ACT_CCSS_MIN_SENIORITY  = 5 ;
end;
when ( missing(ACT_CCSS_MIN_SENIORITY) ) do;
GRP_ACT_CCSS_MIN_SENIORITY  = 6 ;
end;
otherwise GRP_ACT_CCSS_MIN_SENIORITY  = 7 ; end;
select;
when ( not missing(ACT_CCSS_N_LOAN) and ACT_CCSS_N_LOAN <= 0 ) do;
GRP_ACT_CCSS_N_LOAN  = 1 ;
end;
when ( 0 < ACT_CCSS_N_LOAN <= 1 ) do;
GRP_ACT_CCSS_N_LOAN  = 2 ;
end;
when ( 1 < ACT_CCSS_N_LOAN <= 2 ) do;
GRP_ACT_CCSS_N_LOAN  = 3 ;
end;
when ( 2 < ACT_CCSS_N_LOAN <= 3 ) do;
GRP_ACT_CCSS_N_LOAN  = 4 ;
end;
when ( 3 < ACT_CCSS_N_LOAN ) do;
GRP_ACT_CCSS_N_LOAN  = 5 ;
end;
when ( missing(ACT_CCSS_N_LOAN) ) do;
GRP_ACT_CCSS_N_LOAN  = 6 ;
end;
otherwise GRP_ACT_CCSS_N_LOAN  = 7 ; end;
select;
when ( not missing(ACT_CCSS_N_LOANS_ACT) and ACT_CCSS_N_LOANS_ACT <= 1 ) do;
GRP_ACT_CCSS_N_LOANS_ACT  = 1 ;
end;
when ( 1 < ACT_CCSS_N_LOANS_ACT <= 2 ) do;
GRP_ACT_CCSS_N_LOANS_ACT  = 2 ;
end;
when ( 2 < ACT_CCSS_N_LOANS_ACT <= 4 ) do;
GRP_ACT_CCSS_N_LOANS_ACT  = 3 ;
end;
when ( 4 < ACT_CCSS_N_LOANS_ACT ) do;
GRP_ACT_CCSS_N_LOANS_ACT  = 4 ;
end;
when ( missing(ACT_CCSS_N_LOANS_ACT) ) do;
GRP_ACT_CCSS_N_LOANS_ACT  = 5 ;
end;
otherwise GRP_ACT_CCSS_N_LOANS_ACT  = 6 ; end;
select;
when ( not missing(ACT_CCSS_N_LOANS_HIST) and ACT_CCSS_N_LOANS_HIST <= 3 ) do;
GRP_ACT_CCSS_N_LOANS_HIST  = 1 ;
end;
when ( 3 < ACT_CCSS_N_LOANS_HIST <= 11 ) do;
GRP_ACT_CCSS_N_LOANS_HIST  = 2 ;
end;
when ( 11 < ACT_CCSS_N_LOANS_HIST <= 14 ) do;
GRP_ACT_CCSS_N_LOANS_HIST  = 3 ;
end;
when ( 14 < ACT_CCSS_N_LOANS_HIST <= 19 ) do;
GRP_ACT_CCSS_N_LOANS_HIST  = 4 ;
end;
when ( 19 < ACT_CCSS_N_LOANS_HIST ) do;
GRP_ACT_CCSS_N_LOANS_HIST  = 5 ;
end;
when ( missing(ACT_CCSS_N_LOANS_HIST) ) do;
GRP_ACT_CCSS_N_LOANS_HIST  = 6 ;
end;
otherwise GRP_ACT_CCSS_N_LOANS_HIST  = 7 ; end;
select;
when ( not missing(ACT_CCSS_N_STATB) and ACT_CCSS_N_STATB <= 6 ) do;
GRP_ACT_CCSS_N_STATB  = 1 ;
end;
when ( 6 < ACT_CCSS_N_STATB <= 9 ) do;
GRP_ACT_CCSS_N_STATB  = 2 ;
end;
when ( 9 < ACT_CCSS_N_STATB <= 11 ) do;
GRP_ACT_CCSS_N_STATB  = 3 ;
end;
when ( 11 < ACT_CCSS_N_STATB <= 15 ) do;
GRP_ACT_CCSS_N_STATB  = 4 ;
end;
when ( 15 < ACT_CCSS_N_STATB ) do;
GRP_ACT_CCSS_N_STATB  = 5 ;
end;
when ( missing(ACT_CCSS_N_STATB) ) do;
GRP_ACT_CCSS_N_STATB  = 6 ;
end;
otherwise GRP_ACT_CCSS_N_STATB  = 7 ; end;
select;
when ( not missing(ACT_CCSS_N_STATC) and ACT_CCSS_N_STATC <= 0 ) do;
GRP_ACT_CCSS_N_STATC  = 1 ;
end;
when ( 0 < ACT_CCSS_N_STATC <= 1 ) do;
GRP_ACT_CCSS_N_STATC  = 2 ;
end;
when ( 1 < ACT_CCSS_N_STATC <= 3 ) do;
GRP_ACT_CCSS_N_STATC  = 3 ;
end;
when ( 3 < ACT_CCSS_N_STATC ) do;
GRP_ACT_CCSS_N_STATC  = 4 ;
end;
when ( missing(ACT_CCSS_N_STATC) ) do;
GRP_ACT_CCSS_N_STATC  = 5 ;
end;
otherwise GRP_ACT_CCSS_N_STATC  = 6 ; end;
select;
when ( not missing(ACT_CCSS_SENIORITY) and ACT_CCSS_SENIORITY <= 27 ) do;
GRP_ACT_CCSS_SENIORITY  = 1 ;
end;
when ( 27 < ACT_CCSS_SENIORITY <= 75 ) do;
GRP_ACT_CCSS_SENIORITY  = 2 ;
end;
when ( 75 < ACT_CCSS_SENIORITY <= 96 ) do;
GRP_ACT_CCSS_SENIORITY  = 3 ;
end;
when ( 96 < ACT_CCSS_SENIORITY <= 156 ) do;
GRP_ACT_CCSS_SENIORITY  = 4 ;
end;
when ( 156 < ACT_CCSS_SENIORITY ) do;
GRP_ACT_CCSS_SENIORITY  = 5 ;
end;
when ( missing(ACT_CCSS_SENIORITY) ) do;
GRP_ACT_CCSS_SENIORITY  = 6 ;
end;
otherwise GRP_ACT_CCSS_SENIORITY  = 7 ; end;
select;
when ( not missing(ACT_CCSS_UTL) and ACT_CCSS_UTL <= 0.09375 ) do;
GRP_ACT_CCSS_UTL  = 1 ;
end;
when ( 0.09375 < ACT_CCSS_UTL <= 0.2604166667 ) do;
GRP_ACT_CCSS_UTL  = 2 ;
end;
when ( 0.2604166667 < ACT_CCSS_UTL <= 0.325 ) do;
GRP_ACT_CCSS_UTL  = 3 ;
end;
when ( 0.325 < ACT_CCSS_UTL <= 0.4166666667 ) do;
GRP_ACT_CCSS_UTL  = 4 ;
end;
when ( 0.4166666667 < ACT_CCSS_UTL ) do;
GRP_ACT_CCSS_UTL  = 5 ;
end;
when ( missing(ACT_CCSS_UTL) ) do;
GRP_ACT_CCSS_UTL  = 6 ;
end;
otherwise GRP_ACT_CCSS_UTL  = 7 ; end;
select;
when ( not missing(ACT_CINS_CC) and ACT_CINS_CC <= 0.6825726141 ) do;
GRP_ACT_CINS_CC  = 1 ;
end;
when ( 0.6825726141 < ACT_CINS_CC ) do;
GRP_ACT_CINS_CC  = 2 ;
end;
when ( missing(ACT_CINS_CC) ) do;
GRP_ACT_CINS_CC  = 3 ;
end;
otherwise GRP_ACT_CINS_CC  = 4 ; end;
select;
when ( not missing(ACT_CINS_DUEUTL) ) do;
GRP_ACT_CINS_DUEUTL  = 1 ;
end;
when ( missing(ACT_CINS_DUEUTL) ) do;
GRP_ACT_CINS_DUEUTL  = 2 ;
end;
otherwise GRP_ACT_CINS_DUEUTL  = 3 ; end;
select;
when ( not missing(ACT_CINS_MAXDUE) ) do;
GRP_ACT_CINS_MAXDUE  = 1 ;
end;
when ( missing(ACT_CINS_MAXDUE) ) do;
GRP_ACT_CINS_MAXDUE  = 2 ;
end;
otherwise GRP_ACT_CINS_MAXDUE  = 3 ; end;
select;
when ( not missing(ACT_CINS_MIN_LNINST) and ACT_CINS_MIN_LNINST <= 5 ) do;
GRP_ACT_CINS_MIN_LNINST  = 1 ;
end;
when ( 5 < ACT_CINS_MIN_LNINST <= 10 ) do;
GRP_ACT_CINS_MIN_LNINST  = 2 ;
end;
when ( 10 < ACT_CINS_MIN_LNINST <= 18 ) do;
GRP_ACT_CINS_MIN_LNINST  = 3 ;
end;
when ( 18 < ACT_CINS_MIN_LNINST ) do;
GRP_ACT_CINS_MIN_LNINST  = 4 ;
end;
when ( missing(ACT_CINS_MIN_LNINST) ) do;
GRP_ACT_CINS_MIN_LNINST  = 5 ;
end;
otherwise GRP_ACT_CINS_MIN_LNINST  = 6 ; end;
select;
when ( not missing(ACT_CINS_MIN_PNINST) and ACT_CINS_MIN_PNINST <= 3 ) do;
GRP_ACT_CINS_MIN_PNINST  = 1 ;
end;
when ( 3 < ACT_CINS_MIN_PNINST ) do;
GRP_ACT_CINS_MIN_PNINST  = 2 ;
end;
when ( missing(ACT_CINS_MIN_PNINST) ) do;
GRP_ACT_CINS_MIN_PNINST  = 3 ;
end;
otherwise GRP_ACT_CINS_MIN_PNINST  = 4 ; end;
select;
when ( not missing(ACT_CINS_MIN_SENIORITY) and ACT_CINS_MIN_SENIORITY <= 23 ) do;
GRP_ACT_CINS_MIN_SENIORITY  = 1 ;
end;
when ( 23 < ACT_CINS_MIN_SENIORITY <= 30 ) do;
GRP_ACT_CINS_MIN_SENIORITY  = 2 ;
end;
when ( 30 < ACT_CINS_MIN_SENIORITY <= 40 ) do;
GRP_ACT_CINS_MIN_SENIORITY  = 3 ;
end;
when ( 40 < ACT_CINS_MIN_SENIORITY <= 156 ) do;
GRP_ACT_CINS_MIN_SENIORITY  = 4 ;
end;
when ( 156 < ACT_CINS_MIN_SENIORITY ) do;
GRP_ACT_CINS_MIN_SENIORITY  = 5 ;
end;
when ( missing(ACT_CINS_MIN_SENIORITY) ) do;
GRP_ACT_CINS_MIN_SENIORITY  = 6 ;
end;
otherwise GRP_ACT_CINS_MIN_SENIORITY  = 7 ; end;
select;
when ( not missing(ACT_CINS_N_LOAN) and ACT_CINS_N_LOAN <= 1 ) do;
GRP_ACT_CINS_N_LOAN  = 1 ;
end;
when ( 1 < ACT_CINS_N_LOAN ) do;
GRP_ACT_CINS_N_LOAN  = 2 ;
end;
when ( missing(ACT_CINS_N_LOAN) ) do;
GRP_ACT_CINS_N_LOAN  = 3 ;
end;
otherwise GRP_ACT_CINS_N_LOAN  = 4 ; end;
select;
when ( not missing(ACT_CINS_N_LOANS_ACT) ) do;
GRP_ACT_CINS_N_LOANS_ACT  = 1 ;
end;
when ( missing(ACT_CINS_N_LOANS_ACT) ) do;
GRP_ACT_CINS_N_LOANS_ACT  = 2 ;
end;
otherwise GRP_ACT_CINS_N_LOANS_ACT  = 3 ; end;
select;
when ( not missing(ACT_CINS_N_LOANS_HIST) and ACT_CINS_N_LOANS_HIST <= 1 ) do;
GRP_ACT_CINS_N_LOANS_HIST  = 1 ;
end;
when ( 1 < ACT_CINS_N_LOANS_HIST <= 4 ) do;
GRP_ACT_CINS_N_LOANS_HIST  = 2 ;
end;
when ( 4 < ACT_CINS_N_LOANS_HIST <= 5 ) do;
GRP_ACT_CINS_N_LOANS_HIST  = 3 ;
end;
when ( 5 < ACT_CINS_N_LOANS_HIST ) do;
GRP_ACT_CINS_N_LOANS_HIST  = 4 ;
end;
when ( missing(ACT_CINS_N_LOANS_HIST) ) do;
GRP_ACT_CINS_N_LOANS_HIST  = 5 ;
end;
otherwise GRP_ACT_CINS_N_LOANS_HIST  = 6 ; end;
select;
when ( not missing(ACT_CINS_N_STATB) and ACT_CINS_N_STATB <= 0 ) do;
GRP_ACT_CINS_N_STATB  = 1 ;
end;
when ( 0 < ACT_CINS_N_STATB <= 1 ) do;
GRP_ACT_CINS_N_STATB  = 2 ;
end;
when ( 1 < ACT_CINS_N_STATB <= 2 ) do;
GRP_ACT_CINS_N_STATB  = 3 ;
end;
when ( 2 < ACT_CINS_N_STATB ) do;
GRP_ACT_CINS_N_STATB  = 4 ;
end;
when ( missing(ACT_CINS_N_STATB) ) do;
GRP_ACT_CINS_N_STATB  = 5 ;
end;
otherwise GRP_ACT_CINS_N_STATB  = 6 ; end;
select;
when ( not missing(ACT_CINS_N_STATC) and ACT_CINS_N_STATC <= 0 ) do;
GRP_ACT_CINS_N_STATC  = 1 ;
end;
when ( 0 < ACT_CINS_N_STATC <= 2 ) do;
GRP_ACT_CINS_N_STATC  = 2 ;
end;
when ( 2 < ACT_CINS_N_STATC <= 3 ) do;
GRP_ACT_CINS_N_STATC  = 3 ;
end;
when ( 3 < ACT_CINS_N_STATC <= 4 ) do;
GRP_ACT_CINS_N_STATC  = 4 ;
end;
when ( 4 < ACT_CINS_N_STATC ) do;
GRP_ACT_CINS_N_STATC  = 5 ;
end;
when ( missing(ACT_CINS_N_STATC) ) do;
GRP_ACT_CINS_N_STATC  = 6 ;
end;
otherwise GRP_ACT_CINS_N_STATC  = 7 ; end;
select;
when ( not missing(ACT_CINS_SENIORITY) and ACT_CINS_SENIORITY <= 53 ) do;
GRP_ACT_CINS_SENIORITY  = 1 ;
end;
when ( 53 < ACT_CINS_SENIORITY <= 99 ) do;
GRP_ACT_CINS_SENIORITY  = 2 ;
end;
when ( 99 < ACT_CINS_SENIORITY <= 138 ) do;
GRP_ACT_CINS_SENIORITY  = 3 ;
end;
when ( 138 < ACT_CINS_SENIORITY <= 153 ) do;
GRP_ACT_CINS_SENIORITY  = 4 ;
end;
when ( 153 < ACT_CINS_SENIORITY ) do;
GRP_ACT_CINS_SENIORITY  = 5 ;
end;
when ( missing(ACT_CINS_SENIORITY) ) do;
GRP_ACT_CINS_SENIORITY  = 6 ;
end;
otherwise GRP_ACT_CINS_SENIORITY  = 7 ; end;
select;
when ( not missing(ACT_CINS_UTL) and ACT_CINS_UTL <= 0.3166666667 ) do;
GRP_ACT_CINS_UTL  = 1 ;
end;
when ( 0.3166666667 < ACT_CINS_UTL <= 0.55 ) do;
GRP_ACT_CINS_UTL  = 2 ;
end;
when ( 0.55 < ACT_CINS_UTL <= 0.7777777778 ) do;
GRP_ACT_CINS_UTL  = 3 ;
end;
when ( 0.7777777778 < ACT_CINS_UTL ) do;
GRP_ACT_CINS_UTL  = 4 ;
end;
when ( missing(ACT_CINS_UTL) ) do;
GRP_ACT_CINS_UTL  = 5 ;
end;
otherwise GRP_ACT_CINS_UTL  = 6 ; end;
select;
when ( not missing(ACT_CUS_ACTIVE) ) do;
GRP_ACT_CUS_ACTIVE  = 1 ;
end;
when ( missing(ACT_CUS_ACTIVE) ) do;
GRP_ACT_CUS_ACTIVE  = 2 ;
end;
otherwise GRP_ACT_CUS_ACTIVE  = 3 ; end;
select;
when ( not missing(ACT_LOANINC) and ACT_LOANINC <= 0.4264900662 ) do;
GRP_ACT_LOANINC  = 1 ;
end;
when ( 0.4264900662 < ACT_LOANINC <= 2.3571428571 ) do;
GRP_ACT_LOANINC  = 2 ;
end;
when ( 2.3571428571 < ACT_LOANINC <= 2.5937113147 ) do;
GRP_ACT_LOANINC  = 3 ;
end;
when ( 2.5937113147 < ACT_LOANINC <= 7.4827586207 ) do;
GRP_ACT_LOANINC  = 4 ;
end;
when ( 7.4827586207 < ACT_LOANINC <= 16.883458647 ) do;
GRP_ACT_LOANINC  = 5 ;
end;
when ( 16.883458647 < ACT_LOANINC ) do;
GRP_ACT_LOANINC  = 6 ;
end;
when ( missing(ACT_LOANINC) ) do;
GRP_ACT_LOANINC  = 7 ;
end;
otherwise GRP_ACT_LOANINC  = 8 ; end;
select;
when ( not missing(AGR12_MAX_CMAXA_DAYS) and AGR12_MAX_CMAXA_DAYS <= 16 ) do;
GRP_AGR12_MAX_CMAXA_DAYS  = 1 ;
end;
when ( 16 < AGR12_MAX_CMAXA_DAYS ) do;
GRP_AGR12_MAX_CMAXA_DAYS  = 2 ;
end;
when ( missing(AGR12_MAX_CMAXA_DAYS) ) do;
GRP_AGR12_MAX_CMAXA_DAYS  = 3 ;
end;
otherwise GRP_AGR12_MAX_CMAXA_DAYS  = 4 ; end;
select;
when ( not missing(AGR12_MAX_CMAXA_DUE) and AGR12_MAX_CMAXA_DUE <= 1 ) do;
GRP_AGR12_MAX_CMAXA_DUE  = 1 ;
end;
when ( 1 < AGR12_MAX_CMAXA_DUE <= 5 ) do;
GRP_AGR12_MAX_CMAXA_DUE  = 2 ;
end;
when ( 5 < AGR12_MAX_CMAXA_DUE ) do;
GRP_AGR12_MAX_CMAXA_DUE  = 3 ;
end;
when ( missing(AGR12_MAX_CMAXA_DUE) ) do;
GRP_AGR12_MAX_CMAXA_DUE  = 4 ;
end;
otherwise GRP_AGR12_MAX_CMAXA_DUE  = 5 ; end;
select;
when ( not missing(AGR12_MAX_CMAXC_DAYS) ) do;
GRP_AGR12_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR12_MAX_CMAXC_DAYS) ) do;
GRP_AGR12_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MAX_CMAXC_DUE) and AGR12_MAX_CMAXC_DUE <= 2 ) do;
GRP_AGR12_MAX_CMAXC_DUE  = 1 ;
end;
when ( 2 < AGR12_MAX_CMAXC_DUE ) do;
GRP_AGR12_MAX_CMAXC_DUE  = 2 ;
end;
when ( missing(AGR12_MAX_CMAXC_DUE) ) do;
GRP_AGR12_MAX_CMAXC_DUE  = 3 ;
end;
otherwise GRP_AGR12_MAX_CMAXC_DUE  = 4 ; end;
select;
when ( not missing(AGR12_MAX_CMAXI_DAYS) ) do;
GRP_AGR12_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR12_MAX_CMAXI_DAYS) ) do;
GRP_AGR12_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MAX_CMAXI_DUE) and AGR12_MAX_CMAXI_DUE <= 0 ) do;
GRP_AGR12_MAX_CMAXI_DUE  = 1 ;
end;
when ( 0 < AGR12_MAX_CMAXI_DUE ) do;
GRP_AGR12_MAX_CMAXI_DUE  = 2 ;
end;
when ( missing(AGR12_MAX_CMAXI_DUE) ) do;
GRP_AGR12_MAX_CMAXI_DUE  = 3 ;
end;
otherwise GRP_AGR12_MAX_CMAXI_DUE  = 4 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXA_DAYS) and AGR12_MEAN_CMAXA_DAYS <= 13.583333333 ) do;
GRP_AGR12_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( 13.583333333 < AGR12_MEAN_CMAXA_DAYS <= 14.333333333 ) do;
GRP_AGR12_MEAN_CMAXA_DAYS  = 2 ;
end;
when ( 14.333333333 < AGR12_MEAN_CMAXA_DAYS ) do;
GRP_AGR12_MEAN_CMAXA_DAYS  = 3 ;
end;
when ( missing(AGR12_MEAN_CMAXA_DAYS) ) do;
GRP_AGR12_MEAN_CMAXA_DAYS  = 4 ;
end;
otherwise GRP_AGR12_MEAN_CMAXA_DAYS  = 5 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXA_DUE) and AGR12_MEAN_CMAXA_DUE <= 0.4166666667 ) do;
GRP_AGR12_MEAN_CMAXA_DUE  = 1 ;
end;
when ( 0.4166666667 < AGR12_MEAN_CMAXA_DUE <= 3.6666666667 ) do;
GRP_AGR12_MEAN_CMAXA_DUE  = 2 ;
end;
when ( 3.6666666667 < AGR12_MEAN_CMAXA_DUE <= 5.3333333333 ) do;
GRP_AGR12_MEAN_CMAXA_DUE  = 3 ;
end;
when ( 5.3333333333 < AGR12_MEAN_CMAXA_DUE ) do;
GRP_AGR12_MEAN_CMAXA_DUE  = 4 ;
end;
when ( missing(AGR12_MEAN_CMAXA_DUE) ) do;
GRP_AGR12_MEAN_CMAXA_DUE  = 5 ;
end;
otherwise GRP_AGR12_MEAN_CMAXA_DUE  = 6 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXC_DAYS) and AGR12_MEAN_CMAXC_DAYS <= 14 ) do;
GRP_AGR12_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( 14 < AGR12_MEAN_CMAXC_DAYS ) do;
GRP_AGR12_MEAN_CMAXC_DAYS  = 2 ;
end;
when ( missing(AGR12_MEAN_CMAXC_DAYS) ) do;
GRP_AGR12_MEAN_CMAXC_DAYS  = 3 ;
end;
otherwise GRP_AGR12_MEAN_CMAXC_DAYS  = 4 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXC_DUE) and AGR12_MEAN_CMAXC_DUE <= 0.5 ) do;
GRP_AGR12_MEAN_CMAXC_DUE  = 1 ;
end;
when ( 0.5 < AGR12_MEAN_CMAXC_DUE <= 3 ) do;
GRP_AGR12_MEAN_CMAXC_DUE  = 2 ;
end;
when ( 3 < AGR12_MEAN_CMAXC_DUE <= 5.4166666667 ) do;
GRP_AGR12_MEAN_CMAXC_DUE  = 3 ;
end;
when ( 5.4166666667 < AGR12_MEAN_CMAXC_DUE ) do;
GRP_AGR12_MEAN_CMAXC_DUE  = 4 ;
end;
when ( missing(AGR12_MEAN_CMAXC_DUE) ) do;
GRP_AGR12_MEAN_CMAXC_DUE  = 5 ;
end;
otherwise GRP_AGR12_MEAN_CMAXC_DUE  = 6 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXI_DAYS) and AGR12_MEAN_CMAXI_DAYS <= 12.583333333 ) do;
GRP_AGR12_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( 12.583333333 < AGR12_MEAN_CMAXI_DAYS ) do;
GRP_AGR12_MEAN_CMAXI_DAYS  = 2 ;
end;
when ( missing(AGR12_MEAN_CMAXI_DAYS) ) do;
GRP_AGR12_MEAN_CMAXI_DAYS  = 3 ;
end;
otherwise GRP_AGR12_MEAN_CMAXI_DAYS  = 4 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXI_DUE) and AGR12_MEAN_CMAXI_DUE <= 0 ) do;
GRP_AGR12_MEAN_CMAXI_DUE  = 1 ;
end;
when ( 0 < AGR12_MEAN_CMAXI_DUE ) do;
GRP_AGR12_MEAN_CMAXI_DUE  = 2 ;
end;
when ( missing(AGR12_MEAN_CMAXI_DUE) ) do;
GRP_AGR12_MEAN_CMAXI_DUE  = 3 ;
end;
otherwise GRP_AGR12_MEAN_CMAXI_DUE  = 4 ; end;
select;
when ( not missing(AGR12_MIN_CMAXA_DAYS) and AGR12_MIN_CMAXA_DAYS <= 9 ) do;
GRP_AGR12_MIN_CMAXA_DAYS  = 1 ;
end;
when ( 9 < AGR12_MIN_CMAXA_DAYS <= 11 ) do;
GRP_AGR12_MIN_CMAXA_DAYS  = 2 ;
end;
when ( 11 < AGR12_MIN_CMAXA_DAYS ) do;
GRP_AGR12_MIN_CMAXA_DAYS  = 3 ;
end;
when ( missing(AGR12_MIN_CMAXA_DAYS) ) do;
GRP_AGR12_MIN_CMAXA_DAYS  = 4 ;
end;
otherwise GRP_AGR12_MIN_CMAXA_DAYS  = 5 ; end;
select;
when ( not missing(AGR12_MIN_CMAXA_DUE) and AGR12_MIN_CMAXA_DUE <= 0 ) do;
GRP_AGR12_MIN_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGR12_MIN_CMAXA_DUE <= 1 ) do;
GRP_AGR12_MIN_CMAXA_DUE  = 2 ;
end;
when ( 1 < AGR12_MIN_CMAXA_DUE ) do;
GRP_AGR12_MIN_CMAXA_DUE  = 3 ;
end;
when ( missing(AGR12_MIN_CMAXA_DUE) ) do;
GRP_AGR12_MIN_CMAXA_DUE  = 4 ;
end;
otherwise GRP_AGR12_MIN_CMAXA_DUE  = 5 ; end;
select;
when ( not missing(AGR12_MIN_CMAXC_DAYS) and AGR12_MIN_CMAXC_DAYS <= 10 ) do;
GRP_AGR12_MIN_CMAXC_DAYS  = 1 ;
end;
when ( 10 < AGR12_MIN_CMAXC_DAYS ) do;
GRP_AGR12_MIN_CMAXC_DAYS  = 2 ;
end;
when ( missing(AGR12_MIN_CMAXC_DAYS) ) do;
GRP_AGR12_MIN_CMAXC_DAYS  = 3 ;
end;
otherwise GRP_AGR12_MIN_CMAXC_DAYS  = 4 ; end;
select;
when ( not missing(AGR12_MIN_CMAXC_DUE) and AGR12_MIN_CMAXC_DUE <= 0 ) do;
GRP_AGR12_MIN_CMAXC_DUE  = 1 ;
end;
when ( 0 < AGR12_MIN_CMAXC_DUE <= 1 ) do;
GRP_AGR12_MIN_CMAXC_DUE  = 2 ;
end;
when ( 1 < AGR12_MIN_CMAXC_DUE ) do;
GRP_AGR12_MIN_CMAXC_DUE  = 3 ;
end;
when ( missing(AGR12_MIN_CMAXC_DUE) ) do;
GRP_AGR12_MIN_CMAXC_DUE  = 4 ;
end;
otherwise GRP_AGR12_MIN_CMAXC_DUE  = 5 ; end;
select;
when ( not missing(AGR12_MIN_CMAXI_DAYS) and AGR12_MIN_CMAXI_DAYS <= 8 ) do;
GRP_AGR12_MIN_CMAXI_DAYS  = 1 ;
end;
when ( 8 < AGR12_MIN_CMAXI_DAYS ) do;
GRP_AGR12_MIN_CMAXI_DAYS  = 2 ;
end;
when ( missing(AGR12_MIN_CMAXI_DAYS) ) do;
GRP_AGR12_MIN_CMAXI_DAYS  = 3 ;
end;
otherwise GRP_AGR12_MIN_CMAXI_DAYS  = 4 ; end;
select;
when ( not missing(AGR12_MIN_CMAXI_DUE) ) do;
GRP_AGR12_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR12_MIN_CMAXI_DUE) ) do;
GRP_AGR12_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR12_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MAX_CMAXA_DAYS) and AGR3_MAX_CMAXA_DAYS <= 14 ) do;
GRP_AGR3_MAX_CMAXA_DAYS  = 1 ;
end;
when ( 14 < AGR3_MAX_CMAXA_DAYS ) do;
GRP_AGR3_MAX_CMAXA_DAYS  = 2 ;
end;
when ( missing(AGR3_MAX_CMAXA_DAYS) ) do;
GRP_AGR3_MAX_CMAXA_DAYS  = 3 ;
end;
otherwise GRP_AGR3_MAX_CMAXA_DAYS  = 4 ; end;
select;
when ( not missing(AGR3_MAX_CMAXA_DUE) and AGR3_MAX_CMAXA_DUE <= 0 ) do;
GRP_AGR3_MAX_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGR3_MAX_CMAXA_DUE <= 3 ) do;
GRP_AGR3_MAX_CMAXA_DUE  = 2 ;
end;
when ( 3 < AGR3_MAX_CMAXA_DUE <= 6 ) do;
GRP_AGR3_MAX_CMAXA_DUE  = 3 ;
end;
when ( 6 < AGR3_MAX_CMAXA_DUE ) do;
GRP_AGR3_MAX_CMAXA_DUE  = 4 ;
end;
when ( missing(AGR3_MAX_CMAXA_DUE) ) do;
GRP_AGR3_MAX_CMAXA_DUE  = 5 ;
end;
otherwise GRP_AGR3_MAX_CMAXA_DUE  = 6 ; end;
select;
when ( not missing(AGR3_MAX_CMAXC_DAYS) ) do;
GRP_AGR3_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR3_MAX_CMAXC_DAYS) ) do;
GRP_AGR3_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MAX_CMAXC_DUE) and AGR3_MAX_CMAXC_DUE <= 0 ) do;
GRP_AGR3_MAX_CMAXC_DUE  = 1 ;
end;
when ( 0 < AGR3_MAX_CMAXC_DUE <= 3 ) do;
GRP_AGR3_MAX_CMAXC_DUE  = 2 ;
end;
when ( 3 < AGR3_MAX_CMAXC_DUE <= 6 ) do;
GRP_AGR3_MAX_CMAXC_DUE  = 3 ;
end;
when ( 6 < AGR3_MAX_CMAXC_DUE ) do;
GRP_AGR3_MAX_CMAXC_DUE  = 4 ;
end;
when ( missing(AGR3_MAX_CMAXC_DUE) ) do;
GRP_AGR3_MAX_CMAXC_DUE  = 5 ;
end;
otherwise GRP_AGR3_MAX_CMAXC_DUE  = 6 ; end;
select;
when ( not missing(AGR3_MAX_CMAXI_DAYS) and AGR3_MAX_CMAXI_DAYS <= 14 ) do;
GRP_AGR3_MAX_CMAXI_DAYS  = 1 ;
end;
when ( 14 < AGR3_MAX_CMAXI_DAYS ) do;
GRP_AGR3_MAX_CMAXI_DAYS  = 2 ;
end;
when ( missing(AGR3_MAX_CMAXI_DAYS) ) do;
GRP_AGR3_MAX_CMAXI_DAYS  = 3 ;
end;
otherwise GRP_AGR3_MAX_CMAXI_DAYS  = 4 ; end;
select;
when ( not missing(AGR3_MAX_CMAXI_DUE) and AGR3_MAX_CMAXI_DUE <= 0 ) do;
GRP_AGR3_MAX_CMAXI_DUE  = 1 ;
end;
when ( 0 < AGR3_MAX_CMAXI_DUE ) do;
GRP_AGR3_MAX_CMAXI_DUE  = 2 ;
end;
when ( missing(AGR3_MAX_CMAXI_DUE) ) do;
GRP_AGR3_MAX_CMAXI_DUE  = 3 ;
end;
otherwise GRP_AGR3_MAX_CMAXI_DUE  = 4 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXA_DAYS) and AGR3_MEAN_CMAXA_DAYS <= 12.666666667 ) do;
GRP_AGR3_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( 12.666666667 < AGR3_MEAN_CMAXA_DAYS <= 14.333333333 ) do;
GRP_AGR3_MEAN_CMAXA_DAYS  = 2 ;
end;
when ( 14.333333333 < AGR3_MEAN_CMAXA_DAYS <= 14.666666667 ) do;
GRP_AGR3_MEAN_CMAXA_DAYS  = 3 ;
end;
when ( 14.666666667 < AGR3_MEAN_CMAXA_DAYS ) do;
GRP_AGR3_MEAN_CMAXA_DAYS  = 4 ;
end;
when ( missing(AGR3_MEAN_CMAXA_DAYS) ) do;
GRP_AGR3_MEAN_CMAXA_DAYS  = 5 ;
end;
otherwise GRP_AGR3_MEAN_CMAXA_DAYS  = 6 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXA_DUE) and AGR3_MEAN_CMAXA_DUE <= 0 ) do;
GRP_AGR3_MEAN_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGR3_MEAN_CMAXA_DUE <= 2.3333333333 ) do;
GRP_AGR3_MEAN_CMAXA_DUE  = 2 ;
end;
when ( 2.3333333333 < AGR3_MEAN_CMAXA_DUE <= 4.6666666667 ) do;
GRP_AGR3_MEAN_CMAXA_DUE  = 3 ;
end;
when ( 4.6666666667 < AGR3_MEAN_CMAXA_DUE <= 6.3333333333 ) do;
GRP_AGR3_MEAN_CMAXA_DUE  = 4 ;
end;
when ( 6.3333333333 < AGR3_MEAN_CMAXA_DUE ) do;
GRP_AGR3_MEAN_CMAXA_DUE  = 5 ;
end;
when ( missing(AGR3_MEAN_CMAXA_DUE) ) do;
GRP_AGR3_MEAN_CMAXA_DUE  = 6 ;
end;
otherwise GRP_AGR3_MEAN_CMAXA_DUE  = 7 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXC_DAYS) and AGR3_MEAN_CMAXC_DAYS <= 14.333333333 ) do;
GRP_AGR3_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( 14.333333333 < AGR3_MEAN_CMAXC_DAYS ) do;
GRP_AGR3_MEAN_CMAXC_DAYS  = 2 ;
end;
when ( missing(AGR3_MEAN_CMAXC_DAYS) ) do;
GRP_AGR3_MEAN_CMAXC_DAYS  = 3 ;
end;
otherwise GRP_AGR3_MEAN_CMAXC_DAYS  = 4 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXC_DUE) and AGR3_MEAN_CMAXC_DUE <= 0.6666666667 ) do;
GRP_AGR3_MEAN_CMAXC_DUE  = 1 ;
end;
when ( 0.6666666667 < AGR3_MEAN_CMAXC_DUE <= 2 ) do;
GRP_AGR3_MEAN_CMAXC_DUE  = 2 ;
end;
when ( 2 < AGR3_MEAN_CMAXC_DUE <= 5 ) do;
GRP_AGR3_MEAN_CMAXC_DUE  = 3 ;
end;
when ( 5 < AGR3_MEAN_CMAXC_DUE ) do;
GRP_AGR3_MEAN_CMAXC_DUE  = 4 ;
end;
when ( missing(AGR3_MEAN_CMAXC_DUE) ) do;
GRP_AGR3_MEAN_CMAXC_DUE  = 5 ;
end;
otherwise GRP_AGR3_MEAN_CMAXC_DUE  = 6 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXI_DAYS) and AGR3_MEAN_CMAXI_DAYS <= 12 ) do;
GRP_AGR3_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( 12 < AGR3_MEAN_CMAXI_DAYS <= 13 ) do;
GRP_AGR3_MEAN_CMAXI_DAYS  = 2 ;
end;
when ( 13 < AGR3_MEAN_CMAXI_DAYS ) do;
GRP_AGR3_MEAN_CMAXI_DAYS  = 3 ;
end;
when ( missing(AGR3_MEAN_CMAXI_DAYS) ) do;
GRP_AGR3_MEAN_CMAXI_DAYS  = 4 ;
end;
otherwise GRP_AGR3_MEAN_CMAXI_DAYS  = 5 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXI_DUE) and AGR3_MEAN_CMAXI_DUE <= 0 ) do;
GRP_AGR3_MEAN_CMAXI_DUE  = 1 ;
end;
when ( 0 < AGR3_MEAN_CMAXI_DUE ) do;
GRP_AGR3_MEAN_CMAXI_DUE  = 2 ;
end;
when ( missing(AGR3_MEAN_CMAXI_DUE) ) do;
GRP_AGR3_MEAN_CMAXI_DUE  = 3 ;
end;
otherwise GRP_AGR3_MEAN_CMAXI_DUE  = 4 ; end;
select;
when ( not missing(AGR3_MIN_CMAXA_DAYS) and AGR3_MIN_CMAXA_DAYS <= 10 ) do;
GRP_AGR3_MIN_CMAXA_DAYS  = 1 ;
end;
when ( 10 < AGR3_MIN_CMAXA_DAYS <= 12 ) do;
GRP_AGR3_MIN_CMAXA_DAYS  = 2 ;
end;
when ( 12 < AGR3_MIN_CMAXA_DAYS <= 13 ) do;
GRP_AGR3_MIN_CMAXA_DAYS  = 3 ;
end;
when ( 13 < AGR3_MIN_CMAXA_DAYS ) do;
GRP_AGR3_MIN_CMAXA_DAYS  = 4 ;
end;
when ( missing(AGR3_MIN_CMAXA_DAYS) ) do;
GRP_AGR3_MIN_CMAXA_DAYS  = 5 ;
end;
otherwise GRP_AGR3_MIN_CMAXA_DAYS  = 6 ; end;
select;
when ( not missing(AGR3_MIN_CMAXA_DUE) and AGR3_MIN_CMAXA_DUE <= 0 ) do;
GRP_AGR3_MIN_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGR3_MIN_CMAXA_DUE <= 1 ) do;
GRP_AGR3_MIN_CMAXA_DUE  = 2 ;
end;
when ( 1 < AGR3_MIN_CMAXA_DUE <= 3 ) do;
GRP_AGR3_MIN_CMAXA_DUE  = 3 ;
end;
when ( 3 < AGR3_MIN_CMAXA_DUE <= 5 ) do;
GRP_AGR3_MIN_CMAXA_DUE  = 4 ;
end;
when ( 5 < AGR3_MIN_CMAXA_DUE ) do;
GRP_AGR3_MIN_CMAXA_DUE  = 5 ;
end;
when ( missing(AGR3_MIN_CMAXA_DUE) ) do;
GRP_AGR3_MIN_CMAXA_DUE  = 6 ;
end;
otherwise GRP_AGR3_MIN_CMAXA_DUE  = 7 ; end;
select;
when ( not missing(AGR3_MIN_CMAXC_DAYS) and AGR3_MIN_CMAXC_DAYS <= 11 ) do;
GRP_AGR3_MIN_CMAXC_DAYS  = 1 ;
end;
when ( 11 < AGR3_MIN_CMAXC_DAYS <= 13 ) do;
GRP_AGR3_MIN_CMAXC_DAYS  = 2 ;
end;
when ( 13 < AGR3_MIN_CMAXC_DAYS ) do;
GRP_AGR3_MIN_CMAXC_DAYS  = 3 ;
end;
when ( missing(AGR3_MIN_CMAXC_DAYS) ) do;
GRP_AGR3_MIN_CMAXC_DAYS  = 4 ;
end;
otherwise GRP_AGR3_MIN_CMAXC_DAYS  = 5 ; end;
select;
when ( not missing(AGR3_MIN_CMAXC_DUE) and AGR3_MIN_CMAXC_DUE <= 0 ) do;
GRP_AGR3_MIN_CMAXC_DUE  = 1 ;
end;
when ( 0 < AGR3_MIN_CMAXC_DUE <= 3 ) do;
GRP_AGR3_MIN_CMAXC_DUE  = 2 ;
end;
when ( 3 < AGR3_MIN_CMAXC_DUE <= 5 ) do;
GRP_AGR3_MIN_CMAXC_DUE  = 3 ;
end;
when ( 5 < AGR3_MIN_CMAXC_DUE ) do;
GRP_AGR3_MIN_CMAXC_DUE  = 4 ;
end;
when ( missing(AGR3_MIN_CMAXC_DUE) ) do;
GRP_AGR3_MIN_CMAXC_DUE  = 5 ;
end;
otherwise GRP_AGR3_MIN_CMAXC_DUE  = 6 ; end;
select;
when ( not missing(AGR3_MIN_CMAXI_DAYS) and AGR3_MIN_CMAXI_DAYS <= 10 ) do;
GRP_AGR3_MIN_CMAXI_DAYS  = 1 ;
end;
when ( 10 < AGR3_MIN_CMAXI_DAYS ) do;
GRP_AGR3_MIN_CMAXI_DAYS  = 2 ;
end;
when ( missing(AGR3_MIN_CMAXI_DAYS) ) do;
GRP_AGR3_MIN_CMAXI_DAYS  = 3 ;
end;
otherwise GRP_AGR3_MIN_CMAXI_DAYS  = 4 ; end;
select;
when ( not missing(AGR3_MIN_CMAXI_DUE) ) do;
GRP_AGR3_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR3_MIN_CMAXI_DUE) ) do;
GRP_AGR3_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR3_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MAX_CMAXA_DAYS) and AGR6_MAX_CMAXA_DAYS <= 15 ) do;
GRP_AGR6_MAX_CMAXA_DAYS  = 1 ;
end;
when ( 15 < AGR6_MAX_CMAXA_DAYS ) do;
GRP_AGR6_MAX_CMAXA_DAYS  = 2 ;
end;
when ( missing(AGR6_MAX_CMAXA_DAYS) ) do;
GRP_AGR6_MAX_CMAXA_DAYS  = 3 ;
end;
otherwise GRP_AGR6_MAX_CMAXA_DAYS  = 4 ; end;
select;
when ( not missing(AGR6_MAX_CMAXA_DUE) and AGR6_MAX_CMAXA_DUE <= 0 ) do;
GRP_AGR6_MAX_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGR6_MAX_CMAXA_DUE <= 1 ) do;
GRP_AGR6_MAX_CMAXA_DUE  = 2 ;
end;
when ( 1 < AGR6_MAX_CMAXA_DUE <= 5 ) do;
GRP_AGR6_MAX_CMAXA_DUE  = 3 ;
end;
when ( 5 < AGR6_MAX_CMAXA_DUE ) do;
GRP_AGR6_MAX_CMAXA_DUE  = 4 ;
end;
when ( missing(AGR6_MAX_CMAXA_DUE) ) do;
GRP_AGR6_MAX_CMAXA_DUE  = 5 ;
end;
otherwise GRP_AGR6_MAX_CMAXA_DUE  = 6 ; end;
select;
when ( not missing(AGR6_MAX_CMAXC_DAYS) ) do;
GRP_AGR6_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR6_MAX_CMAXC_DAYS) ) do;
GRP_AGR6_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MAX_CMAXC_DUE) and AGR6_MAX_CMAXC_DUE <= 2 ) do;
GRP_AGR6_MAX_CMAXC_DUE  = 1 ;
end;
when ( 2 < AGR6_MAX_CMAXC_DUE ) do;
GRP_AGR6_MAX_CMAXC_DUE  = 2 ;
end;
when ( missing(AGR6_MAX_CMAXC_DUE) ) do;
GRP_AGR6_MAX_CMAXC_DUE  = 3 ;
end;
otherwise GRP_AGR6_MAX_CMAXC_DUE  = 4 ; end;
select;
when ( not missing(AGR6_MAX_CMAXI_DAYS) ) do;
GRP_AGR6_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR6_MAX_CMAXI_DAYS) ) do;
GRP_AGR6_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MAX_CMAXI_DUE) and AGR6_MAX_CMAXI_DUE <= 0 ) do;
GRP_AGR6_MAX_CMAXI_DUE  = 1 ;
end;
when ( 0 < AGR6_MAX_CMAXI_DUE ) do;
GRP_AGR6_MAX_CMAXI_DUE  = 2 ;
end;
when ( missing(AGR6_MAX_CMAXI_DUE) ) do;
GRP_AGR6_MAX_CMAXI_DUE  = 3 ;
end;
otherwise GRP_AGR6_MAX_CMAXI_DUE  = 4 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXA_DAYS) and AGR6_MEAN_CMAXA_DAYS <= 13 ) do;
GRP_AGR6_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( 13 < AGR6_MEAN_CMAXA_DAYS <= 13.666666667 ) do;
GRP_AGR6_MEAN_CMAXA_DAYS  = 2 ;
end;
when ( 13.666666667 < AGR6_MEAN_CMAXA_DAYS <= 14.5 ) do;
GRP_AGR6_MEAN_CMAXA_DAYS  = 3 ;
end;
when ( 14.5 < AGR6_MEAN_CMAXA_DAYS ) do;
GRP_AGR6_MEAN_CMAXA_DAYS  = 4 ;
end;
when ( missing(AGR6_MEAN_CMAXA_DAYS) ) do;
GRP_AGR6_MEAN_CMAXA_DAYS  = 5 ;
end;
otherwise GRP_AGR6_MEAN_CMAXA_DAYS  = 6 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXA_DUE) and AGR6_MEAN_CMAXA_DUE <= 0.1666666667 ) do;
GRP_AGR6_MEAN_CMAXA_DUE  = 1 ;
end;
when ( 0.1666666667 < AGR6_MEAN_CMAXA_DUE <= 2 ) do;
GRP_AGR6_MEAN_CMAXA_DUE  = 2 ;
end;
when ( 2 < AGR6_MEAN_CMAXA_DUE <= 5.3333333333 ) do;
GRP_AGR6_MEAN_CMAXA_DUE  = 3 ;
end;
when ( 5.3333333333 < AGR6_MEAN_CMAXA_DUE ) do;
GRP_AGR6_MEAN_CMAXA_DUE  = 4 ;
end;
when ( missing(AGR6_MEAN_CMAXA_DUE) ) do;
GRP_AGR6_MEAN_CMAXA_DUE  = 5 ;
end;
otherwise GRP_AGR6_MEAN_CMAXA_DUE  = 6 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXC_DAYS) and AGR6_MEAN_CMAXC_DAYS <= 13.833333333 ) do;
GRP_AGR6_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( 13.833333333 < AGR6_MEAN_CMAXC_DAYS ) do;
GRP_AGR6_MEAN_CMAXC_DAYS  = 2 ;
end;
when ( missing(AGR6_MEAN_CMAXC_DAYS) ) do;
GRP_AGR6_MEAN_CMAXC_DAYS  = 3 ;
end;
otherwise GRP_AGR6_MEAN_CMAXC_DAYS  = 4 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXC_DUE) and AGR6_MEAN_CMAXC_DUE <= 0.6666666667 ) do;
GRP_AGR6_MEAN_CMAXC_DUE  = 1 ;
end;
when ( 0.6666666667 < AGR6_MEAN_CMAXC_DUE <= 2.8333333333 ) do;
GRP_AGR6_MEAN_CMAXC_DUE  = 2 ;
end;
when ( 2.8333333333 < AGR6_MEAN_CMAXC_DUE <= 5.3333333333 ) do;
GRP_AGR6_MEAN_CMAXC_DUE  = 3 ;
end;
when ( 5.3333333333 < AGR6_MEAN_CMAXC_DUE ) do;
GRP_AGR6_MEAN_CMAXC_DUE  = 4 ;
end;
when ( missing(AGR6_MEAN_CMAXC_DUE) ) do;
GRP_AGR6_MEAN_CMAXC_DUE  = 5 ;
end;
otherwise GRP_AGR6_MEAN_CMAXC_DUE  = 6 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXI_DAYS) and AGR6_MEAN_CMAXI_DAYS <= 12.833333333 ) do;
GRP_AGR6_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( 12.833333333 < AGR6_MEAN_CMAXI_DAYS ) do;
GRP_AGR6_MEAN_CMAXI_DAYS  = 2 ;
end;
when ( missing(AGR6_MEAN_CMAXI_DAYS) ) do;
GRP_AGR6_MEAN_CMAXI_DAYS  = 3 ;
end;
otherwise GRP_AGR6_MEAN_CMAXI_DAYS  = 4 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXI_DUE) and AGR6_MEAN_CMAXI_DUE <= 0 ) do;
GRP_AGR6_MEAN_CMAXI_DUE  = 1 ;
end;
when ( 0 < AGR6_MEAN_CMAXI_DUE ) do;
GRP_AGR6_MEAN_CMAXI_DUE  = 2 ;
end;
when ( missing(AGR6_MEAN_CMAXI_DUE) ) do;
GRP_AGR6_MEAN_CMAXI_DUE  = 3 ;
end;
otherwise GRP_AGR6_MEAN_CMAXI_DUE  = 4 ; end;
select;
when ( not missing(AGR6_MIN_CMAXA_DAYS) and AGR6_MIN_CMAXA_DAYS <= 9 ) do;
GRP_AGR6_MIN_CMAXA_DAYS  = 1 ;
end;
when ( 9 < AGR6_MIN_CMAXA_DAYS <= 11 ) do;
GRP_AGR6_MIN_CMAXA_DAYS  = 2 ;
end;
when ( 11 < AGR6_MIN_CMAXA_DAYS <= 13 ) do;
GRP_AGR6_MIN_CMAXA_DAYS  = 3 ;
end;
when ( 13 < AGR6_MIN_CMAXA_DAYS ) do;
GRP_AGR6_MIN_CMAXA_DAYS  = 4 ;
end;
when ( missing(AGR6_MIN_CMAXA_DAYS) ) do;
GRP_AGR6_MIN_CMAXA_DAYS  = 5 ;
end;
otherwise GRP_AGR6_MIN_CMAXA_DAYS  = 6 ; end;
select;
when ( not missing(AGR6_MIN_CMAXA_DUE) and AGR6_MIN_CMAXA_DUE <= 0 ) do;
GRP_AGR6_MIN_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGR6_MIN_CMAXA_DUE <= 1 ) do;
GRP_AGR6_MIN_CMAXA_DUE  = 2 ;
end;
when ( 1 < AGR6_MIN_CMAXA_DUE <= 3 ) do;
GRP_AGR6_MIN_CMAXA_DUE  = 3 ;
end;
when ( 3 < AGR6_MIN_CMAXA_DUE ) do;
GRP_AGR6_MIN_CMAXA_DUE  = 4 ;
end;
when ( missing(AGR6_MIN_CMAXA_DUE) ) do;
GRP_AGR6_MIN_CMAXA_DUE  = 5 ;
end;
otherwise GRP_AGR6_MIN_CMAXA_DUE  = 6 ; end;
select;
when ( not missing(AGR6_MIN_CMAXC_DAYS) and AGR6_MIN_CMAXC_DAYS <= 10 ) do;
GRP_AGR6_MIN_CMAXC_DAYS  = 1 ;
end;
when ( 10 < AGR6_MIN_CMAXC_DAYS ) do;
GRP_AGR6_MIN_CMAXC_DAYS  = 2 ;
end;
when ( missing(AGR6_MIN_CMAXC_DAYS) ) do;
GRP_AGR6_MIN_CMAXC_DAYS  = 3 ;
end;
otherwise GRP_AGR6_MIN_CMAXC_DAYS  = 4 ; end;
select;
when ( not missing(AGR6_MIN_CMAXC_DUE) and AGR6_MIN_CMAXC_DUE <= 0 ) do;
GRP_AGR6_MIN_CMAXC_DUE  = 1 ;
end;
when ( 0 < AGR6_MIN_CMAXC_DUE <= 3 ) do;
GRP_AGR6_MIN_CMAXC_DUE  = 2 ;
end;
when ( 3 < AGR6_MIN_CMAXC_DUE ) do;
GRP_AGR6_MIN_CMAXC_DUE  = 3 ;
end;
when ( missing(AGR6_MIN_CMAXC_DUE) ) do;
GRP_AGR6_MIN_CMAXC_DUE  = 4 ;
end;
otherwise GRP_AGR6_MIN_CMAXC_DUE  = 5 ; end;
select;
when ( not missing(AGR6_MIN_CMAXI_DAYS) and AGR6_MIN_CMAXI_DAYS <= 9 ) do;
GRP_AGR6_MIN_CMAXI_DAYS  = 1 ;
end;
when ( 9 < AGR6_MIN_CMAXI_DAYS ) do;
GRP_AGR6_MIN_CMAXI_DAYS  = 2 ;
end;
when ( missing(AGR6_MIN_CMAXI_DAYS) ) do;
GRP_AGR6_MIN_CMAXI_DAYS  = 3 ;
end;
otherwise GRP_AGR6_MIN_CMAXI_DAYS  = 4 ; end;
select;
when ( not missing(AGR6_MIN_CMAXI_DUE) ) do;
GRP_AGR6_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR6_MIN_CMAXI_DUE) ) do;
GRP_AGR6_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR6_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MAX_CMAXA_DAYS) and AGR9_MAX_CMAXA_DAYS <= 15 ) do;
GRP_AGR9_MAX_CMAXA_DAYS  = 1 ;
end;
when ( 15 < AGR9_MAX_CMAXA_DAYS ) do;
GRP_AGR9_MAX_CMAXA_DAYS  = 2 ;
end;
when ( missing(AGR9_MAX_CMAXA_DAYS) ) do;
GRP_AGR9_MAX_CMAXA_DAYS  = 3 ;
end;
otherwise GRP_AGR9_MAX_CMAXA_DAYS  = 4 ; end;
select;
when ( not missing(AGR9_MAX_CMAXA_DUE) and AGR9_MAX_CMAXA_DUE <= 0 ) do;
GRP_AGR9_MAX_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGR9_MAX_CMAXA_DUE <= 1 ) do;
GRP_AGR9_MAX_CMAXA_DUE  = 2 ;
end;
when ( 1 < AGR9_MAX_CMAXA_DUE <= 5 ) do;
GRP_AGR9_MAX_CMAXA_DUE  = 3 ;
end;
when ( 5 < AGR9_MAX_CMAXA_DUE ) do;
GRP_AGR9_MAX_CMAXA_DUE  = 4 ;
end;
when ( missing(AGR9_MAX_CMAXA_DUE) ) do;
GRP_AGR9_MAX_CMAXA_DUE  = 5 ;
end;
otherwise GRP_AGR9_MAX_CMAXA_DUE  = 6 ; end;
select;
when ( not missing(AGR9_MAX_CMAXC_DAYS) ) do;
GRP_AGR9_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR9_MAX_CMAXC_DAYS) ) do;
GRP_AGR9_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MAX_CMAXC_DUE) and AGR9_MAX_CMAXC_DUE <= 1 ) do;
GRP_AGR9_MAX_CMAXC_DUE  = 1 ;
end;
when ( 1 < AGR9_MAX_CMAXC_DUE <= 6 ) do;
GRP_AGR9_MAX_CMAXC_DUE  = 2 ;
end;
when ( 6 < AGR9_MAX_CMAXC_DUE ) do;
GRP_AGR9_MAX_CMAXC_DUE  = 3 ;
end;
when ( missing(AGR9_MAX_CMAXC_DUE) ) do;
GRP_AGR9_MAX_CMAXC_DUE  = 4 ;
end;
otherwise GRP_AGR9_MAX_CMAXC_DUE  = 5 ; end;
select;
when ( not missing(AGR9_MAX_CMAXI_DAYS) ) do;
GRP_AGR9_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR9_MAX_CMAXI_DAYS) ) do;
GRP_AGR9_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MAX_CMAXI_DUE) and AGR9_MAX_CMAXI_DUE <= 0 ) do;
GRP_AGR9_MAX_CMAXI_DUE  = 1 ;
end;
when ( 0 < AGR9_MAX_CMAXI_DUE ) do;
GRP_AGR9_MAX_CMAXI_DUE  = 2 ;
end;
when ( missing(AGR9_MAX_CMAXI_DUE) ) do;
GRP_AGR9_MAX_CMAXI_DUE  = 3 ;
end;
otherwise GRP_AGR9_MAX_CMAXI_DUE  = 4 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXA_DAYS) and AGR9_MEAN_CMAXA_DAYS <= 13 ) do;
GRP_AGR9_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( 13 < AGR9_MEAN_CMAXA_DAYS <= 13.777777778 ) do;
GRP_AGR9_MEAN_CMAXA_DAYS  = 2 ;
end;
when ( 13.777777778 < AGR9_MEAN_CMAXA_DAYS <= 14.555555556 ) do;
GRP_AGR9_MEAN_CMAXA_DAYS  = 3 ;
end;
when ( 14.555555556 < AGR9_MEAN_CMAXA_DAYS ) do;
GRP_AGR9_MEAN_CMAXA_DAYS  = 4 ;
end;
when ( missing(AGR9_MEAN_CMAXA_DAYS) ) do;
GRP_AGR9_MEAN_CMAXA_DAYS  = 5 ;
end;
otherwise GRP_AGR9_MEAN_CMAXA_DAYS  = 6 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXA_DUE) and AGR9_MEAN_CMAXA_DUE <= 0.4444444444 ) do;
GRP_AGR9_MEAN_CMAXA_DUE  = 1 ;
end;
when ( 0.4444444444 < AGR9_MEAN_CMAXA_DUE <= 2.4444444444 ) do;
GRP_AGR9_MEAN_CMAXA_DUE  = 2 ;
end;
when ( 2.4444444444 < AGR9_MEAN_CMAXA_DUE <= 4.1111111111 ) do;
GRP_AGR9_MEAN_CMAXA_DUE  = 3 ;
end;
when ( 4.1111111111 < AGR9_MEAN_CMAXA_DUE <= 5.7777777778 ) do;
GRP_AGR9_MEAN_CMAXA_DUE  = 4 ;
end;
when ( 5.7777777778 < AGR9_MEAN_CMAXA_DUE ) do;
GRP_AGR9_MEAN_CMAXA_DUE  = 5 ;
end;
when ( missing(AGR9_MEAN_CMAXA_DUE) ) do;
GRP_AGR9_MEAN_CMAXA_DUE  = 6 ;
end;
otherwise GRP_AGR9_MEAN_CMAXA_DUE  = 7 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXC_DAYS) and AGR9_MEAN_CMAXC_DAYS <= 13.777777778 ) do;
GRP_AGR9_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( 13.777777778 < AGR9_MEAN_CMAXC_DAYS ) do;
GRP_AGR9_MEAN_CMAXC_DAYS  = 2 ;
end;
when ( missing(AGR9_MEAN_CMAXC_DAYS) ) do;
GRP_AGR9_MEAN_CMAXC_DAYS  = 3 ;
end;
otherwise GRP_AGR9_MEAN_CMAXC_DAYS  = 4 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXC_DUE) and AGR9_MEAN_CMAXC_DUE <= 0.4444444444 ) do;
GRP_AGR9_MEAN_CMAXC_DUE  = 1 ;
end;
when ( 0.4444444444 < AGR9_MEAN_CMAXC_DUE <= 2.4444444444 ) do;
GRP_AGR9_MEAN_CMAXC_DUE  = 2 ;
end;
when ( 2.4444444444 < AGR9_MEAN_CMAXC_DUE <= 5.6666666667 ) do;
GRP_AGR9_MEAN_CMAXC_DUE  = 3 ;
end;
when ( 5.6666666667 < AGR9_MEAN_CMAXC_DUE ) do;
GRP_AGR9_MEAN_CMAXC_DUE  = 4 ;
end;
when ( missing(AGR9_MEAN_CMAXC_DUE) ) do;
GRP_AGR9_MEAN_CMAXC_DUE  = 5 ;
end;
otherwise GRP_AGR9_MEAN_CMAXC_DUE  = 6 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXI_DAYS) and AGR9_MEAN_CMAXI_DAYS <= 12.777777778 ) do;
GRP_AGR9_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( 12.777777778 < AGR9_MEAN_CMAXI_DAYS ) do;
GRP_AGR9_MEAN_CMAXI_DAYS  = 2 ;
end;
when ( missing(AGR9_MEAN_CMAXI_DAYS) ) do;
GRP_AGR9_MEAN_CMAXI_DAYS  = 3 ;
end;
otherwise GRP_AGR9_MEAN_CMAXI_DAYS  = 4 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXI_DUE) and AGR9_MEAN_CMAXI_DUE <= 0 ) do;
GRP_AGR9_MEAN_CMAXI_DUE  = 1 ;
end;
when ( 0 < AGR9_MEAN_CMAXI_DUE ) do;
GRP_AGR9_MEAN_CMAXI_DUE  = 2 ;
end;
when ( missing(AGR9_MEAN_CMAXI_DUE) ) do;
GRP_AGR9_MEAN_CMAXI_DUE  = 3 ;
end;
otherwise GRP_AGR9_MEAN_CMAXI_DUE  = 4 ; end;
select;
when ( not missing(AGR9_MIN_CMAXA_DAYS) and AGR9_MIN_CMAXA_DAYS <= 10 ) do;
GRP_AGR9_MIN_CMAXA_DAYS  = 1 ;
end;
when ( 10 < AGR9_MIN_CMAXA_DAYS <= 12 ) do;
GRP_AGR9_MIN_CMAXA_DAYS  = 2 ;
end;
when ( 12 < AGR9_MIN_CMAXA_DAYS ) do;
GRP_AGR9_MIN_CMAXA_DAYS  = 3 ;
end;
when ( missing(AGR9_MIN_CMAXA_DAYS) ) do;
GRP_AGR9_MIN_CMAXA_DAYS  = 4 ;
end;
otherwise GRP_AGR9_MIN_CMAXA_DAYS  = 5 ; end;
select;
when ( not missing(AGR9_MIN_CMAXA_DUE) and AGR9_MIN_CMAXA_DUE <= 0 ) do;
GRP_AGR9_MIN_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGR9_MIN_CMAXA_DUE <= 1 ) do;
GRP_AGR9_MIN_CMAXA_DUE  = 2 ;
end;
when ( 1 < AGR9_MIN_CMAXA_DUE <= 3 ) do;
GRP_AGR9_MIN_CMAXA_DUE  = 3 ;
end;
when ( 3 < AGR9_MIN_CMAXA_DUE ) do;
GRP_AGR9_MIN_CMAXA_DUE  = 4 ;
end;
when ( missing(AGR9_MIN_CMAXA_DUE) ) do;
GRP_AGR9_MIN_CMAXA_DUE  = 5 ;
end;
otherwise GRP_AGR9_MIN_CMAXA_DUE  = 6 ; end;
select;
when ( not missing(AGR9_MIN_CMAXC_DAYS) and AGR9_MIN_CMAXC_DAYS <= 11 ) do;
GRP_AGR9_MIN_CMAXC_DAYS  = 1 ;
end;
when ( 11 < AGR9_MIN_CMAXC_DAYS ) do;
GRP_AGR9_MIN_CMAXC_DAYS  = 2 ;
end;
when ( missing(AGR9_MIN_CMAXC_DAYS) ) do;
GRP_AGR9_MIN_CMAXC_DAYS  = 3 ;
end;
otherwise GRP_AGR9_MIN_CMAXC_DAYS  = 4 ; end;
select;
when ( not missing(AGR9_MIN_CMAXC_DUE) and AGR9_MIN_CMAXC_DUE <= 0 ) do;
GRP_AGR9_MIN_CMAXC_DUE  = 1 ;
end;
when ( 0 < AGR9_MIN_CMAXC_DUE <= 2 ) do;
GRP_AGR9_MIN_CMAXC_DUE  = 2 ;
end;
when ( 2 < AGR9_MIN_CMAXC_DUE ) do;
GRP_AGR9_MIN_CMAXC_DUE  = 3 ;
end;
when ( missing(AGR9_MIN_CMAXC_DUE) ) do;
GRP_AGR9_MIN_CMAXC_DUE  = 4 ;
end;
otherwise GRP_AGR9_MIN_CMAXC_DUE  = 5 ; end;
select;
when ( not missing(AGR9_MIN_CMAXI_DAYS) and AGR9_MIN_CMAXI_DAYS <= 8 ) do;
GRP_AGR9_MIN_CMAXI_DAYS  = 1 ;
end;
when ( 8 < AGR9_MIN_CMAXI_DAYS ) do;
GRP_AGR9_MIN_CMAXI_DAYS  = 2 ;
end;
when ( missing(AGR9_MIN_CMAXI_DAYS) ) do;
GRP_AGR9_MIN_CMAXI_DAYS  = 3 ;
end;
otherwise GRP_AGR9_MIN_CMAXI_DAYS  = 4 ; end;
select;
when ( not missing(AGR9_MIN_CMAXI_DUE) ) do;
GRP_AGR9_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR9_MIN_CMAXI_DUE) ) do;
GRP_AGR9_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR9_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS12_MAX_CMAXA_DAYS) and AGS12_MAX_CMAXA_DAYS <= 15 ) do;
GRP_AGS12_MAX_CMAXA_DAYS  = 1 ;
end;
when ( 15 < AGS12_MAX_CMAXA_DAYS <= 18 ) do;
GRP_AGS12_MAX_CMAXA_DAYS  = 2 ;
end;
when ( 18 < AGS12_MAX_CMAXA_DAYS ) do;
GRP_AGS12_MAX_CMAXA_DAYS  = 3 ;
end;
when ( missing(AGS12_MAX_CMAXA_DAYS) ) do;
GRP_AGS12_MAX_CMAXA_DAYS  = 4 ;
end;
otherwise GRP_AGS12_MAX_CMAXA_DAYS  = 5 ; end;
select;
when ( not missing(AGS12_MAX_CMAXA_DUE) and AGS12_MAX_CMAXA_DUE <= 0 ) do;
GRP_AGS12_MAX_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGS12_MAX_CMAXA_DUE <= 1 ) do;
GRP_AGS12_MAX_CMAXA_DUE  = 2 ;
end;
when ( 1 < AGS12_MAX_CMAXA_DUE <= 5 ) do;
GRP_AGS12_MAX_CMAXA_DUE  = 3 ;
end;
when ( 5 < AGS12_MAX_CMAXA_DUE ) do;
GRP_AGS12_MAX_CMAXA_DUE  = 4 ;
end;
when ( missing(AGS12_MAX_CMAXA_DUE) ) do;
GRP_AGS12_MAX_CMAXA_DUE  = 5 ;
end;
otherwise GRP_AGS12_MAX_CMAXA_DUE  = 6 ; end;
select;
when ( not missing(AGS12_MAX_CMAXC_DAYS) and AGS12_MAX_CMAXC_DAYS <= 16 ) do;
GRP_AGS12_MAX_CMAXC_DAYS  = 1 ;
end;
when ( 16 < AGS12_MAX_CMAXC_DAYS <= 19 ) do;
GRP_AGS12_MAX_CMAXC_DAYS  = 2 ;
end;
when ( 19 < AGS12_MAX_CMAXC_DAYS ) do;
GRP_AGS12_MAX_CMAXC_DAYS  = 3 ;
end;
when ( missing(AGS12_MAX_CMAXC_DAYS) ) do;
GRP_AGS12_MAX_CMAXC_DAYS  = 4 ;
end;
otherwise GRP_AGS12_MAX_CMAXC_DAYS  = 5 ; end;
select;
when ( not missing(AGS12_MAX_CMAXC_DUE) and AGS12_MAX_CMAXC_DUE <= 2 ) do;
GRP_AGS12_MAX_CMAXC_DUE  = 1 ;
end;
when ( 2 < AGS12_MAX_CMAXC_DUE ) do;
GRP_AGS12_MAX_CMAXC_DUE  = 2 ;
end;
when ( missing(AGS12_MAX_CMAXC_DUE) ) do;
GRP_AGS12_MAX_CMAXC_DUE  = 3 ;
end;
otherwise GRP_AGS12_MAX_CMAXC_DUE  = 4 ; end;
select;
when ( not missing(AGS12_MAX_CMAXI_DAYS) ) do;
GRP_AGS12_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS12_MAX_CMAXI_DAYS) ) do;
GRP_AGS12_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MAX_CMAXI_DUE) and AGS12_MAX_CMAXI_DUE <= 0 ) do;
GRP_AGS12_MAX_CMAXI_DUE  = 1 ;
end;
when ( 0 < AGS12_MAX_CMAXI_DUE ) do;
GRP_AGS12_MAX_CMAXI_DUE  = 2 ;
end;
when ( missing(AGS12_MAX_CMAXI_DUE) ) do;
GRP_AGS12_MAX_CMAXI_DUE  = 3 ;
end;
otherwise GRP_AGS12_MAX_CMAXI_DUE  = 4 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXA_DAYS) and AGS12_MEAN_CMAXA_DAYS <= 12.181818182 ) do;
GRP_AGS12_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( 12.181818182 < AGS12_MEAN_CMAXA_DAYS <= 14 ) do;
GRP_AGS12_MEAN_CMAXA_DAYS  = 2 ;
end;
when ( 14 < AGS12_MEAN_CMAXA_DAYS <= 14.571428571 ) do;
GRP_AGS12_MEAN_CMAXA_DAYS  = 3 ;
end;
when ( 14.571428571 < AGS12_MEAN_CMAXA_DAYS <= 15 ) do;
GRP_AGS12_MEAN_CMAXA_DAYS  = 4 ;
end;
when ( 15 < AGS12_MEAN_CMAXA_DAYS ) do;
GRP_AGS12_MEAN_CMAXA_DAYS  = 5 ;
end;
when ( missing(AGS12_MEAN_CMAXA_DAYS) ) do;
GRP_AGS12_MEAN_CMAXA_DAYS  = 6 ;
end;
otherwise GRP_AGS12_MEAN_CMAXA_DAYS  = 7 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXA_DUE) and AGS12_MEAN_CMAXA_DUE <= 0.4444444444 ) do;
GRP_AGS12_MEAN_CMAXA_DUE  = 1 ;
end;
when ( 0.4444444444 < AGS12_MEAN_CMAXA_DUE <= 2 ) do;
GRP_AGS12_MEAN_CMAXA_DUE  = 2 ;
end;
when ( 2 < AGS12_MEAN_CMAXA_DUE <= 3.7 ) do;
GRP_AGS12_MEAN_CMAXA_DUE  = 3 ;
end;
when ( 3.7 < AGS12_MEAN_CMAXA_DUE <= 5.3636363636 ) do;
GRP_AGS12_MEAN_CMAXA_DUE  = 4 ;
end;
when ( 5.3636363636 < AGS12_MEAN_CMAXA_DUE <= 6.2222222222 ) do;
GRP_AGS12_MEAN_CMAXA_DUE  = 5 ;
end;
when ( 6.2222222222 < AGS12_MEAN_CMAXA_DUE ) do;
GRP_AGS12_MEAN_CMAXA_DUE  = 6 ;
end;
when ( missing(AGS12_MEAN_CMAXA_DUE) ) do;
GRP_AGS12_MEAN_CMAXA_DUE  = 7 ;
end;
otherwise GRP_AGS12_MEAN_CMAXA_DUE  = 8 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXC_DAYS) and AGS12_MEAN_CMAXC_DAYS <= 12.714285714 ) do;
GRP_AGS12_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( 12.714285714 < AGS12_MEAN_CMAXC_DAYS <= 13.454545455 ) do;
GRP_AGS12_MEAN_CMAXC_DAYS  = 2 ;
end;
when ( 13.454545455 < AGS12_MEAN_CMAXC_DAYS <= 14.909090909 ) do;
GRP_AGS12_MEAN_CMAXC_DAYS  = 3 ;
end;
when ( 14.909090909 < AGS12_MEAN_CMAXC_DAYS <= 15 ) do;
GRP_AGS12_MEAN_CMAXC_DAYS  = 4 ;
end;
when ( 15 < AGS12_MEAN_CMAXC_DAYS ) do;
GRP_AGS12_MEAN_CMAXC_DAYS  = 5 ;
end;
when ( missing(AGS12_MEAN_CMAXC_DAYS) ) do;
GRP_AGS12_MEAN_CMAXC_DAYS  = 6 ;
end;
otherwise GRP_AGS12_MEAN_CMAXC_DAYS  = 7 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXC_DUE) and AGS12_MEAN_CMAXC_DUE <= 0.6363636364 ) do;
GRP_AGS12_MEAN_CMAXC_DUE  = 1 ;
end;
when ( 0.6363636364 < AGS12_MEAN_CMAXC_DUE <= 2.4444444444 ) do;
GRP_AGS12_MEAN_CMAXC_DUE  = 2 ;
end;
when ( 2.4444444444 < AGS12_MEAN_CMAXC_DUE <= 3.9090909091 ) do;
GRP_AGS12_MEAN_CMAXC_DUE  = 3 ;
end;
when ( 3.9090909091 < AGS12_MEAN_CMAXC_DUE <= 6.25 ) do;
GRP_AGS12_MEAN_CMAXC_DUE  = 4 ;
end;
when ( 6.25 < AGS12_MEAN_CMAXC_DUE ) do;
GRP_AGS12_MEAN_CMAXC_DUE  = 5 ;
end;
when ( missing(AGS12_MEAN_CMAXC_DUE) ) do;
GRP_AGS12_MEAN_CMAXC_DUE  = 6 ;
end;
otherwise GRP_AGS12_MEAN_CMAXC_DUE  = 7 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXI_DAYS) and AGS12_MEAN_CMAXI_DAYS <= 12 ) do;
GRP_AGS12_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( 12 < AGS12_MEAN_CMAXI_DAYS <= 13.3 ) do;
GRP_AGS12_MEAN_CMAXI_DAYS  = 2 ;
end;
when ( 13.3 < AGS12_MEAN_CMAXI_DAYS <= 13.833333333 ) do;
GRP_AGS12_MEAN_CMAXI_DAYS  = 3 ;
end;
when ( 13.833333333 < AGS12_MEAN_CMAXI_DAYS ) do;
GRP_AGS12_MEAN_CMAXI_DAYS  = 4 ;
end;
when ( missing(AGS12_MEAN_CMAXI_DAYS) ) do;
GRP_AGS12_MEAN_CMAXI_DAYS  = 5 ;
end;
otherwise GRP_AGS12_MEAN_CMAXI_DAYS  = 6 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXI_DUE) and AGS12_MEAN_CMAXI_DUE <= 0 ) do;
GRP_AGS12_MEAN_CMAXI_DUE  = 1 ;
end;
when ( 0 < AGS12_MEAN_CMAXI_DUE <= 0.6666666667 ) do;
GRP_AGS12_MEAN_CMAXI_DUE  = 2 ;
end;
when ( 0.6666666667 < AGS12_MEAN_CMAXI_DUE ) do;
GRP_AGS12_MEAN_CMAXI_DUE  = 3 ;
end;
when ( missing(AGS12_MEAN_CMAXI_DUE) ) do;
GRP_AGS12_MEAN_CMAXI_DUE  = 4 ;
end;
otherwise GRP_AGS12_MEAN_CMAXI_DUE  = 5 ; end;
select;
when ( not missing(AGS12_MIN_CMAXA_DAYS) and AGS12_MIN_CMAXA_DAYS <= 10 ) do;
GRP_AGS12_MIN_CMAXA_DAYS  = 1 ;
end;
when ( 10 < AGS12_MIN_CMAXA_DAYS <= 11 ) do;
GRP_AGS12_MIN_CMAXA_DAYS  = 2 ;
end;
when ( 11 < AGS12_MIN_CMAXA_DAYS <= 12 ) do;
GRP_AGS12_MIN_CMAXA_DAYS  = 3 ;
end;
when ( 12 < AGS12_MIN_CMAXA_DAYS <= 13 ) do;
GRP_AGS12_MIN_CMAXA_DAYS  = 4 ;
end;
when ( 13 < AGS12_MIN_CMAXA_DAYS ) do;
GRP_AGS12_MIN_CMAXA_DAYS  = 5 ;
end;
when ( missing(AGS12_MIN_CMAXA_DAYS) ) do;
GRP_AGS12_MIN_CMAXA_DAYS  = 6 ;
end;
otherwise GRP_AGS12_MIN_CMAXA_DAYS  = 7 ; end;
select;
when ( not missing(AGS12_MIN_CMAXA_DUE) and AGS12_MIN_CMAXA_DUE <= 0 ) do;
GRP_AGS12_MIN_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGS12_MIN_CMAXA_DUE <= 1 ) do;
GRP_AGS12_MIN_CMAXA_DUE  = 2 ;
end;
when ( 1 < AGS12_MIN_CMAXA_DUE <= 3 ) do;
GRP_AGS12_MIN_CMAXA_DUE  = 3 ;
end;
when ( 3 < AGS12_MIN_CMAXA_DUE ) do;
GRP_AGS12_MIN_CMAXA_DUE  = 4 ;
end;
when ( missing(AGS12_MIN_CMAXA_DUE) ) do;
GRP_AGS12_MIN_CMAXA_DUE  = 5 ;
end;
otherwise GRP_AGS12_MIN_CMAXA_DUE  = 6 ; end;
select;
when ( not missing(AGS12_MIN_CMAXC_DAYS) and AGS12_MIN_CMAXC_DAYS <= 8 ) do;
GRP_AGS12_MIN_CMAXC_DAYS  = 1 ;
end;
when ( 8 < AGS12_MIN_CMAXC_DAYS <= 11 ) do;
GRP_AGS12_MIN_CMAXC_DAYS  = 2 ;
end;
when ( 11 < AGS12_MIN_CMAXC_DAYS <= 14 ) do;
GRP_AGS12_MIN_CMAXC_DAYS  = 3 ;
end;
when ( 14 < AGS12_MIN_CMAXC_DAYS ) do;
GRP_AGS12_MIN_CMAXC_DAYS  = 4 ;
end;
when ( missing(AGS12_MIN_CMAXC_DAYS) ) do;
GRP_AGS12_MIN_CMAXC_DAYS  = 5 ;
end;
otherwise GRP_AGS12_MIN_CMAXC_DAYS  = 6 ; end;
select;
when ( not missing(AGS12_MIN_CMAXC_DUE) and AGS12_MIN_CMAXC_DUE <= 0 ) do;
GRP_AGS12_MIN_CMAXC_DUE  = 1 ;
end;
when ( 0 < AGS12_MIN_CMAXC_DUE <= 1 ) do;
GRP_AGS12_MIN_CMAXC_DUE  = 2 ;
end;
when ( 1 < AGS12_MIN_CMAXC_DUE <= 4 ) do;
GRP_AGS12_MIN_CMAXC_DUE  = 3 ;
end;
when ( 4 < AGS12_MIN_CMAXC_DUE ) do;
GRP_AGS12_MIN_CMAXC_DUE  = 4 ;
end;
when ( missing(AGS12_MIN_CMAXC_DUE) ) do;
GRP_AGS12_MIN_CMAXC_DUE  = 5 ;
end;
otherwise GRP_AGS12_MIN_CMAXC_DUE  = 6 ; end;
select;
when ( not missing(AGS12_MIN_CMAXI_DAYS) and AGS12_MIN_CMAXI_DAYS <= 7 ) do;
GRP_AGS12_MIN_CMAXI_DAYS  = 1 ;
end;
when ( 7 < AGS12_MIN_CMAXI_DAYS <= 9 ) do;
GRP_AGS12_MIN_CMAXI_DAYS  = 2 ;
end;
when ( 9 < AGS12_MIN_CMAXI_DAYS <= 10 ) do;
GRP_AGS12_MIN_CMAXI_DAYS  = 3 ;
end;
when ( 10 < AGS12_MIN_CMAXI_DAYS <= 12 ) do;
GRP_AGS12_MIN_CMAXI_DAYS  = 4 ;
end;
when ( 12 < AGS12_MIN_CMAXI_DAYS ) do;
GRP_AGS12_MIN_CMAXI_DAYS  = 5 ;
end;
when ( missing(AGS12_MIN_CMAXI_DAYS) ) do;
GRP_AGS12_MIN_CMAXI_DAYS  = 6 ;
end;
otherwise GRP_AGS12_MIN_CMAXI_DAYS  = 7 ; end;
select;
when ( not missing(AGS12_MIN_CMAXI_DUE) ) do;
GRP_AGS12_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS12_MIN_CMAXI_DUE) ) do;
GRP_AGS12_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS12_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MAX_CMAXA_DAYS) and AGS3_MAX_CMAXA_DAYS <= 14 ) do;
GRP_AGS3_MAX_CMAXA_DAYS  = 1 ;
end;
when ( 14 < AGS3_MAX_CMAXA_DAYS <= 15 ) do;
GRP_AGS3_MAX_CMAXA_DAYS  = 2 ;
end;
when ( 15 < AGS3_MAX_CMAXA_DAYS ) do;
GRP_AGS3_MAX_CMAXA_DAYS  = 3 ;
end;
when ( missing(AGS3_MAX_CMAXA_DAYS) ) do;
GRP_AGS3_MAX_CMAXA_DAYS  = 4 ;
end;
otherwise GRP_AGS3_MAX_CMAXA_DAYS  = 5 ; end;
select;
when ( not missing(AGS3_MAX_CMAXA_DUE) and AGS3_MAX_CMAXA_DUE <= 0 ) do;
GRP_AGS3_MAX_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGS3_MAX_CMAXA_DUE <= 3 ) do;
GRP_AGS3_MAX_CMAXA_DUE  = 2 ;
end;
when ( 3 < AGS3_MAX_CMAXA_DUE <= 6 ) do;
GRP_AGS3_MAX_CMAXA_DUE  = 3 ;
end;
when ( 6 < AGS3_MAX_CMAXA_DUE ) do;
GRP_AGS3_MAX_CMAXA_DUE  = 4 ;
end;
when ( missing(AGS3_MAX_CMAXA_DUE) ) do;
GRP_AGS3_MAX_CMAXA_DUE  = 5 ;
end;
otherwise GRP_AGS3_MAX_CMAXA_DUE  = 6 ; end;
select;
when ( not missing(AGS3_MAX_CMAXC_DAYS) and AGS3_MAX_CMAXC_DAYS <= 14 ) do;
GRP_AGS3_MAX_CMAXC_DAYS  = 1 ;
end;
when ( 14 < AGS3_MAX_CMAXC_DAYS ) do;
GRP_AGS3_MAX_CMAXC_DAYS  = 2 ;
end;
when ( missing(AGS3_MAX_CMAXC_DAYS) ) do;
GRP_AGS3_MAX_CMAXC_DAYS  = 3 ;
end;
otherwise GRP_AGS3_MAX_CMAXC_DAYS  = 4 ; end;
select;
when ( not missing(AGS3_MAX_CMAXC_DUE) and AGS3_MAX_CMAXC_DUE <= 0 ) do;
GRP_AGS3_MAX_CMAXC_DUE  = 1 ;
end;
when ( 0 < AGS3_MAX_CMAXC_DUE <= 3 ) do;
GRP_AGS3_MAX_CMAXC_DUE  = 2 ;
end;
when ( 3 < AGS3_MAX_CMAXC_DUE <= 6 ) do;
GRP_AGS3_MAX_CMAXC_DUE  = 3 ;
end;
when ( 6 < AGS3_MAX_CMAXC_DUE ) do;
GRP_AGS3_MAX_CMAXC_DUE  = 4 ;
end;
when ( missing(AGS3_MAX_CMAXC_DUE) ) do;
GRP_AGS3_MAX_CMAXC_DUE  = 5 ;
end;
otherwise GRP_AGS3_MAX_CMAXC_DUE  = 6 ; end;
select;
when ( not missing(AGS3_MAX_CMAXI_DAYS) and AGS3_MAX_CMAXI_DAYS <= 14 ) do;
GRP_AGS3_MAX_CMAXI_DAYS  = 1 ;
end;
when ( 14 < AGS3_MAX_CMAXI_DAYS ) do;
GRP_AGS3_MAX_CMAXI_DAYS  = 2 ;
end;
when ( missing(AGS3_MAX_CMAXI_DAYS) ) do;
GRP_AGS3_MAX_CMAXI_DAYS  = 3 ;
end;
otherwise GRP_AGS3_MAX_CMAXI_DAYS  = 4 ; end;
select;
when ( not missing(AGS3_MAX_CMAXI_DUE) and AGS3_MAX_CMAXI_DUE <= 0 ) do;
GRP_AGS3_MAX_CMAXI_DUE  = 1 ;
end;
when ( 0 < AGS3_MAX_CMAXI_DUE ) do;
GRP_AGS3_MAX_CMAXI_DUE  = 2 ;
end;
when ( missing(AGS3_MAX_CMAXI_DUE) ) do;
GRP_AGS3_MAX_CMAXI_DUE  = 3 ;
end;
otherwise GRP_AGS3_MAX_CMAXI_DUE  = 4 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXA_DAYS) and AGS3_MEAN_CMAXA_DAYS <= 12.666666667 ) do;
GRP_AGS3_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( 12.666666667 < AGS3_MEAN_CMAXA_DAYS <= 14 ) do;
GRP_AGS3_MEAN_CMAXA_DAYS  = 2 ;
end;
when ( 14 < AGS3_MEAN_CMAXA_DAYS <= 14.666666667 ) do;
GRP_AGS3_MEAN_CMAXA_DAYS  = 3 ;
end;
when ( 14.666666667 < AGS3_MEAN_CMAXA_DAYS ) do;
GRP_AGS3_MEAN_CMAXA_DAYS  = 4 ;
end;
when ( missing(AGS3_MEAN_CMAXA_DAYS) ) do;
GRP_AGS3_MEAN_CMAXA_DAYS  = 5 ;
end;
otherwise GRP_AGS3_MEAN_CMAXA_DAYS  = 6 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXA_DUE) and AGS3_MEAN_CMAXA_DUE <= 0 ) do;
GRP_AGS3_MEAN_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGS3_MEAN_CMAXA_DUE <= 2.3333333333 ) do;
GRP_AGS3_MEAN_CMAXA_DUE  = 2 ;
end;
when ( 2.3333333333 < AGS3_MEAN_CMAXA_DUE <= 4.6666666667 ) do;
GRP_AGS3_MEAN_CMAXA_DUE  = 3 ;
end;
when ( 4.6666666667 < AGS3_MEAN_CMAXA_DUE <= 6.3333333333 ) do;
GRP_AGS3_MEAN_CMAXA_DUE  = 4 ;
end;
when ( 6.3333333333 < AGS3_MEAN_CMAXA_DUE ) do;
GRP_AGS3_MEAN_CMAXA_DUE  = 5 ;
end;
when ( missing(AGS3_MEAN_CMAXA_DUE) ) do;
GRP_AGS3_MEAN_CMAXA_DUE  = 6 ;
end;
otherwise GRP_AGS3_MEAN_CMAXA_DUE  = 7 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXC_DAYS) and AGS3_MEAN_CMAXC_DAYS <= 12.666666667 ) do;
GRP_AGS3_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( 12.666666667 < AGS3_MEAN_CMAXC_DAYS <= 14 ) do;
GRP_AGS3_MEAN_CMAXC_DAYS  = 2 ;
end;
when ( 14 < AGS3_MEAN_CMAXC_DAYS <= 14.666666667 ) do;
GRP_AGS3_MEAN_CMAXC_DAYS  = 3 ;
end;
when ( 14.666666667 < AGS3_MEAN_CMAXC_DAYS ) do;
GRP_AGS3_MEAN_CMAXC_DAYS  = 4 ;
end;
when ( missing(AGS3_MEAN_CMAXC_DAYS) ) do;
GRP_AGS3_MEAN_CMAXC_DAYS  = 5 ;
end;
otherwise GRP_AGS3_MEAN_CMAXC_DAYS  = 6 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXC_DUE) and AGS3_MEAN_CMAXC_DUE <= 0.6666666667 ) do;
GRP_AGS3_MEAN_CMAXC_DUE  = 1 ;
end;
when ( 0.6666666667 < AGS3_MEAN_CMAXC_DUE <= 2 ) do;
GRP_AGS3_MEAN_CMAXC_DUE  = 2 ;
end;
when ( 2 < AGS3_MEAN_CMAXC_DUE <= 6.3333333333 ) do;
GRP_AGS3_MEAN_CMAXC_DUE  = 3 ;
end;
when ( 6.3333333333 < AGS3_MEAN_CMAXC_DUE ) do;
GRP_AGS3_MEAN_CMAXC_DUE  = 4 ;
end;
when ( missing(AGS3_MEAN_CMAXC_DUE) ) do;
GRP_AGS3_MEAN_CMAXC_DUE  = 5 ;
end;
otherwise GRP_AGS3_MEAN_CMAXC_DUE  = 6 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXI_DAYS) and AGS3_MEAN_CMAXI_DAYS <= 12 ) do;
GRP_AGS3_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( 12 < AGS3_MEAN_CMAXI_DAYS <= 13 ) do;
GRP_AGS3_MEAN_CMAXI_DAYS  = 2 ;
end;
when ( 13 < AGS3_MEAN_CMAXI_DAYS <= 13.666666667 ) do;
GRP_AGS3_MEAN_CMAXI_DAYS  = 3 ;
end;
when ( 13.666666667 < AGS3_MEAN_CMAXI_DAYS ) do;
GRP_AGS3_MEAN_CMAXI_DAYS  = 4 ;
end;
when ( missing(AGS3_MEAN_CMAXI_DAYS) ) do;
GRP_AGS3_MEAN_CMAXI_DAYS  = 5 ;
end;
otherwise GRP_AGS3_MEAN_CMAXI_DAYS  = 6 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXI_DUE) and AGS3_MEAN_CMAXI_DUE <= 0 ) do;
GRP_AGS3_MEAN_CMAXI_DUE  = 1 ;
end;
when ( 0 < AGS3_MEAN_CMAXI_DUE ) do;
GRP_AGS3_MEAN_CMAXI_DUE  = 2 ;
end;
when ( missing(AGS3_MEAN_CMAXI_DUE) ) do;
GRP_AGS3_MEAN_CMAXI_DUE  = 3 ;
end;
otherwise GRP_AGS3_MEAN_CMAXI_DUE  = 4 ; end;
select;
when ( not missing(AGS3_MIN_CMAXA_DAYS) and AGS3_MIN_CMAXA_DAYS <= 9 ) do;
GRP_AGS3_MIN_CMAXA_DAYS  = 1 ;
end;
when ( 9 < AGS3_MIN_CMAXA_DAYS <= 12 ) do;
GRP_AGS3_MIN_CMAXA_DAYS  = 2 ;
end;
when ( 12 < AGS3_MIN_CMAXA_DAYS <= 13 ) do;
GRP_AGS3_MIN_CMAXA_DAYS  = 3 ;
end;
when ( 13 < AGS3_MIN_CMAXA_DAYS <= 14 ) do;
GRP_AGS3_MIN_CMAXA_DAYS  = 4 ;
end;
when ( 14 < AGS3_MIN_CMAXA_DAYS ) do;
GRP_AGS3_MIN_CMAXA_DAYS  = 5 ;
end;
when ( missing(AGS3_MIN_CMAXA_DAYS) ) do;
GRP_AGS3_MIN_CMAXA_DAYS  = 6 ;
end;
otherwise GRP_AGS3_MIN_CMAXA_DAYS  = 7 ; end;
select;
when ( not missing(AGS3_MIN_CMAXA_DUE) and AGS3_MIN_CMAXA_DUE <= 0 ) do;
GRP_AGS3_MIN_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGS3_MIN_CMAXA_DUE <= 1 ) do;
GRP_AGS3_MIN_CMAXA_DUE  = 2 ;
end;
when ( 1 < AGS3_MIN_CMAXA_DUE <= 3 ) do;
GRP_AGS3_MIN_CMAXA_DUE  = 3 ;
end;
when ( 3 < AGS3_MIN_CMAXA_DUE <= 5 ) do;
GRP_AGS3_MIN_CMAXA_DUE  = 4 ;
end;
when ( 5 < AGS3_MIN_CMAXA_DUE ) do;
GRP_AGS3_MIN_CMAXA_DUE  = 5 ;
end;
when ( missing(AGS3_MIN_CMAXA_DUE) ) do;
GRP_AGS3_MIN_CMAXA_DUE  = 6 ;
end;
otherwise GRP_AGS3_MIN_CMAXA_DUE  = 7 ; end;
select;
when ( not missing(AGS3_MIN_CMAXC_DAYS) and AGS3_MIN_CMAXC_DAYS <= 11 ) do;
GRP_AGS3_MIN_CMAXC_DAYS  = 1 ;
end;
when ( 11 < AGS3_MIN_CMAXC_DAYS <= 13 ) do;
GRP_AGS3_MIN_CMAXC_DAYS  = 2 ;
end;
when ( 13 < AGS3_MIN_CMAXC_DAYS <= 14 ) do;
GRP_AGS3_MIN_CMAXC_DAYS  = 3 ;
end;
when ( 14 < AGS3_MIN_CMAXC_DAYS ) do;
GRP_AGS3_MIN_CMAXC_DAYS  = 4 ;
end;
when ( missing(AGS3_MIN_CMAXC_DAYS) ) do;
GRP_AGS3_MIN_CMAXC_DAYS  = 5 ;
end;
otherwise GRP_AGS3_MIN_CMAXC_DAYS  = 6 ; end;
select;
when ( not missing(AGS3_MIN_CMAXC_DUE) and AGS3_MIN_CMAXC_DUE <= 0 ) do;
GRP_AGS3_MIN_CMAXC_DUE  = 1 ;
end;
when ( 0 < AGS3_MIN_CMAXC_DUE <= 3 ) do;
GRP_AGS3_MIN_CMAXC_DUE  = 2 ;
end;
when ( 3 < AGS3_MIN_CMAXC_DUE <= 5 ) do;
GRP_AGS3_MIN_CMAXC_DUE  = 3 ;
end;
when ( 5 < AGS3_MIN_CMAXC_DUE ) do;
GRP_AGS3_MIN_CMAXC_DUE  = 4 ;
end;
when ( missing(AGS3_MIN_CMAXC_DUE) ) do;
GRP_AGS3_MIN_CMAXC_DUE  = 5 ;
end;
otherwise GRP_AGS3_MIN_CMAXC_DUE  = 6 ; end;
select;
when ( not missing(AGS3_MIN_CMAXI_DAYS) and AGS3_MIN_CMAXI_DAYS <= 10 ) do;
GRP_AGS3_MIN_CMAXI_DAYS  = 1 ;
end;
when ( 10 < AGS3_MIN_CMAXI_DAYS <= 12 ) do;
GRP_AGS3_MIN_CMAXI_DAYS  = 2 ;
end;
when ( 12 < AGS3_MIN_CMAXI_DAYS ) do;
GRP_AGS3_MIN_CMAXI_DAYS  = 3 ;
end;
when ( missing(AGS3_MIN_CMAXI_DAYS) ) do;
GRP_AGS3_MIN_CMAXI_DAYS  = 4 ;
end;
otherwise GRP_AGS3_MIN_CMAXI_DAYS  = 5 ; end;
select;
when ( not missing(AGS3_MIN_CMAXI_DUE) ) do;
GRP_AGS3_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS3_MIN_CMAXI_DUE) ) do;
GRP_AGS3_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS3_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MAX_CMAXA_DAYS) and AGS6_MAX_CMAXA_DAYS <= 15 ) do;
GRP_AGS6_MAX_CMAXA_DAYS  = 1 ;
end;
when ( 15 < AGS6_MAX_CMAXA_DAYS ) do;
GRP_AGS6_MAX_CMAXA_DAYS  = 2 ;
end;
when ( missing(AGS6_MAX_CMAXA_DAYS) ) do;
GRP_AGS6_MAX_CMAXA_DAYS  = 3 ;
end;
otherwise GRP_AGS6_MAX_CMAXA_DAYS  = 4 ; end;
select;
when ( not missing(AGS6_MAX_CMAXA_DUE) and AGS6_MAX_CMAXA_DUE <= 0 ) do;
GRP_AGS6_MAX_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGS6_MAX_CMAXA_DUE <= 3 ) do;
GRP_AGS6_MAX_CMAXA_DUE  = 2 ;
end;
when ( 3 < AGS6_MAX_CMAXA_DUE ) do;
GRP_AGS6_MAX_CMAXA_DUE  = 3 ;
end;
when ( missing(AGS6_MAX_CMAXA_DUE) ) do;
GRP_AGS6_MAX_CMAXA_DUE  = 4 ;
end;
otherwise GRP_AGS6_MAX_CMAXA_DUE  = 5 ; end;
select;
when ( not missing(AGS6_MAX_CMAXC_DAYS) and AGS6_MAX_CMAXC_DAYS <= 16 ) do;
GRP_AGS6_MAX_CMAXC_DAYS  = 1 ;
end;
when ( 16 < AGS6_MAX_CMAXC_DAYS ) do;
GRP_AGS6_MAX_CMAXC_DAYS  = 2 ;
end;
when ( missing(AGS6_MAX_CMAXC_DAYS) ) do;
GRP_AGS6_MAX_CMAXC_DAYS  = 3 ;
end;
otherwise GRP_AGS6_MAX_CMAXC_DAYS  = 4 ; end;
select;
when ( not missing(AGS6_MAX_CMAXC_DUE) and AGS6_MAX_CMAXC_DUE <= 3 ) do;
GRP_AGS6_MAX_CMAXC_DUE  = 1 ;
end;
when ( 3 < AGS6_MAX_CMAXC_DUE ) do;
GRP_AGS6_MAX_CMAXC_DUE  = 2 ;
end;
when ( missing(AGS6_MAX_CMAXC_DUE) ) do;
GRP_AGS6_MAX_CMAXC_DUE  = 3 ;
end;
otherwise GRP_AGS6_MAX_CMAXC_DUE  = 4 ; end;
select;
when ( not missing(AGS6_MAX_CMAXI_DAYS) and AGS6_MAX_CMAXI_DAYS <= 14 ) do;
GRP_AGS6_MAX_CMAXI_DAYS  = 1 ;
end;
when ( 14 < AGS6_MAX_CMAXI_DAYS ) do;
GRP_AGS6_MAX_CMAXI_DAYS  = 2 ;
end;
when ( missing(AGS6_MAX_CMAXI_DAYS) ) do;
GRP_AGS6_MAX_CMAXI_DAYS  = 3 ;
end;
otherwise GRP_AGS6_MAX_CMAXI_DAYS  = 4 ; end;
select;
when ( not missing(AGS6_MAX_CMAXI_DUE) and AGS6_MAX_CMAXI_DUE <= 0 ) do;
GRP_AGS6_MAX_CMAXI_DUE  = 1 ;
end;
when ( 0 < AGS6_MAX_CMAXI_DUE ) do;
GRP_AGS6_MAX_CMAXI_DUE  = 2 ;
end;
when ( missing(AGS6_MAX_CMAXI_DUE) ) do;
GRP_AGS6_MAX_CMAXI_DUE  = 3 ;
end;
otherwise GRP_AGS6_MAX_CMAXI_DUE  = 4 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXA_DAYS) and AGS6_MEAN_CMAXA_DAYS <= 13 ) do;
GRP_AGS6_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( 13 < AGS6_MEAN_CMAXA_DAYS <= 13.75 ) do;
GRP_AGS6_MEAN_CMAXA_DAYS  = 2 ;
end;
when ( 13.75 < AGS6_MEAN_CMAXA_DAYS <= 14.8 ) do;
GRP_AGS6_MEAN_CMAXA_DAYS  = 3 ;
end;
when ( 14.8 < AGS6_MEAN_CMAXA_DAYS <= 15 ) do;
GRP_AGS6_MEAN_CMAXA_DAYS  = 4 ;
end;
when ( 15 < AGS6_MEAN_CMAXA_DAYS ) do;
GRP_AGS6_MEAN_CMAXA_DAYS  = 5 ;
end;
when ( missing(AGS6_MEAN_CMAXA_DAYS) ) do;
GRP_AGS6_MEAN_CMAXA_DAYS  = 6 ;
end;
otherwise GRP_AGS6_MEAN_CMAXA_DAYS  = 7 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXA_DUE) and AGS6_MEAN_CMAXA_DUE <= 0.25 ) do;
GRP_AGS6_MEAN_CMAXA_DUE  = 1 ;
end;
when ( 0.25 < AGS6_MEAN_CMAXA_DUE <= 2 ) do;
GRP_AGS6_MEAN_CMAXA_DUE  = 2 ;
end;
when ( 2 < AGS6_MEAN_CMAXA_DUE <= 5.3333333333 ) do;
GRP_AGS6_MEAN_CMAXA_DUE  = 3 ;
end;
when ( 5.3333333333 < AGS6_MEAN_CMAXA_DUE <= 5.8333333333 ) do;
GRP_AGS6_MEAN_CMAXA_DUE  = 4 ;
end;
when ( 5.8333333333 < AGS6_MEAN_CMAXA_DUE ) do;
GRP_AGS6_MEAN_CMAXA_DUE  = 5 ;
end;
when ( missing(AGS6_MEAN_CMAXA_DUE) ) do;
GRP_AGS6_MEAN_CMAXA_DUE  = 6 ;
end;
otherwise GRP_AGS6_MEAN_CMAXA_DUE  = 7 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXC_DAYS) and AGS6_MEAN_CMAXC_DAYS <= 13.333333333 ) do;
GRP_AGS6_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( 13.333333333 < AGS6_MEAN_CMAXC_DAYS <= 14.75 ) do;
GRP_AGS6_MEAN_CMAXC_DAYS  = 2 ;
end;
when ( 14.75 < AGS6_MEAN_CMAXC_DAYS <= 15 ) do;
GRP_AGS6_MEAN_CMAXC_DAYS  = 3 ;
end;
when ( 15 < AGS6_MEAN_CMAXC_DAYS ) do;
GRP_AGS6_MEAN_CMAXC_DAYS  = 4 ;
end;
when ( missing(AGS6_MEAN_CMAXC_DAYS) ) do;
GRP_AGS6_MEAN_CMAXC_DAYS  = 5 ;
end;
otherwise GRP_AGS6_MEAN_CMAXC_DAYS  = 6 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXC_DUE) and AGS6_MEAN_CMAXC_DUE <= 0.25 ) do;
GRP_AGS6_MEAN_CMAXC_DUE  = 1 ;
end;
when ( 0.25 < AGS6_MEAN_CMAXC_DUE <= 1 ) do;
GRP_AGS6_MEAN_CMAXC_DUE  = 2 ;
end;
when ( 1 < AGS6_MEAN_CMAXC_DUE <= 3.6666666667 ) do;
GRP_AGS6_MEAN_CMAXC_DUE  = 3 ;
end;
when ( 3.6666666667 < AGS6_MEAN_CMAXC_DUE <= 6.3333333333 ) do;
GRP_AGS6_MEAN_CMAXC_DUE  = 4 ;
end;
when ( 6.3333333333 < AGS6_MEAN_CMAXC_DUE ) do;
GRP_AGS6_MEAN_CMAXC_DUE  = 5 ;
end;
when ( missing(AGS6_MEAN_CMAXC_DUE) ) do;
GRP_AGS6_MEAN_CMAXC_DUE  = 6 ;
end;
otherwise GRP_AGS6_MEAN_CMAXC_DUE  = 7 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXI_DAYS) and AGS6_MEAN_CMAXI_DAYS <= 12.833333333 ) do;
GRP_AGS6_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( 12.833333333 < AGS6_MEAN_CMAXI_DAYS <= 13.4 ) do;
GRP_AGS6_MEAN_CMAXI_DAYS  = 2 ;
end;
when ( 13.4 < AGS6_MEAN_CMAXI_DAYS ) do;
GRP_AGS6_MEAN_CMAXI_DAYS  = 3 ;
end;
when ( missing(AGS6_MEAN_CMAXI_DAYS) ) do;
GRP_AGS6_MEAN_CMAXI_DAYS  = 4 ;
end;
otherwise GRP_AGS6_MEAN_CMAXI_DAYS  = 5 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXI_DUE) and AGS6_MEAN_CMAXI_DUE <= 0 ) do;
GRP_AGS6_MEAN_CMAXI_DUE  = 1 ;
end;
when ( 0 < AGS6_MEAN_CMAXI_DUE ) do;
GRP_AGS6_MEAN_CMAXI_DUE  = 2 ;
end;
when ( missing(AGS6_MEAN_CMAXI_DUE) ) do;
GRP_AGS6_MEAN_CMAXI_DUE  = 3 ;
end;
otherwise GRP_AGS6_MEAN_CMAXI_DUE  = 4 ; end;
select;
when ( not missing(AGS6_MIN_CMAXA_DAYS) and AGS6_MIN_CMAXA_DAYS <= 11 ) do;
GRP_AGS6_MIN_CMAXA_DAYS  = 1 ;
end;
when ( 11 < AGS6_MIN_CMAXA_DAYS <= 12 ) do;
GRP_AGS6_MIN_CMAXA_DAYS  = 2 ;
end;
when ( 12 < AGS6_MIN_CMAXA_DAYS <= 13 ) do;
GRP_AGS6_MIN_CMAXA_DAYS  = 3 ;
end;
when ( 13 < AGS6_MIN_CMAXA_DAYS <= 14 ) do;
GRP_AGS6_MIN_CMAXA_DAYS  = 4 ;
end;
when ( 14 < AGS6_MIN_CMAXA_DAYS ) do;
GRP_AGS6_MIN_CMAXA_DAYS  = 5 ;
end;
when ( missing(AGS6_MIN_CMAXA_DAYS) ) do;
GRP_AGS6_MIN_CMAXA_DAYS  = 6 ;
end;
otherwise GRP_AGS6_MIN_CMAXA_DAYS  = 7 ; end;
select;
when ( not missing(AGS6_MIN_CMAXA_DUE) and AGS6_MIN_CMAXA_DUE <= 0 ) do;
GRP_AGS6_MIN_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGS6_MIN_CMAXA_DUE <= 1 ) do;
GRP_AGS6_MIN_CMAXA_DUE  = 2 ;
end;
when ( 1 < AGS6_MIN_CMAXA_DUE <= 3 ) do;
GRP_AGS6_MIN_CMAXA_DUE  = 3 ;
end;
when ( 3 < AGS6_MIN_CMAXA_DUE ) do;
GRP_AGS6_MIN_CMAXA_DUE  = 4 ;
end;
when ( missing(AGS6_MIN_CMAXA_DUE) ) do;
GRP_AGS6_MIN_CMAXA_DUE  = 5 ;
end;
otherwise GRP_AGS6_MIN_CMAXA_DUE  = 6 ; end;
select;
when ( not missing(AGS6_MIN_CMAXC_DAYS) and AGS6_MIN_CMAXC_DAYS <= 9 ) do;
GRP_AGS6_MIN_CMAXC_DAYS  = 1 ;
end;
when ( 9 < AGS6_MIN_CMAXC_DAYS <= 11 ) do;
GRP_AGS6_MIN_CMAXC_DAYS  = 2 ;
end;
when ( 11 < AGS6_MIN_CMAXC_DAYS <= 14 ) do;
GRP_AGS6_MIN_CMAXC_DAYS  = 3 ;
end;
when ( 14 < AGS6_MIN_CMAXC_DAYS ) do;
GRP_AGS6_MIN_CMAXC_DAYS  = 4 ;
end;
when ( missing(AGS6_MIN_CMAXC_DAYS) ) do;
GRP_AGS6_MIN_CMAXC_DAYS  = 5 ;
end;
otherwise GRP_AGS6_MIN_CMAXC_DAYS  = 6 ; end;
select;
when ( not missing(AGS6_MIN_CMAXC_DUE) and AGS6_MIN_CMAXC_DUE <= 0 ) do;
GRP_AGS6_MIN_CMAXC_DUE  = 1 ;
end;
when ( 0 < AGS6_MIN_CMAXC_DUE <= 3 ) do;
GRP_AGS6_MIN_CMAXC_DUE  = 2 ;
end;
when ( 3 < AGS6_MIN_CMAXC_DUE ) do;
GRP_AGS6_MIN_CMAXC_DUE  = 3 ;
end;
when ( missing(AGS6_MIN_CMAXC_DUE) ) do;
GRP_AGS6_MIN_CMAXC_DUE  = 4 ;
end;
otherwise GRP_AGS6_MIN_CMAXC_DUE  = 5 ; end;
select;
when ( not missing(AGS6_MIN_CMAXI_DAYS) and AGS6_MIN_CMAXI_DAYS <= 10 ) do;
GRP_AGS6_MIN_CMAXI_DAYS  = 1 ;
end;
when ( 10 < AGS6_MIN_CMAXI_DAYS <= 12 ) do;
GRP_AGS6_MIN_CMAXI_DAYS  = 2 ;
end;
when ( 12 < AGS6_MIN_CMAXI_DAYS ) do;
GRP_AGS6_MIN_CMAXI_DAYS  = 3 ;
end;
when ( missing(AGS6_MIN_CMAXI_DAYS) ) do;
GRP_AGS6_MIN_CMAXI_DAYS  = 4 ;
end;
otherwise GRP_AGS6_MIN_CMAXI_DAYS  = 5 ; end;
select;
when ( not missing(AGS6_MIN_CMAXI_DUE) ) do;
GRP_AGS6_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS6_MIN_CMAXI_DUE) ) do;
GRP_AGS6_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS6_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MAX_CMAXA_DAYS) and AGS9_MAX_CMAXA_DAYS <= 15 ) do;
GRP_AGS9_MAX_CMAXA_DAYS  = 1 ;
end;
when ( 15 < AGS9_MAX_CMAXA_DAYS <= 18 ) do;
GRP_AGS9_MAX_CMAXA_DAYS  = 2 ;
end;
when ( 18 < AGS9_MAX_CMAXA_DAYS ) do;
GRP_AGS9_MAX_CMAXA_DAYS  = 3 ;
end;
when ( missing(AGS9_MAX_CMAXA_DAYS) ) do;
GRP_AGS9_MAX_CMAXA_DAYS  = 4 ;
end;
otherwise GRP_AGS9_MAX_CMAXA_DAYS  = 5 ; end;
select;
when ( not missing(AGS9_MAX_CMAXA_DUE) and AGS9_MAX_CMAXA_DUE <= 0 ) do;
GRP_AGS9_MAX_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGS9_MAX_CMAXA_DUE <= 1 ) do;
GRP_AGS9_MAX_CMAXA_DUE  = 2 ;
end;
when ( 1 < AGS9_MAX_CMAXA_DUE <= 5 ) do;
GRP_AGS9_MAX_CMAXA_DUE  = 3 ;
end;
when ( 5 < AGS9_MAX_CMAXA_DUE ) do;
GRP_AGS9_MAX_CMAXA_DUE  = 4 ;
end;
when ( missing(AGS9_MAX_CMAXA_DUE) ) do;
GRP_AGS9_MAX_CMAXA_DUE  = 5 ;
end;
otherwise GRP_AGS9_MAX_CMAXA_DUE  = 6 ; end;
select;
when ( not missing(AGS9_MAX_CMAXC_DAYS) and AGS9_MAX_CMAXC_DAYS <= 16 ) do;
GRP_AGS9_MAX_CMAXC_DAYS  = 1 ;
end;
when ( 16 < AGS9_MAX_CMAXC_DAYS ) do;
GRP_AGS9_MAX_CMAXC_DAYS  = 2 ;
end;
when ( missing(AGS9_MAX_CMAXC_DAYS) ) do;
GRP_AGS9_MAX_CMAXC_DAYS  = 3 ;
end;
otherwise GRP_AGS9_MAX_CMAXC_DAYS  = 4 ; end;
select;
when ( not missing(AGS9_MAX_CMAXC_DUE) and AGS9_MAX_CMAXC_DUE <= 2 ) do;
GRP_AGS9_MAX_CMAXC_DUE  = 1 ;
end;
when ( 2 < AGS9_MAX_CMAXC_DUE ) do;
GRP_AGS9_MAX_CMAXC_DUE  = 2 ;
end;
when ( missing(AGS9_MAX_CMAXC_DUE) ) do;
GRP_AGS9_MAX_CMAXC_DUE  = 3 ;
end;
otherwise GRP_AGS9_MAX_CMAXC_DUE  = 4 ; end;
select;
when ( not missing(AGS9_MAX_CMAXI_DAYS) ) do;
GRP_AGS9_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS9_MAX_CMAXI_DAYS) ) do;
GRP_AGS9_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MAX_CMAXI_DUE) and AGS9_MAX_CMAXI_DUE <= 0 ) do;
GRP_AGS9_MAX_CMAXI_DUE  = 1 ;
end;
when ( 0 < AGS9_MAX_CMAXI_DUE ) do;
GRP_AGS9_MAX_CMAXI_DUE  = 2 ;
end;
when ( missing(AGS9_MAX_CMAXI_DUE) ) do;
GRP_AGS9_MAX_CMAXI_DUE  = 3 ;
end;
otherwise GRP_AGS9_MAX_CMAXI_DUE  = 4 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXA_DAYS) and AGS9_MEAN_CMAXA_DAYS <= 12.444444444 ) do;
GRP_AGS9_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( 12.444444444 < AGS9_MEAN_CMAXA_DAYS <= 13.857142857 ) do;
GRP_AGS9_MEAN_CMAXA_DAYS  = 2 ;
end;
when ( 13.857142857 < AGS9_MEAN_CMAXA_DAYS <= 14.285714286 ) do;
GRP_AGS9_MEAN_CMAXA_DAYS  = 3 ;
end;
when ( 14.285714286 < AGS9_MEAN_CMAXA_DAYS <= 14.888888889 ) do;
GRP_AGS9_MEAN_CMAXA_DAYS  = 4 ;
end;
when ( 14.888888889 < AGS9_MEAN_CMAXA_DAYS ) do;
GRP_AGS9_MEAN_CMAXA_DAYS  = 5 ;
end;
when ( missing(AGS9_MEAN_CMAXA_DAYS) ) do;
GRP_AGS9_MEAN_CMAXA_DAYS  = 6 ;
end;
otherwise GRP_AGS9_MEAN_CMAXA_DAYS  = 7 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXA_DUE) and AGS9_MEAN_CMAXA_DUE <= 0.4285714286 ) do;
GRP_AGS9_MEAN_CMAXA_DUE  = 1 ;
end;
when ( 0.4285714286 < AGS9_MEAN_CMAXA_DUE <= 1 ) do;
GRP_AGS9_MEAN_CMAXA_DUE  = 2 ;
end;
when ( 1 < AGS9_MEAN_CMAXA_DUE <= 4.1111111111 ) do;
GRP_AGS9_MEAN_CMAXA_DUE  = 3 ;
end;
when ( 4.1111111111 < AGS9_MEAN_CMAXA_DUE <= 5.8 ) do;
GRP_AGS9_MEAN_CMAXA_DUE  = 4 ;
end;
when ( 5.8 < AGS9_MEAN_CMAXA_DUE ) do;
GRP_AGS9_MEAN_CMAXA_DUE  = 5 ;
end;
when ( missing(AGS9_MEAN_CMAXA_DUE) ) do;
GRP_AGS9_MEAN_CMAXA_DUE  = 6 ;
end;
otherwise GRP_AGS9_MEAN_CMAXA_DUE  = 7 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXC_DAYS) and AGS9_MEAN_CMAXC_DAYS <= 12.833333333 ) do;
GRP_AGS9_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( 12.833333333 < AGS9_MEAN_CMAXC_DAYS <= 13.6 ) do;
GRP_AGS9_MEAN_CMAXC_DAYS  = 2 ;
end;
when ( 13.6 < AGS9_MEAN_CMAXC_DAYS <= 14.125 ) do;
GRP_AGS9_MEAN_CMAXC_DAYS  = 3 ;
end;
when ( 14.125 < AGS9_MEAN_CMAXC_DAYS <= 14.888888889 ) do;
GRP_AGS9_MEAN_CMAXC_DAYS  = 4 ;
end;
when ( 14.888888889 < AGS9_MEAN_CMAXC_DAYS ) do;
GRP_AGS9_MEAN_CMAXC_DAYS  = 5 ;
end;
when ( missing(AGS9_MEAN_CMAXC_DAYS) ) do;
GRP_AGS9_MEAN_CMAXC_DAYS  = 6 ;
end;
otherwise GRP_AGS9_MEAN_CMAXC_DAYS  = 7 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXC_DUE) and AGS9_MEAN_CMAXC_DUE <= 0.2 ) do;
GRP_AGS9_MEAN_CMAXC_DUE  = 1 ;
end;
when ( 0.2 < AGS9_MEAN_CMAXC_DUE <= 1 ) do;
GRP_AGS9_MEAN_CMAXC_DUE  = 2 ;
end;
when ( 1 < AGS9_MEAN_CMAXC_DUE <= 3 ) do;
GRP_AGS9_MEAN_CMAXC_DUE  = 3 ;
end;
when ( 3 < AGS9_MEAN_CMAXC_DUE <= 5.6666666667 ) do;
GRP_AGS9_MEAN_CMAXC_DUE  = 4 ;
end;
when ( 5.6666666667 < AGS9_MEAN_CMAXC_DUE ) do;
GRP_AGS9_MEAN_CMAXC_DUE  = 5 ;
end;
when ( missing(AGS9_MEAN_CMAXC_DUE) ) do;
GRP_AGS9_MEAN_CMAXC_DUE  = 6 ;
end;
otherwise GRP_AGS9_MEAN_CMAXC_DUE  = 7 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXI_DAYS) and AGS9_MEAN_CMAXI_DAYS <= 11.888888889 ) do;
GRP_AGS9_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( 11.888888889 < AGS9_MEAN_CMAXI_DAYS <= 12.714285714 ) do;
GRP_AGS9_MEAN_CMAXI_DAYS  = 2 ;
end;
when ( 12.714285714 < AGS9_MEAN_CMAXI_DAYS <= 13.2 ) do;
GRP_AGS9_MEAN_CMAXI_DAYS  = 3 ;
end;
when ( 13.2 < AGS9_MEAN_CMAXI_DAYS <= 13.571428571 ) do;
GRP_AGS9_MEAN_CMAXI_DAYS  = 4 ;
end;
when ( 13.571428571 < AGS9_MEAN_CMAXI_DAYS ) do;
GRP_AGS9_MEAN_CMAXI_DAYS  = 5 ;
end;
when ( missing(AGS9_MEAN_CMAXI_DAYS) ) do;
GRP_AGS9_MEAN_CMAXI_DAYS  = 6 ;
end;
otherwise GRP_AGS9_MEAN_CMAXI_DAYS  = 7 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXI_DUE) and AGS9_MEAN_CMAXI_DUE <= 0 ) do;
GRP_AGS9_MEAN_CMAXI_DUE  = 1 ;
end;
when ( 0 < AGS9_MEAN_CMAXI_DUE ) do;
GRP_AGS9_MEAN_CMAXI_DUE  = 2 ;
end;
when ( missing(AGS9_MEAN_CMAXI_DUE) ) do;
GRP_AGS9_MEAN_CMAXI_DUE  = 3 ;
end;
otherwise GRP_AGS9_MEAN_CMAXI_DUE  = 4 ; end;
select;
when ( not missing(AGS9_MIN_CMAXA_DAYS) and AGS9_MIN_CMAXA_DAYS <= 10 ) do;
GRP_AGS9_MIN_CMAXA_DAYS  = 1 ;
end;
when ( 10 < AGS9_MIN_CMAXA_DAYS <= 11 ) do;
GRP_AGS9_MIN_CMAXA_DAYS  = 2 ;
end;
when ( 11 < AGS9_MIN_CMAXA_DAYS <= 12 ) do;
GRP_AGS9_MIN_CMAXA_DAYS  = 3 ;
end;
when ( 12 < AGS9_MIN_CMAXA_DAYS <= 14 ) do;
GRP_AGS9_MIN_CMAXA_DAYS  = 4 ;
end;
when ( 14 < AGS9_MIN_CMAXA_DAYS ) do;
GRP_AGS9_MIN_CMAXA_DAYS  = 5 ;
end;
when ( missing(AGS9_MIN_CMAXA_DAYS) ) do;
GRP_AGS9_MIN_CMAXA_DAYS  = 6 ;
end;
otherwise GRP_AGS9_MIN_CMAXA_DAYS  = 7 ; end;
select;
when ( not missing(AGS9_MIN_CMAXA_DUE) and AGS9_MIN_CMAXA_DUE <= 0 ) do;
GRP_AGS9_MIN_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGS9_MIN_CMAXA_DUE <= 1 ) do;
GRP_AGS9_MIN_CMAXA_DUE  = 2 ;
end;
when ( 1 < AGS9_MIN_CMAXA_DUE <= 3 ) do;
GRP_AGS9_MIN_CMAXA_DUE  = 3 ;
end;
when ( 3 < AGS9_MIN_CMAXA_DUE ) do;
GRP_AGS9_MIN_CMAXA_DUE  = 4 ;
end;
when ( missing(AGS9_MIN_CMAXA_DUE) ) do;
GRP_AGS9_MIN_CMAXA_DUE  = 5 ;
end;
otherwise GRP_AGS9_MIN_CMAXA_DUE  = 6 ; end;
select;
when ( not missing(AGS9_MIN_CMAXC_DAYS) and AGS9_MIN_CMAXC_DAYS <= 8 ) do;
GRP_AGS9_MIN_CMAXC_DAYS  = 1 ;
end;
when ( 8 < AGS9_MIN_CMAXC_DAYS <= 11 ) do;
GRP_AGS9_MIN_CMAXC_DAYS  = 2 ;
end;
when ( 11 < AGS9_MIN_CMAXC_DAYS <= 14 ) do;
GRP_AGS9_MIN_CMAXC_DAYS  = 3 ;
end;
when ( 14 < AGS9_MIN_CMAXC_DAYS ) do;
GRP_AGS9_MIN_CMAXC_DAYS  = 4 ;
end;
when ( missing(AGS9_MIN_CMAXC_DAYS) ) do;
GRP_AGS9_MIN_CMAXC_DAYS  = 5 ;
end;
otherwise GRP_AGS9_MIN_CMAXC_DAYS  = 6 ; end;
select;
when ( not missing(AGS9_MIN_CMAXC_DUE) and AGS9_MIN_CMAXC_DUE <= 0 ) do;
GRP_AGS9_MIN_CMAXC_DUE  = 1 ;
end;
when ( 0 < AGS9_MIN_CMAXC_DUE <= 2 ) do;
GRP_AGS9_MIN_CMAXC_DUE  = 2 ;
end;
when ( 2 < AGS9_MIN_CMAXC_DUE <= 4 ) do;
GRP_AGS9_MIN_CMAXC_DUE  = 3 ;
end;
when ( 4 < AGS9_MIN_CMAXC_DUE ) do;
GRP_AGS9_MIN_CMAXC_DUE  = 4 ;
end;
when ( missing(AGS9_MIN_CMAXC_DUE) ) do;
GRP_AGS9_MIN_CMAXC_DUE  = 5 ;
end;
otherwise GRP_AGS9_MIN_CMAXC_DUE  = 6 ; end;
select;
when ( not missing(AGS9_MIN_CMAXI_DAYS) and AGS9_MIN_CMAXI_DAYS <= 7 ) do;
GRP_AGS9_MIN_CMAXI_DAYS  = 1 ;
end;
when ( 7 < AGS9_MIN_CMAXI_DAYS <= 9 ) do;
GRP_AGS9_MIN_CMAXI_DAYS  = 2 ;
end;
when ( 9 < AGS9_MIN_CMAXI_DAYS <= 10 ) do;
GRP_AGS9_MIN_CMAXI_DAYS  = 3 ;
end;
when ( 10 < AGS9_MIN_CMAXI_DAYS ) do;
GRP_AGS9_MIN_CMAXI_DAYS  = 4 ;
end;
when ( missing(AGS9_MIN_CMAXI_DAYS) ) do;
GRP_AGS9_MIN_CMAXI_DAYS  = 5 ;
end;
otherwise GRP_AGS9_MIN_CMAXI_DAYS  = 6 ; end;
select;
when ( not missing(AGS9_MIN_CMAXI_DUE) ) do;
GRP_AGS9_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS9_MIN_CMAXI_DUE) ) do;
GRP_AGS9_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS9_MIN_CMAXI_DUE  = 3 ; end;
select (APP_CHAR_BRANCH );
  when ('Computers')   do;
GRP_APP_CHAR_BRANCH  = 1 ;
end;
  when ('DiY')   do;
GRP_APP_CHAR_BRANCH  = 2 ;
end;
  when ('Fenitures')   do;
GRP_APP_CHAR_BRANCH  = 3 ;
end;
  when ('Radio-TV')   do;
GRP_APP_CHAR_BRANCH  = 4 ;
end;
otherwise GRP_APP_CHAR_BRANCH  = 5 ; end;
select (APP_CHAR_CARS );
  when ('No')   do;
GRP_APP_CHAR_CARS  = 1 ;
end;
  when ('Owner')   do;
GRP_APP_CHAR_CARS  = 2 ;
end;
otherwise GRP_APP_CHAR_CARS  = 3 ; end;
select (APP_CHAR_CITY );
  when ('Big')   do;
GRP_APP_CHAR_CITY  = 1 ;
end;
  when ('Small')   do;
GRP_APP_CHAR_CITY  = 2 ;
end;
  when ('Medium')   do;
GRP_APP_CHAR_CITY  = 3 ;
end;
  when ('Large')   do;
GRP_APP_CHAR_CITY  = 4 ;
end;
otherwise GRP_APP_CHAR_CITY  = 5 ; end;
select (APP_CHAR_GENDER );
  when ('Female')   do;
GRP_APP_CHAR_GENDER  = 1 ;
end;
  when ('Male')   do;
GRP_APP_CHAR_GENDER  = 2 ;
end;
otherwise GRP_APP_CHAR_GENDER  = 3 ; end;
select (APP_CHAR_HOME_STATUS );
  when ('Owner')   do;
GRP_APP_CHAR_HOME_STATUS  = 1 ;
end;
  when ('Rental')   do;
GRP_APP_CHAR_HOME_STATUS  = 2 ;
end;
otherwise GRP_APP_CHAR_HOME_STATUS  = 3 ; end;
select (APP_CHAR_JOB_CODE );
  when ('Permanent')   do;
GRP_APP_CHAR_JOB_CODE  = 1 ;
end;
  when ('Retired')   do;
GRP_APP_CHAR_JOB_CODE  = 2 ;
end;
  when ('Owner company')   do;
GRP_APP_CHAR_JOB_CODE  = 3 ;
end;
  when ('Contract')   do;
GRP_APP_CHAR_JOB_CODE  = 4 ;
end;
otherwise GRP_APP_CHAR_JOB_CODE  = 5 ; end;
select (APP_CHAR_MARITAL_STATUS );
  when ('Divorced')   do;
GRP_APP_CHAR_MARITAL_STATUS  = 1 ;
end;
  when ('Maried')   do;
GRP_APP_CHAR_MARITAL_STATUS  = 2 ;
end;
  when ('Widowed')   do;
GRP_APP_CHAR_MARITAL_STATUS  = 3 ;
end;
otherwise GRP_APP_CHAR_MARITAL_STATUS  = 4 ; end;
select;
when ( not missing(APP_INCOME) and APP_INCOME <= 383 ) do;
GRP_APP_INCOME  = 1 ;
end;
when ( 383 < APP_INCOME <= 465 ) do;
GRP_APP_INCOME  = 2 ;
end;
when ( 465 < APP_INCOME <= 517 ) do;
GRP_APP_INCOME  = 3 ;
end;
when ( 517 < APP_INCOME <= 952 ) do;
GRP_APP_INCOME  = 4 ;
end;
when ( 952 < APP_INCOME <= 4223 ) do;
GRP_APP_INCOME  = 5 ;
end;
when ( 4223 < APP_INCOME ) do;
GRP_APP_INCOME  = 6 ;
end;
when ( missing(APP_INCOME) ) do;
GRP_APP_INCOME  = 7 ;
end;
otherwise GRP_APP_INCOME  = 8 ; end;
select;
when ( not missing(APP_INSTALLMENT) and APP_INSTALLMENT <= 115 ) do;
GRP_APP_INSTALLMENT  = 1 ;
end;
when ( 115 < APP_INSTALLMENT <= 290 ) do;
GRP_APP_INSTALLMENT  = 2 ;
end;
when ( 290 < APP_INSTALLMENT <= 311 ) do;
GRP_APP_INSTALLMENT  = 3 ;
end;
when ( 311 < APP_INSTALLMENT <= 371 ) do;
GRP_APP_INSTALLMENT  = 4 ;
end;
when ( 371 < APP_INSTALLMENT <= 490 ) do;
GRP_APP_INSTALLMENT  = 5 ;
end;
when ( 490 < APP_INSTALLMENT ) do;
GRP_APP_INSTALLMENT  = 6 ;
end;
when ( missing(APP_INSTALLMENT) ) do;
GRP_APP_INSTALLMENT  = 7 ;
end;
otherwise GRP_APP_INSTALLMENT  = 8 ; end;
select;
when ( not missing(APP_LOAN_AMOUNT) and APP_LOAN_AMOUNT <= 1788 ) do;
GRP_APP_LOAN_AMOUNT  = 1 ;
end;
when ( 1788 < APP_LOAN_AMOUNT <= 2304 ) do;
GRP_APP_LOAN_AMOUNT  = 2 ;
end;
when ( 2304 < APP_LOAN_AMOUNT <= 2628 ) do;
GRP_APP_LOAN_AMOUNT  = 3 ;
end;
when ( 2628 < APP_LOAN_AMOUNT <= 10464 ) do;
GRP_APP_LOAN_AMOUNT  = 4 ;
end;
when ( 10464 < APP_LOAN_AMOUNT <= 12636 ) do;
GRP_APP_LOAN_AMOUNT  = 5 ;
end;
when ( 12636 < APP_LOAN_AMOUNT ) do;
GRP_APP_LOAN_AMOUNT  = 6 ;
end;
when ( missing(APP_LOAN_AMOUNT) ) do;
GRP_APP_LOAN_AMOUNT  = 7 ;
end;
otherwise GRP_APP_LOAN_AMOUNT  = 8 ; end;
select;
when ( not missing(APP_NUMBER_OF_CHILDREN) and APP_NUMBER_OF_CHILDREN <= 0 ) do;
GRP_APP_NUMBER_OF_CHILDREN  = 1 ;
end;
when ( 0 < APP_NUMBER_OF_CHILDREN <= 1 ) do;
GRP_APP_NUMBER_OF_CHILDREN  = 2 ;
end;
when ( 1 < APP_NUMBER_OF_CHILDREN ) do;
GRP_APP_NUMBER_OF_CHILDREN  = 3 ;
end;
when ( missing(APP_NUMBER_OF_CHILDREN) ) do;
GRP_APP_NUMBER_OF_CHILDREN  = 4 ;
end;
otherwise GRP_APP_NUMBER_OF_CHILDREN  = 5 ; end;
select;
when ( not missing(APP_N_INSTALLMENTS) and APP_N_INSTALLMENTS <= 12 ) do;
GRP_APP_N_INSTALLMENTS  = 1 ;
end;
when ( 12 < APP_N_INSTALLMENTS <= 24 ) do;
GRP_APP_N_INSTALLMENTS  = 2 ;
end;
when ( 24 < APP_N_INSTALLMENTS ) do;
GRP_APP_N_INSTALLMENTS  = 3 ;
end;
when ( missing(APP_N_INSTALLMENTS) ) do;
GRP_APP_N_INSTALLMENTS  = 4 ;
end;
otherwise GRP_APP_N_INSTALLMENTS  = 5 ; end;
select;
when ( not missing(APP_SPENDINGS) and APP_SPENDINGS <= 140 ) do;
GRP_APP_SPENDINGS  = 1 ;
end;
when ( 140 < APP_SPENDINGS <= 220 ) do;
GRP_APP_SPENDINGS  = 2 ;
end;
when ( 220 < APP_SPENDINGS <= 240 ) do;
GRP_APP_SPENDINGS  = 3 ;
end;
when ( 240 < APP_SPENDINGS <= 360 ) do;
GRP_APP_SPENDINGS  = 4 ;
end;
when ( 360 < APP_SPENDINGS <= 2160 ) do;
GRP_APP_SPENDINGS  = 5 ;
end;
when ( 2160 < APP_SPENDINGS ) do;
GRP_APP_SPENDINGS  = 6 ;
end;
when ( missing(APP_SPENDINGS) ) do;
GRP_APP_SPENDINGS  = 7 ;
end;
otherwise GRP_APP_SPENDINGS  = 8 ; end;
run;
