data grp;
set abt.train;
select;
when ( not missing(ACT12_N_ARREARS) and ACT12_N_ARREARS <= 6 ) do;
GRP_ACT12_N_ARREARS  = 1 ;
end;
when ( 6 < ACT12_N_ARREARS ) do;
GRP_ACT12_N_ARREARS  = 2 ;
end;
when ( missing(ACT12_N_ARREARS) ) do;
GRP_ACT12_N_ARREARS  = 3 ;
end;
otherwise GRP_ACT12_N_ARREARS  = 4 ; end;
select;
when ( not missing(ACT12_N_ARREARS_DAYS) ) do;
GRP_ACT12_N_ARREARS_DAYS  = 1 ;
end;
when ( missing(ACT12_N_ARREARS_DAYS) ) do;
GRP_ACT12_N_ARREARS_DAYS  = 2 ;
end;
otherwise GRP_ACT12_N_ARREARS_DAYS  = 3 ; end;
select;
when ( not missing(ACT12_N_GOOD_DAYS) and ACT12_N_GOOD_DAYS <= 4 ) do;
GRP_ACT12_N_GOOD_DAYS  = 1 ;
end;
when ( 4 < ACT12_N_GOOD_DAYS ) do;
GRP_ACT12_N_GOOD_DAYS  = 2 ;
end;
when ( missing(ACT12_N_GOOD_DAYS) ) do;
GRP_ACT12_N_GOOD_DAYS  = 3 ;
end;
otherwise GRP_ACT12_N_GOOD_DAYS  = 4 ; end;
select;
when ( not missing(ACT3_N_ARREARS) and ACT3_N_ARREARS <= 2 ) do;
GRP_ACT3_N_ARREARS  = 1 ;
end;
when ( 2 < ACT3_N_ARREARS ) do;
GRP_ACT3_N_ARREARS  = 2 ;
end;
when ( missing(ACT3_N_ARREARS) ) do;
GRP_ACT3_N_ARREARS  = 3 ;
end;
otherwise GRP_ACT3_N_ARREARS  = 4 ; end;
select;
when ( not missing(ACT3_N_ARREARS_DAYS) ) do;
GRP_ACT3_N_ARREARS_DAYS  = 1 ;
end;
when ( missing(ACT3_N_ARREARS_DAYS) ) do;
GRP_ACT3_N_ARREARS_DAYS  = 2 ;
end;
otherwise GRP_ACT3_N_ARREARS_DAYS  = 3 ; end;
select;
when ( not missing(ACT3_N_GOOD_DAYS) and ACT3_N_GOOD_DAYS <= 0 ) do;
GRP_ACT3_N_GOOD_DAYS  = 1 ;
end;
when ( 0 < ACT3_N_GOOD_DAYS ) do;
GRP_ACT3_N_GOOD_DAYS  = 2 ;
end;
when ( missing(ACT3_N_GOOD_DAYS) ) do;
GRP_ACT3_N_GOOD_DAYS  = 3 ;
end;
otherwise GRP_ACT3_N_GOOD_DAYS  = 4 ; end;
select;
when ( not missing(ACT6_N_ARREARS) and ACT6_N_ARREARS <= 2 ) do;
GRP_ACT6_N_ARREARS  = 1 ;
end;
when ( 2 < ACT6_N_ARREARS ) do;
GRP_ACT6_N_ARREARS  = 2 ;
end;
when ( missing(ACT6_N_ARREARS) ) do;
GRP_ACT6_N_ARREARS  = 3 ;
end;
otherwise GRP_ACT6_N_ARREARS  = 4 ; end;
select;
when ( not missing(ACT6_N_ARREARS_DAYS) ) do;
GRP_ACT6_N_ARREARS_DAYS  = 1 ;
end;
when ( missing(ACT6_N_ARREARS_DAYS) ) do;
GRP_ACT6_N_ARREARS_DAYS  = 2 ;
end;
otherwise GRP_ACT6_N_ARREARS_DAYS  = 3 ; end;
select;
when ( not missing(ACT6_N_GOOD_DAYS) and ACT6_N_GOOD_DAYS <= 0 ) do;
GRP_ACT6_N_GOOD_DAYS  = 1 ;
end;
when ( 0 < ACT6_N_GOOD_DAYS <= 2 ) do;
GRP_ACT6_N_GOOD_DAYS  = 2 ;
end;
when ( 2 < ACT6_N_GOOD_DAYS ) do;
GRP_ACT6_N_GOOD_DAYS  = 3 ;
end;
when ( missing(ACT6_N_GOOD_DAYS) ) do;
GRP_ACT6_N_GOOD_DAYS  = 4 ;
end;
otherwise GRP_ACT6_N_GOOD_DAYS  = 5 ; end;
select;
when ( not missing(ACT9_N_ARREARS) and ACT9_N_ARREARS <= 0 ) do;
GRP_ACT9_N_ARREARS  = 1 ;
end;
when ( 0 < ACT9_N_ARREARS <= 7 ) do;
GRP_ACT9_N_ARREARS  = 2 ;
end;
when ( 7 < ACT9_N_ARREARS ) do;
GRP_ACT9_N_ARREARS  = 3 ;
end;
when ( missing(ACT9_N_ARREARS) ) do;
GRP_ACT9_N_ARREARS  = 4 ;
end;
otherwise GRP_ACT9_N_ARREARS  = 5 ; end;
select;
when ( not missing(ACT9_N_ARREARS_DAYS) ) do;
GRP_ACT9_N_ARREARS_DAYS  = 1 ;
end;
when ( missing(ACT9_N_ARREARS_DAYS) ) do;
GRP_ACT9_N_ARREARS_DAYS  = 2 ;
end;
otherwise GRP_ACT9_N_ARREARS_DAYS  = 3 ; end;
select;
when ( not missing(ACT9_N_GOOD_DAYS) and ACT9_N_GOOD_DAYS <= 2 ) do;
GRP_ACT9_N_GOOD_DAYS  = 1 ;
end;
when ( 2 < ACT9_N_GOOD_DAYS ) do;
GRP_ACT9_N_GOOD_DAYS  = 2 ;
end;
when ( missing(ACT9_N_GOOD_DAYS) ) do;
GRP_ACT9_N_GOOD_DAYS  = 3 ;
end;
otherwise GRP_ACT9_N_GOOD_DAYS  = 4 ; end;
select;
when ( not missing(ACT_AGE) and ACT_AGE <= 39 ) do;
GRP_ACT_AGE  = 1 ;
end;
when ( 39 < ACT_AGE <= 44 ) do;
GRP_ACT_AGE  = 2 ;
end;
when ( 44 < ACT_AGE <= 53 ) do;
GRP_ACT_AGE  = 3 ;
end;
when ( 53 < ACT_AGE <= 62 ) do;
GRP_ACT_AGE  = 4 ;
end;
when ( 62 < ACT_AGE <= 76 ) do;
GRP_ACT_AGE  = 5 ;
end;
when ( 76 < ACT_AGE ) do;
GRP_ACT_AGE  = 6 ;
end;
when ( missing(ACT_AGE) ) do;
GRP_ACT_AGE  = 7 ;
end;
otherwise GRP_ACT_AGE  = 8 ; end;
select;
when ( not missing(ACT_CALL_CC) and ACT_CALL_CC <= 0.1978877154 ) do;
GRP_ACT_CALL_CC  = 1 ;
end;
when ( 0.1978877154 < ACT_CALL_CC <= 0.258629846 ) do;
GRP_ACT_CALL_CC  = 2 ;
end;
when ( 0.258629846 < ACT_CALL_CC <= 0.8923857868 ) do;
GRP_ACT_CALL_CC  = 3 ;
end;
when ( 0.8923857868 < ACT_CALL_CC <= 1.0412573674 ) do;
GRP_ACT_CALL_CC  = 4 ;
end;
when ( 1.0412573674 < ACT_CALL_CC <= 1.3146853147 ) do;
GRP_ACT_CALL_CC  = 5 ;
end;
when ( 1.3146853147 < ACT_CALL_CC ) do;
GRP_ACT_CALL_CC  = 6 ;
end;
when ( missing(ACT_CALL_CC) ) do;
GRP_ACT_CALL_CC  = 7 ;
end;
otherwise GRP_ACT_CALL_CC  = 8 ; end;
select;
when ( not missing(ACT_CALL_N_LOAN) and ACT_CALL_N_LOAN <= 1 ) do;
GRP_ACT_CALL_N_LOAN  = 1 ;
end;
when ( 1 < ACT_CALL_N_LOAN ) do;
GRP_ACT_CALL_N_LOAN  = 2 ;
end;
when ( missing(ACT_CALL_N_LOAN) ) do;
GRP_ACT_CALL_N_LOAN  = 3 ;
end;
otherwise GRP_ACT_CALL_N_LOAN  = 4 ; end;
select;
when ( not missing(ACT_CC) and ACT_CC <= 0.248125937 ) do;
GRP_ACT_CC  = 1 ;
end;
when ( 0.248125937 < ACT_CC <= 0.3324658426 ) do;
GRP_ACT_CC  = 2 ;
end;
when ( 0.3324658426 < ACT_CC <= 0.857442348 ) do;
GRP_ACT_CC  = 3 ;
end;
when ( 0.857442348 < ACT_CC <= 1.0535455861 ) do;
GRP_ACT_CC  = 4 ;
end;
when ( 1.0535455861 < ACT_CC ) do;
GRP_ACT_CC  = 5 ;
end;
when ( missing(ACT_CC) ) do;
GRP_ACT_CC  = 6 ;
end;
otherwise GRP_ACT_CC  = 7 ; end;
select;
when ( not missing(ACT_CCSS_CC) ) do;
GRP_ACT_CCSS_CC  = 1 ;
end;
when ( missing(ACT_CCSS_CC) ) do;
GRP_ACT_CCSS_CC  = 2 ;
end;
otherwise GRP_ACT_CCSS_CC  = 3 ; end;
select;
when ( not missing(ACT_CCSS_DUEUTL) ) do;
GRP_ACT_CCSS_DUEUTL  = 1 ;
end;
when ( missing(ACT_CCSS_DUEUTL) ) do;
GRP_ACT_CCSS_DUEUTL  = 2 ;
end;
otherwise GRP_ACT_CCSS_DUEUTL  = 3 ; end;
select;
when ( not missing(ACT_CCSS_MAXDUE) ) do;
GRP_ACT_CCSS_MAXDUE  = 1 ;
end;
when ( missing(ACT_CCSS_MAXDUE) ) do;
GRP_ACT_CCSS_MAXDUE  = 2 ;
end;
otherwise GRP_ACT_CCSS_MAXDUE  = 3 ; end;
select;
when ( not missing(ACT_CCSS_MIN_LNINST) ) do;
GRP_ACT_CCSS_MIN_LNINST  = 1 ;
end;
when ( missing(ACT_CCSS_MIN_LNINST) ) do;
GRP_ACT_CCSS_MIN_LNINST  = 2 ;
end;
otherwise GRP_ACT_CCSS_MIN_LNINST  = 3 ; end;
select;
when ( not missing(ACT_CCSS_MIN_PNINST) ) do;
GRP_ACT_CCSS_MIN_PNINST  = 1 ;
end;
when ( missing(ACT_CCSS_MIN_PNINST) ) do;
GRP_ACT_CCSS_MIN_PNINST  = 2 ;
end;
otherwise GRP_ACT_CCSS_MIN_PNINST  = 3 ; end;
select;
when ( not missing(ACT_CCSS_MIN_SENIORITY) and ACT_CCSS_MIN_SENIORITY <= 4 ) do;
GRP_ACT_CCSS_MIN_SENIORITY  = 1 ;
end;
when ( 4 < ACT_CCSS_MIN_SENIORITY <= 23 ) do;
GRP_ACT_CCSS_MIN_SENIORITY  = 2 ;
end;
when ( 23 < ACT_CCSS_MIN_SENIORITY ) do;
GRP_ACT_CCSS_MIN_SENIORITY  = 3 ;
end;
when ( missing(ACT_CCSS_MIN_SENIORITY) ) do;
GRP_ACT_CCSS_MIN_SENIORITY  = 4 ;
end;
otherwise GRP_ACT_CCSS_MIN_SENIORITY  = 5 ; end;
select;
when ( not missing(ACT_CCSS_N_LOAN) and ACT_CCSS_N_LOAN <= 0 ) do;
GRP_ACT_CCSS_N_LOAN  = 1 ;
end;
when ( 0 < ACT_CCSS_N_LOAN ) do;
GRP_ACT_CCSS_N_LOAN  = 2 ;
end;
when ( missing(ACT_CCSS_N_LOAN) ) do;
GRP_ACT_CCSS_N_LOAN  = 3 ;
end;
otherwise GRP_ACT_CCSS_N_LOAN  = 4 ; end;
select;
when ( not missing(ACT_CCSS_N_LOANS_ACT) ) do;
GRP_ACT_CCSS_N_LOANS_ACT  = 1 ;
end;
when ( missing(ACT_CCSS_N_LOANS_ACT) ) do;
GRP_ACT_CCSS_N_LOANS_ACT  = 2 ;
end;
otherwise GRP_ACT_CCSS_N_LOANS_ACT  = 3 ; end;
select;
when ( not missing(ACT_CCSS_N_LOANS_HIST) and ACT_CCSS_N_LOANS_HIST <= 4 ) do;
GRP_ACT_CCSS_N_LOANS_HIST  = 1 ;
end;
when ( 4 < ACT_CCSS_N_LOANS_HIST <= 10 ) do;
GRP_ACT_CCSS_N_LOANS_HIST  = 2 ;
end;
when ( 10 < ACT_CCSS_N_LOANS_HIST ) do;
GRP_ACT_CCSS_N_LOANS_HIST  = 3 ;
end;
when ( missing(ACT_CCSS_N_LOANS_HIST) ) do;
GRP_ACT_CCSS_N_LOANS_HIST  = 4 ;
end;
otherwise GRP_ACT_CCSS_N_LOANS_HIST  = 5 ; end;
select;
when ( not missing(ACT_CCSS_N_STATB) and ACT_CCSS_N_STATB <= 3 ) do;
GRP_ACT_CCSS_N_STATB  = 1 ;
end;
when ( 3 < ACT_CCSS_N_STATB <= 8 ) do;
GRP_ACT_CCSS_N_STATB  = 2 ;
end;
when ( 8 < ACT_CCSS_N_STATB ) do;
GRP_ACT_CCSS_N_STATB  = 3 ;
end;
when ( missing(ACT_CCSS_N_STATB) ) do;
GRP_ACT_CCSS_N_STATB  = 4 ;
end;
otherwise GRP_ACT_CCSS_N_STATB  = 5 ; end;
select;
when ( not missing(ACT_CCSS_N_STATC) and ACT_CCSS_N_STATC <= 0 ) do;
GRP_ACT_CCSS_N_STATC  = 1 ;
end;
when ( 0 < ACT_CCSS_N_STATC ) do;
GRP_ACT_CCSS_N_STATC  = 2 ;
end;
when ( missing(ACT_CCSS_N_STATC) ) do;
GRP_ACT_CCSS_N_STATC  = 3 ;
end;
otherwise GRP_ACT_CCSS_N_STATC  = 4 ; end;
select;
when ( not missing(ACT_CCSS_SENIORITY) and ACT_CCSS_SENIORITY <= 63 ) do;
GRP_ACT_CCSS_SENIORITY  = 1 ;
end;
when ( 63 < ACT_CCSS_SENIORITY <= 109 ) do;
GRP_ACT_CCSS_SENIORITY  = 2 ;
end;
when ( 109 < ACT_CCSS_SENIORITY ) do;
GRP_ACT_CCSS_SENIORITY  = 3 ;
end;
when ( missing(ACT_CCSS_SENIORITY) ) do;
GRP_ACT_CCSS_SENIORITY  = 4 ;
end;
otherwise GRP_ACT_CCSS_SENIORITY  = 5 ; end;
select;
when ( not missing(ACT_CCSS_UTL) ) do;
GRP_ACT_CCSS_UTL  = 1 ;
end;
when ( missing(ACT_CCSS_UTL) ) do;
GRP_ACT_CCSS_UTL  = 2 ;
end;
otherwise GRP_ACT_CCSS_UTL  = 3 ; end;
select;
when ( not missing(ACT_CINS_CC) ) do;
GRP_ACT_CINS_CC  = 1 ;
end;
when ( missing(ACT_CINS_CC) ) do;
GRP_ACT_CINS_CC  = 2 ;
end;
otherwise GRP_ACT_CINS_CC  = 3 ; end;
select;
when ( not missing(ACT_CINS_DUEUTL) ) do;
GRP_ACT_CINS_DUEUTL  = 1 ;
end;
when ( missing(ACT_CINS_DUEUTL) ) do;
GRP_ACT_CINS_DUEUTL  = 2 ;
end;
otherwise GRP_ACT_CINS_DUEUTL  = 3 ; end;
select;
when ( not missing(ACT_CINS_MAXDUE) ) do;
GRP_ACT_CINS_MAXDUE  = 1 ;
end;
when ( missing(ACT_CINS_MAXDUE) ) do;
GRP_ACT_CINS_MAXDUE  = 2 ;
end;
otherwise GRP_ACT_CINS_MAXDUE  = 3 ; end;
select;
when ( not missing(ACT_CINS_MIN_LNINST) ) do;
GRP_ACT_CINS_MIN_LNINST  = 1 ;
end;
when ( missing(ACT_CINS_MIN_LNINST) ) do;
GRP_ACT_CINS_MIN_LNINST  = 2 ;
end;
otherwise GRP_ACT_CINS_MIN_LNINST  = 3 ; end;
select;
when ( not missing(ACT_CINS_MIN_PNINST) ) do;
GRP_ACT_CINS_MIN_PNINST  = 1 ;
end;
when ( missing(ACT_CINS_MIN_PNINST) ) do;
GRP_ACT_CINS_MIN_PNINST  = 2 ;
end;
otherwise GRP_ACT_CINS_MIN_PNINST  = 3 ; end;
select;
when ( not missing(ACT_CINS_MIN_SENIORITY) and ACT_CINS_MIN_SENIORITY <= 22 ) do;
GRP_ACT_CINS_MIN_SENIORITY  = 1 ;
end;
when ( 22 < ACT_CINS_MIN_SENIORITY <= 36 ) do;
GRP_ACT_CINS_MIN_SENIORITY  = 2 ;
end;
when ( 36 < ACT_CINS_MIN_SENIORITY <= 119 ) do;
GRP_ACT_CINS_MIN_SENIORITY  = 3 ;
end;
when ( 119 < ACT_CINS_MIN_SENIORITY ) do;
GRP_ACT_CINS_MIN_SENIORITY  = 4 ;
end;
when ( missing(ACT_CINS_MIN_SENIORITY) ) do;
GRP_ACT_CINS_MIN_SENIORITY  = 5 ;
end;
otherwise GRP_ACT_CINS_MIN_SENIORITY  = 6 ; end;
select;
when ( not missing(ACT_CINS_N_LOAN) and ACT_CINS_N_LOAN <= 1 ) do;
GRP_ACT_CINS_N_LOAN  = 1 ;
end;
when ( 1 < ACT_CINS_N_LOAN ) do;
GRP_ACT_CINS_N_LOAN  = 2 ;
end;
when ( missing(ACT_CINS_N_LOAN) ) do;
GRP_ACT_CINS_N_LOAN  = 3 ;
end;
otherwise GRP_ACT_CINS_N_LOAN  = 4 ; end;
select;
when ( not missing(ACT_CINS_N_LOANS_ACT) ) do;
GRP_ACT_CINS_N_LOANS_ACT  = 1 ;
end;
when ( missing(ACT_CINS_N_LOANS_ACT) ) do;
GRP_ACT_CINS_N_LOANS_ACT  = 2 ;
end;
otherwise GRP_ACT_CINS_N_LOANS_ACT  = 3 ; end;
select;
when ( not missing(ACT_CINS_N_LOANS_HIST) and ACT_CINS_N_LOANS_HIST <= 1 ) do;
GRP_ACT_CINS_N_LOANS_HIST  = 1 ;
end;
when ( 1 < ACT_CINS_N_LOANS_HIST <= 2 ) do;
GRP_ACT_CINS_N_LOANS_HIST  = 2 ;
end;
when ( 2 < ACT_CINS_N_LOANS_HIST <= 4 ) do;
GRP_ACT_CINS_N_LOANS_HIST  = 3 ;
end;
when ( 4 < ACT_CINS_N_LOANS_HIST ) do;
GRP_ACT_CINS_N_LOANS_HIST  = 4 ;
end;
when ( missing(ACT_CINS_N_LOANS_HIST) ) do;
GRP_ACT_CINS_N_LOANS_HIST  = 5 ;
end;
otherwise GRP_ACT_CINS_N_LOANS_HIST  = 6 ; end;
select;
when ( not missing(ACT_CINS_N_STATB) and ACT_CINS_N_STATB <= 0 ) do;
GRP_ACT_CINS_N_STATB  = 1 ;
end;
when ( 0 < ACT_CINS_N_STATB ) do;
GRP_ACT_CINS_N_STATB  = 2 ;
end;
when ( missing(ACT_CINS_N_STATB) ) do;
GRP_ACT_CINS_N_STATB  = 3 ;
end;
otherwise GRP_ACT_CINS_N_STATB  = 4 ; end;
select;
when ( not missing(ACT_CINS_N_STATC) and ACT_CINS_N_STATC <= 0 ) do;
GRP_ACT_CINS_N_STATC  = 1 ;
end;
when ( 0 < ACT_CINS_N_STATC <= 1 ) do;
GRP_ACT_CINS_N_STATC  = 2 ;
end;
when ( 1 < ACT_CINS_N_STATC <= 2 ) do;
GRP_ACT_CINS_N_STATC  = 3 ;
end;
when ( 2 < ACT_CINS_N_STATC ) do;
GRP_ACT_CINS_N_STATC  = 4 ;
end;
when ( missing(ACT_CINS_N_STATC) ) do;
GRP_ACT_CINS_N_STATC  = 5 ;
end;
otherwise GRP_ACT_CINS_N_STATC  = 6 ; end;
select;
when ( not missing(ACT_CINS_SENIORITY) and ACT_CINS_SENIORITY <= 78 ) do;
GRP_ACT_CINS_SENIORITY  = 1 ;
end;
when ( 78 < ACT_CINS_SENIORITY <= 92 ) do;
GRP_ACT_CINS_SENIORITY  = 2 ;
end;
when ( 92 < ACT_CINS_SENIORITY <= 116 ) do;
GRP_ACT_CINS_SENIORITY  = 3 ;
end;
when ( 116 < ACT_CINS_SENIORITY <= 140 ) do;
GRP_ACT_CINS_SENIORITY  = 4 ;
end;
when ( 140 < ACT_CINS_SENIORITY <= 167 ) do;
GRP_ACT_CINS_SENIORITY  = 5 ;
end;
when ( 167 < ACT_CINS_SENIORITY ) do;
GRP_ACT_CINS_SENIORITY  = 6 ;
end;
when ( missing(ACT_CINS_SENIORITY) ) do;
GRP_ACT_CINS_SENIORITY  = 7 ;
end;
otherwise GRP_ACT_CINS_SENIORITY  = 8 ; end;
select;
when ( not missing(ACT_CINS_UTL) ) do;
GRP_ACT_CINS_UTL  = 1 ;
end;
when ( missing(ACT_CINS_UTL) ) do;
GRP_ACT_CINS_UTL  = 2 ;
end;
otherwise GRP_ACT_CINS_UTL  = 3 ; end;
select;
when ( not missing(ACT_CUS_ACTIVE) ) do;
GRP_ACT_CUS_ACTIVE  = 1 ;
end;
when ( missing(ACT_CUS_ACTIVE) ) do;
GRP_ACT_CUS_ACTIVE  = 2 ;
end;
otherwise GRP_ACT_CUS_ACTIVE  = 3 ; end;
select;
when ( not missing(ACT_LOANINC) and ACT_LOANINC <= 0.3890274314 ) do;
GRP_ACT_LOANINC  = 1 ;
end;
when ( 0.3890274314 < ACT_LOANINC <= 2.6373626374 ) do;
GRP_ACT_LOANINC  = 2 ;
end;
when ( 2.6373626374 < ACT_LOANINC <= 6 ) do;
GRP_ACT_LOANINC  = 3 ;
end;
when ( 6 < ACT_LOANINC <= 7.6883116883 ) do;
GRP_ACT_LOANINC  = 4 ;
end;
when ( 7.6883116883 < ACT_LOANINC <= 16.243093923 ) do;
GRP_ACT_LOANINC  = 5 ;
end;
when ( 16.243093923 < ACT_LOANINC ) do;
GRP_ACT_LOANINC  = 6 ;
end;
when ( missing(ACT_LOANINC) ) do;
GRP_ACT_LOANINC  = 7 ;
end;
otherwise GRP_ACT_LOANINC  = 8 ; end;
select;
when ( not missing(AGR12_MAX_CMAXA_DAYS) ) do;
GRP_AGR12_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR12_MAX_CMAXA_DAYS) ) do;
GRP_AGR12_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MAX_CMAXA_DUE) ) do;
GRP_AGR12_MAX_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR12_MAX_CMAXA_DUE) ) do;
GRP_AGR12_MAX_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR12_MAX_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MAX_CMAXC_DAYS) ) do;
GRP_AGR12_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR12_MAX_CMAXC_DAYS) ) do;
GRP_AGR12_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MAX_CMAXC_DUE) ) do;
GRP_AGR12_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR12_MAX_CMAXC_DUE) ) do;
GRP_AGR12_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR12_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MAX_CMAXI_DAYS) ) do;
GRP_AGR12_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR12_MAX_CMAXI_DAYS) ) do;
GRP_AGR12_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MAX_CMAXI_DUE) ) do;
GRP_AGR12_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR12_MAX_CMAXI_DUE) ) do;
GRP_AGR12_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR12_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXA_DAYS) ) do;
GRP_AGR12_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR12_MEAN_CMAXA_DAYS) ) do;
GRP_AGR12_MEAN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MEAN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXA_DUE) ) do;
GRP_AGR12_MEAN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR12_MEAN_CMAXA_DUE) ) do;
GRP_AGR12_MEAN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR12_MEAN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXC_DAYS) ) do;
GRP_AGR12_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR12_MEAN_CMAXC_DAYS) ) do;
GRP_AGR12_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXC_DUE) ) do;
GRP_AGR12_MEAN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR12_MEAN_CMAXC_DUE) ) do;
GRP_AGR12_MEAN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR12_MEAN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXI_DAYS) ) do;
GRP_AGR12_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR12_MEAN_CMAXI_DAYS) ) do;
GRP_AGR12_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MEAN_CMAXI_DUE) ) do;
GRP_AGR12_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR12_MEAN_CMAXI_DUE) ) do;
GRP_AGR12_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR12_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MIN_CMAXA_DAYS) ) do;
GRP_AGR12_MIN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR12_MIN_CMAXA_DAYS) ) do;
GRP_AGR12_MIN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MIN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MIN_CMAXA_DUE) ) do;
GRP_AGR12_MIN_CMAXA_DUE  = 1 ;
end;
when ( missing(AGR12_MIN_CMAXA_DUE) ) do;
GRP_AGR12_MIN_CMAXA_DUE  = 2 ;
end;
otherwise GRP_AGR12_MIN_CMAXA_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MIN_CMAXC_DAYS) ) do;
GRP_AGR12_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR12_MIN_CMAXC_DAYS) ) do;
GRP_AGR12_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MIN_CMAXC_DUE) ) do;
GRP_AGR12_MIN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR12_MIN_CMAXC_DUE) ) do;
GRP_AGR12_MIN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR12_MIN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR12_MIN_CMAXI_DAYS) ) do;
GRP_AGR12_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR12_MIN_CMAXI_DAYS) ) do;
GRP_AGR12_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR12_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR12_MIN_CMAXI_DUE) ) do;
GRP_AGR12_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR12_MIN_CMAXI_DUE) ) do;
GRP_AGR12_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR12_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MAX_CMAXA_DAYS) ) do;
GRP_AGR3_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR3_MAX_CMAXA_DAYS) ) do;
GRP_AGR3_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MAX_CMAXA_DUE) and AGR3_MAX_CMAXA_DUE <= 3 ) do;
GRP_AGR3_MAX_CMAXA_DUE  = 1 ;
end;
when ( 3 < AGR3_MAX_CMAXA_DUE ) do;
GRP_AGR3_MAX_CMAXA_DUE  = 2 ;
end;
when ( missing(AGR3_MAX_CMAXA_DUE) ) do;
GRP_AGR3_MAX_CMAXA_DUE  = 3 ;
end;
otherwise GRP_AGR3_MAX_CMAXA_DUE  = 4 ; end;
select;
when ( not missing(AGR3_MAX_CMAXC_DAYS) ) do;
GRP_AGR3_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR3_MAX_CMAXC_DAYS) ) do;
GRP_AGR3_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MAX_CMAXC_DUE) ) do;
GRP_AGR3_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR3_MAX_CMAXC_DUE) ) do;
GRP_AGR3_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR3_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MAX_CMAXI_DAYS) ) do;
GRP_AGR3_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR3_MAX_CMAXI_DAYS) ) do;
GRP_AGR3_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MAX_CMAXI_DUE) ) do;
GRP_AGR3_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR3_MAX_CMAXI_DUE) ) do;
GRP_AGR3_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR3_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXA_DAYS) ) do;
GRP_AGR3_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR3_MEAN_CMAXA_DAYS) ) do;
GRP_AGR3_MEAN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MEAN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXA_DUE) and AGR3_MEAN_CMAXA_DUE <= 1 ) do;
GRP_AGR3_MEAN_CMAXA_DUE  = 1 ;
end;
when ( 1 < AGR3_MEAN_CMAXA_DUE ) do;
GRP_AGR3_MEAN_CMAXA_DUE  = 2 ;
end;
when ( missing(AGR3_MEAN_CMAXA_DUE) ) do;
GRP_AGR3_MEAN_CMAXA_DUE  = 3 ;
end;
otherwise GRP_AGR3_MEAN_CMAXA_DUE  = 4 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXC_DAYS) ) do;
GRP_AGR3_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR3_MEAN_CMAXC_DAYS) ) do;
GRP_AGR3_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXC_DUE) ) do;
GRP_AGR3_MEAN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR3_MEAN_CMAXC_DUE) ) do;
GRP_AGR3_MEAN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR3_MEAN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXI_DAYS) ) do;
GRP_AGR3_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR3_MEAN_CMAXI_DAYS) ) do;
GRP_AGR3_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MEAN_CMAXI_DUE) ) do;
GRP_AGR3_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR3_MEAN_CMAXI_DUE) ) do;
GRP_AGR3_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR3_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MIN_CMAXA_DAYS) ) do;
GRP_AGR3_MIN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR3_MIN_CMAXA_DAYS) ) do;
GRP_AGR3_MIN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MIN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MIN_CMAXA_DUE) and AGR3_MIN_CMAXA_DUE <= 0 ) do;
GRP_AGR3_MIN_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGR3_MIN_CMAXA_DUE ) do;
GRP_AGR3_MIN_CMAXA_DUE  = 2 ;
end;
when ( missing(AGR3_MIN_CMAXA_DUE) ) do;
GRP_AGR3_MIN_CMAXA_DUE  = 3 ;
end;
otherwise GRP_AGR3_MIN_CMAXA_DUE  = 4 ; end;
select;
when ( not missing(AGR3_MIN_CMAXC_DAYS) ) do;
GRP_AGR3_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR3_MIN_CMAXC_DAYS) ) do;
GRP_AGR3_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MIN_CMAXC_DUE) ) do;
GRP_AGR3_MIN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR3_MIN_CMAXC_DUE) ) do;
GRP_AGR3_MIN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR3_MIN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR3_MIN_CMAXI_DAYS) ) do;
GRP_AGR3_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR3_MIN_CMAXI_DAYS) ) do;
GRP_AGR3_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR3_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR3_MIN_CMAXI_DUE) ) do;
GRP_AGR3_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR3_MIN_CMAXI_DUE) ) do;
GRP_AGR3_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR3_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MAX_CMAXA_DAYS) ) do;
GRP_AGR6_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR6_MAX_CMAXA_DAYS) ) do;
GRP_AGR6_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MAX_CMAXA_DUE) and AGR6_MAX_CMAXA_DUE <= 4 ) do;
GRP_AGR6_MAX_CMAXA_DUE  = 1 ;
end;
when ( 4 < AGR6_MAX_CMAXA_DUE ) do;
GRP_AGR6_MAX_CMAXA_DUE  = 2 ;
end;
when ( missing(AGR6_MAX_CMAXA_DUE) ) do;
GRP_AGR6_MAX_CMAXA_DUE  = 3 ;
end;
otherwise GRP_AGR6_MAX_CMAXA_DUE  = 4 ; end;
select;
when ( not missing(AGR6_MAX_CMAXC_DAYS) ) do;
GRP_AGR6_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR6_MAX_CMAXC_DAYS) ) do;
GRP_AGR6_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MAX_CMAXC_DUE) ) do;
GRP_AGR6_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR6_MAX_CMAXC_DUE) ) do;
GRP_AGR6_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR6_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MAX_CMAXI_DAYS) ) do;
GRP_AGR6_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR6_MAX_CMAXI_DAYS) ) do;
GRP_AGR6_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MAX_CMAXI_DUE) ) do;
GRP_AGR6_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR6_MAX_CMAXI_DUE) ) do;
GRP_AGR6_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR6_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXA_DAYS) ) do;
GRP_AGR6_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR6_MEAN_CMAXA_DAYS) ) do;
GRP_AGR6_MEAN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MEAN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXA_DUE) and AGR6_MEAN_CMAXA_DUE <= 2 ) do;
GRP_AGR6_MEAN_CMAXA_DUE  = 1 ;
end;
when ( 2 < AGR6_MEAN_CMAXA_DUE ) do;
GRP_AGR6_MEAN_CMAXA_DUE  = 2 ;
end;
when ( missing(AGR6_MEAN_CMAXA_DUE) ) do;
GRP_AGR6_MEAN_CMAXA_DUE  = 3 ;
end;
otherwise GRP_AGR6_MEAN_CMAXA_DUE  = 4 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXC_DAYS) ) do;
GRP_AGR6_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR6_MEAN_CMAXC_DAYS) ) do;
GRP_AGR6_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXC_DUE) ) do;
GRP_AGR6_MEAN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR6_MEAN_CMAXC_DUE) ) do;
GRP_AGR6_MEAN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR6_MEAN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXI_DAYS) ) do;
GRP_AGR6_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR6_MEAN_CMAXI_DAYS) ) do;
GRP_AGR6_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MEAN_CMAXI_DUE) ) do;
GRP_AGR6_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR6_MEAN_CMAXI_DUE) ) do;
GRP_AGR6_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR6_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MIN_CMAXA_DAYS) ) do;
GRP_AGR6_MIN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR6_MIN_CMAXA_DAYS) ) do;
GRP_AGR6_MIN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MIN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MIN_CMAXA_DUE) and AGR6_MIN_CMAXA_DUE <= 0 ) do;
GRP_AGR6_MIN_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGR6_MIN_CMAXA_DUE ) do;
GRP_AGR6_MIN_CMAXA_DUE  = 2 ;
end;
when ( missing(AGR6_MIN_CMAXA_DUE) ) do;
GRP_AGR6_MIN_CMAXA_DUE  = 3 ;
end;
otherwise GRP_AGR6_MIN_CMAXA_DUE  = 4 ; end;
select;
when ( not missing(AGR6_MIN_CMAXC_DAYS) ) do;
GRP_AGR6_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR6_MIN_CMAXC_DAYS) ) do;
GRP_AGR6_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MIN_CMAXC_DUE) ) do;
GRP_AGR6_MIN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR6_MIN_CMAXC_DUE) ) do;
GRP_AGR6_MIN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR6_MIN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR6_MIN_CMAXI_DAYS) ) do;
GRP_AGR6_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR6_MIN_CMAXI_DAYS) ) do;
GRP_AGR6_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR6_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR6_MIN_CMAXI_DUE) ) do;
GRP_AGR6_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR6_MIN_CMAXI_DUE) ) do;
GRP_AGR6_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR6_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MAX_CMAXA_DAYS) ) do;
GRP_AGR9_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR9_MAX_CMAXA_DAYS) ) do;
GRP_AGR9_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MAX_CMAXA_DUE) and AGR9_MAX_CMAXA_DUE <= 6 ) do;
GRP_AGR9_MAX_CMAXA_DUE  = 1 ;
end;
when ( 6 < AGR9_MAX_CMAXA_DUE ) do;
GRP_AGR9_MAX_CMAXA_DUE  = 2 ;
end;
when ( missing(AGR9_MAX_CMAXA_DUE) ) do;
GRP_AGR9_MAX_CMAXA_DUE  = 3 ;
end;
otherwise GRP_AGR9_MAX_CMAXA_DUE  = 4 ; end;
select;
when ( not missing(AGR9_MAX_CMAXC_DAYS) ) do;
GRP_AGR9_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR9_MAX_CMAXC_DAYS) ) do;
GRP_AGR9_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MAX_CMAXC_DUE) ) do;
GRP_AGR9_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR9_MAX_CMAXC_DUE) ) do;
GRP_AGR9_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR9_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MAX_CMAXI_DAYS) ) do;
GRP_AGR9_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR9_MAX_CMAXI_DAYS) ) do;
GRP_AGR9_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MAX_CMAXI_DUE) ) do;
GRP_AGR9_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR9_MAX_CMAXI_DUE) ) do;
GRP_AGR9_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR9_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXA_DAYS) ) do;
GRP_AGR9_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR9_MEAN_CMAXA_DAYS) ) do;
GRP_AGR9_MEAN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MEAN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXA_DUE) and AGR9_MEAN_CMAXA_DUE <= 2.5555555556 ) do;
GRP_AGR9_MEAN_CMAXA_DUE  = 1 ;
end;
when ( 2.5555555556 < AGR9_MEAN_CMAXA_DUE ) do;
GRP_AGR9_MEAN_CMAXA_DUE  = 2 ;
end;
when ( missing(AGR9_MEAN_CMAXA_DUE) ) do;
GRP_AGR9_MEAN_CMAXA_DUE  = 3 ;
end;
otherwise GRP_AGR9_MEAN_CMAXA_DUE  = 4 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXC_DAYS) ) do;
GRP_AGR9_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR9_MEAN_CMAXC_DAYS) ) do;
GRP_AGR9_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXC_DUE) ) do;
GRP_AGR9_MEAN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR9_MEAN_CMAXC_DUE) ) do;
GRP_AGR9_MEAN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR9_MEAN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXI_DAYS) ) do;
GRP_AGR9_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR9_MEAN_CMAXI_DAYS) ) do;
GRP_AGR9_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MEAN_CMAXI_DUE) ) do;
GRP_AGR9_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR9_MEAN_CMAXI_DUE) ) do;
GRP_AGR9_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR9_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MIN_CMAXA_DAYS) ) do;
GRP_AGR9_MIN_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGR9_MIN_CMAXA_DAYS) ) do;
GRP_AGR9_MIN_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MIN_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MIN_CMAXA_DUE) and AGR9_MIN_CMAXA_DUE <= 0 ) do;
GRP_AGR9_MIN_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGR9_MIN_CMAXA_DUE ) do;
GRP_AGR9_MIN_CMAXA_DUE  = 2 ;
end;
when ( missing(AGR9_MIN_CMAXA_DUE) ) do;
GRP_AGR9_MIN_CMAXA_DUE  = 3 ;
end;
otherwise GRP_AGR9_MIN_CMAXA_DUE  = 4 ; end;
select;
when ( not missing(AGR9_MIN_CMAXC_DAYS) ) do;
GRP_AGR9_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGR9_MIN_CMAXC_DAYS) ) do;
GRP_AGR9_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MIN_CMAXC_DUE) ) do;
GRP_AGR9_MIN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGR9_MIN_CMAXC_DUE) ) do;
GRP_AGR9_MIN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGR9_MIN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGR9_MIN_CMAXI_DAYS) ) do;
GRP_AGR9_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGR9_MIN_CMAXI_DAYS) ) do;
GRP_AGR9_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGR9_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGR9_MIN_CMAXI_DUE) ) do;
GRP_AGR9_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGR9_MIN_CMAXI_DUE) ) do;
GRP_AGR9_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGR9_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS12_MAX_CMAXA_DAYS) ) do;
GRP_AGS12_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS12_MAX_CMAXA_DAYS) ) do;
GRP_AGS12_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MAX_CMAXA_DUE) and AGS12_MAX_CMAXA_DUE <= 6 ) do;
GRP_AGS12_MAX_CMAXA_DUE  = 1 ;
end;
when ( 6 < AGS12_MAX_CMAXA_DUE ) do;
GRP_AGS12_MAX_CMAXA_DUE  = 2 ;
end;
when ( missing(AGS12_MAX_CMAXA_DUE) ) do;
GRP_AGS12_MAX_CMAXA_DUE  = 3 ;
end;
otherwise GRP_AGS12_MAX_CMAXA_DUE  = 4 ; end;
select;
when ( not missing(AGS12_MAX_CMAXC_DAYS) ) do;
GRP_AGS12_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS12_MAX_CMAXC_DAYS) ) do;
GRP_AGS12_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MAX_CMAXC_DUE) ) do;
GRP_AGS12_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS12_MAX_CMAXC_DUE) ) do;
GRP_AGS12_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS12_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS12_MAX_CMAXI_DAYS) ) do;
GRP_AGS12_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS12_MAX_CMAXI_DAYS) ) do;
GRP_AGS12_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MAX_CMAXI_DUE) ) do;
GRP_AGS12_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS12_MAX_CMAXI_DUE) ) do;
GRP_AGS12_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS12_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXA_DAYS) and AGS12_MEAN_CMAXA_DAYS <= 14.25 ) do;
GRP_AGS12_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( 14.25 < AGS12_MEAN_CMAXA_DAYS ) do;
GRP_AGS12_MEAN_CMAXA_DAYS  = 2 ;
end;
when ( missing(AGS12_MEAN_CMAXA_DAYS) ) do;
GRP_AGS12_MEAN_CMAXA_DAYS  = 3 ;
end;
otherwise GRP_AGS12_MEAN_CMAXA_DAYS  = 4 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXA_DUE) and AGS12_MEAN_CMAXA_DUE <= 0.2727272727 ) do;
GRP_AGS12_MEAN_CMAXA_DUE  = 1 ;
end;
when ( 0.2727272727 < AGS12_MEAN_CMAXA_DUE <= 3.8888888889 ) do;
GRP_AGS12_MEAN_CMAXA_DUE  = 2 ;
end;
when ( 3.8888888889 < AGS12_MEAN_CMAXA_DUE ) do;
GRP_AGS12_MEAN_CMAXA_DUE  = 3 ;
end;
when ( missing(AGS12_MEAN_CMAXA_DUE) ) do;
GRP_AGS12_MEAN_CMAXA_DUE  = 4 ;
end;
otherwise GRP_AGS12_MEAN_CMAXA_DUE  = 5 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXC_DAYS) ) do;
GRP_AGS12_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS12_MEAN_CMAXC_DAYS) ) do;
GRP_AGS12_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXC_DUE) and AGS12_MEAN_CMAXC_DUE <= 4 ) do;
GRP_AGS12_MEAN_CMAXC_DUE  = 1 ;
end;
when ( 4 < AGS12_MEAN_CMAXC_DUE ) do;
GRP_AGS12_MEAN_CMAXC_DUE  = 2 ;
end;
when ( missing(AGS12_MEAN_CMAXC_DUE) ) do;
GRP_AGS12_MEAN_CMAXC_DUE  = 3 ;
end;
otherwise GRP_AGS12_MEAN_CMAXC_DUE  = 4 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXI_DAYS) ) do;
GRP_AGS12_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS12_MEAN_CMAXI_DAYS) ) do;
GRP_AGS12_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MEAN_CMAXI_DUE) ) do;
GRP_AGS12_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS12_MEAN_CMAXI_DUE) ) do;
GRP_AGS12_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS12_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS12_MIN_CMAXA_DAYS) and AGS12_MIN_CMAXA_DAYS <= 11 ) do;
GRP_AGS12_MIN_CMAXA_DAYS  = 1 ;
end;
when ( 11 < AGS12_MIN_CMAXA_DAYS ) do;
GRP_AGS12_MIN_CMAXA_DAYS  = 2 ;
end;
when ( missing(AGS12_MIN_CMAXA_DAYS) ) do;
GRP_AGS12_MIN_CMAXA_DAYS  = 3 ;
end;
otherwise GRP_AGS12_MIN_CMAXA_DAYS  = 4 ; end;
select;
when ( not missing(AGS12_MIN_CMAXA_DUE) and AGS12_MIN_CMAXA_DUE <= 0 ) do;
GRP_AGS12_MIN_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGS12_MIN_CMAXA_DUE ) do;
GRP_AGS12_MIN_CMAXA_DUE  = 2 ;
end;
when ( missing(AGS12_MIN_CMAXA_DUE) ) do;
GRP_AGS12_MIN_CMAXA_DUE  = 3 ;
end;
otherwise GRP_AGS12_MIN_CMAXA_DUE  = 4 ; end;
select;
when ( not missing(AGS12_MIN_CMAXC_DAYS) ) do;
GRP_AGS12_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS12_MIN_CMAXC_DAYS) ) do;
GRP_AGS12_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MIN_CMAXC_DUE) and AGS12_MIN_CMAXC_DUE <= 0 ) do;
GRP_AGS12_MIN_CMAXC_DUE  = 1 ;
end;
when ( 0 < AGS12_MIN_CMAXC_DUE ) do;
GRP_AGS12_MIN_CMAXC_DUE  = 2 ;
end;
when ( missing(AGS12_MIN_CMAXC_DUE) ) do;
GRP_AGS12_MIN_CMAXC_DUE  = 3 ;
end;
otherwise GRP_AGS12_MIN_CMAXC_DUE  = 4 ; end;
select;
when ( not missing(AGS12_MIN_CMAXI_DAYS) ) do;
GRP_AGS12_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS12_MIN_CMAXI_DAYS) ) do;
GRP_AGS12_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS12_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS12_MIN_CMAXI_DUE) ) do;
GRP_AGS12_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS12_MIN_CMAXI_DUE) ) do;
GRP_AGS12_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS12_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MAX_CMAXA_DAYS) ) do;
GRP_AGS3_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS3_MAX_CMAXA_DAYS) ) do;
GRP_AGS3_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MAX_CMAXA_DUE) and AGS3_MAX_CMAXA_DUE <= 3 ) do;
GRP_AGS3_MAX_CMAXA_DUE  = 1 ;
end;
when ( 3 < AGS3_MAX_CMAXA_DUE ) do;
GRP_AGS3_MAX_CMAXA_DUE  = 2 ;
end;
when ( missing(AGS3_MAX_CMAXA_DUE) ) do;
GRP_AGS3_MAX_CMAXA_DUE  = 3 ;
end;
otherwise GRP_AGS3_MAX_CMAXA_DUE  = 4 ; end;
select;
when ( not missing(AGS3_MAX_CMAXC_DAYS) ) do;
GRP_AGS3_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS3_MAX_CMAXC_DAYS) ) do;
GRP_AGS3_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MAX_CMAXC_DUE) ) do;
GRP_AGS3_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS3_MAX_CMAXC_DUE) ) do;
GRP_AGS3_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS3_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MAX_CMAXI_DAYS) ) do;
GRP_AGS3_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS3_MAX_CMAXI_DAYS) ) do;
GRP_AGS3_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MAX_CMAXI_DUE) ) do;
GRP_AGS3_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS3_MAX_CMAXI_DUE) ) do;
GRP_AGS3_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS3_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXA_DAYS) and AGS3_MEAN_CMAXA_DAYS <= 14 ) do;
GRP_AGS3_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( 14 < AGS3_MEAN_CMAXA_DAYS ) do;
GRP_AGS3_MEAN_CMAXA_DAYS  = 2 ;
end;
when ( missing(AGS3_MEAN_CMAXA_DAYS) ) do;
GRP_AGS3_MEAN_CMAXA_DAYS  = 3 ;
end;
otherwise GRP_AGS3_MEAN_CMAXA_DAYS  = 4 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXA_DUE) and AGS3_MEAN_CMAXA_DUE <= 0.6666666667 ) do;
GRP_AGS3_MEAN_CMAXA_DUE  = 1 ;
end;
when ( 0.6666666667 < AGS3_MEAN_CMAXA_DUE ) do;
GRP_AGS3_MEAN_CMAXA_DUE  = 2 ;
end;
when ( missing(AGS3_MEAN_CMAXA_DUE) ) do;
GRP_AGS3_MEAN_CMAXA_DUE  = 3 ;
end;
otherwise GRP_AGS3_MEAN_CMAXA_DUE  = 4 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXC_DAYS) ) do;
GRP_AGS3_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS3_MEAN_CMAXC_DAYS) ) do;
GRP_AGS3_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXC_DUE) ) do;
GRP_AGS3_MEAN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS3_MEAN_CMAXC_DUE) ) do;
GRP_AGS3_MEAN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS3_MEAN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXI_DAYS) ) do;
GRP_AGS3_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS3_MEAN_CMAXI_DAYS) ) do;
GRP_AGS3_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MEAN_CMAXI_DUE) ) do;
GRP_AGS3_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS3_MEAN_CMAXI_DUE) ) do;
GRP_AGS3_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS3_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MIN_CMAXA_DAYS) and AGS3_MIN_CMAXA_DAYS <= 12 ) do;
GRP_AGS3_MIN_CMAXA_DAYS  = 1 ;
end;
when ( 12 < AGS3_MIN_CMAXA_DAYS ) do;
GRP_AGS3_MIN_CMAXA_DAYS  = 2 ;
end;
when ( missing(AGS3_MIN_CMAXA_DAYS) ) do;
GRP_AGS3_MIN_CMAXA_DAYS  = 3 ;
end;
otherwise GRP_AGS3_MIN_CMAXA_DAYS  = 4 ; end;
select;
when ( not missing(AGS3_MIN_CMAXA_DUE) and AGS3_MIN_CMAXA_DUE <= 0 ) do;
GRP_AGS3_MIN_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGS3_MIN_CMAXA_DUE ) do;
GRP_AGS3_MIN_CMAXA_DUE  = 2 ;
end;
when ( missing(AGS3_MIN_CMAXA_DUE) ) do;
GRP_AGS3_MIN_CMAXA_DUE  = 3 ;
end;
otherwise GRP_AGS3_MIN_CMAXA_DUE  = 4 ; end;
select;
when ( not missing(AGS3_MIN_CMAXC_DAYS) ) do;
GRP_AGS3_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS3_MIN_CMAXC_DAYS) ) do;
GRP_AGS3_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MIN_CMAXC_DUE) ) do;
GRP_AGS3_MIN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS3_MIN_CMAXC_DUE) ) do;
GRP_AGS3_MIN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS3_MIN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS3_MIN_CMAXI_DAYS) ) do;
GRP_AGS3_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS3_MIN_CMAXI_DAYS) ) do;
GRP_AGS3_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS3_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS3_MIN_CMAXI_DUE) ) do;
GRP_AGS3_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS3_MIN_CMAXI_DUE) ) do;
GRP_AGS3_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS3_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MAX_CMAXA_DAYS) ) do;
GRP_AGS6_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS6_MAX_CMAXA_DAYS) ) do;
GRP_AGS6_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MAX_CMAXA_DUE) and AGS6_MAX_CMAXA_DUE <= 5 ) do;
GRP_AGS6_MAX_CMAXA_DUE  = 1 ;
end;
when ( 5 < AGS6_MAX_CMAXA_DUE ) do;
GRP_AGS6_MAX_CMAXA_DUE  = 2 ;
end;
when ( missing(AGS6_MAX_CMAXA_DUE) ) do;
GRP_AGS6_MAX_CMAXA_DUE  = 3 ;
end;
otherwise GRP_AGS6_MAX_CMAXA_DUE  = 4 ; end;
select;
when ( not missing(AGS6_MAX_CMAXC_DAYS) ) do;
GRP_AGS6_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS6_MAX_CMAXC_DAYS) ) do;
GRP_AGS6_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MAX_CMAXC_DUE) ) do;
GRP_AGS6_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS6_MAX_CMAXC_DUE) ) do;
GRP_AGS6_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS6_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MAX_CMAXI_DAYS) ) do;
GRP_AGS6_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS6_MAX_CMAXI_DAYS) ) do;
GRP_AGS6_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MAX_CMAXI_DUE) ) do;
GRP_AGS6_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS6_MAX_CMAXI_DUE) ) do;
GRP_AGS6_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS6_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXA_DAYS) and AGS6_MEAN_CMAXA_DAYS <= 14.25 ) do;
GRP_AGS6_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( 14.25 < AGS6_MEAN_CMAXA_DAYS ) do;
GRP_AGS6_MEAN_CMAXA_DAYS  = 2 ;
end;
when ( missing(AGS6_MEAN_CMAXA_DAYS) ) do;
GRP_AGS6_MEAN_CMAXA_DAYS  = 3 ;
end;
otherwise GRP_AGS6_MEAN_CMAXA_DAYS  = 4 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXA_DUE) and AGS6_MEAN_CMAXA_DUE <= 3.6666666667 ) do;
GRP_AGS6_MEAN_CMAXA_DUE  = 1 ;
end;
when ( 3.6666666667 < AGS6_MEAN_CMAXA_DUE ) do;
GRP_AGS6_MEAN_CMAXA_DUE  = 2 ;
end;
when ( missing(AGS6_MEAN_CMAXA_DUE) ) do;
GRP_AGS6_MEAN_CMAXA_DUE  = 3 ;
end;
otherwise GRP_AGS6_MEAN_CMAXA_DUE  = 4 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXC_DAYS) ) do;
GRP_AGS6_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS6_MEAN_CMAXC_DAYS) ) do;
GRP_AGS6_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXC_DUE) ) do;
GRP_AGS6_MEAN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS6_MEAN_CMAXC_DUE) ) do;
GRP_AGS6_MEAN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS6_MEAN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXI_DAYS) ) do;
GRP_AGS6_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS6_MEAN_CMAXI_DAYS) ) do;
GRP_AGS6_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MEAN_CMAXI_DUE) ) do;
GRP_AGS6_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS6_MEAN_CMAXI_DUE) ) do;
GRP_AGS6_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS6_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MIN_CMAXA_DAYS) and AGS6_MIN_CMAXA_DAYS <= 11 ) do;
GRP_AGS6_MIN_CMAXA_DAYS  = 1 ;
end;
when ( 11 < AGS6_MIN_CMAXA_DAYS ) do;
GRP_AGS6_MIN_CMAXA_DAYS  = 2 ;
end;
when ( missing(AGS6_MIN_CMAXA_DAYS) ) do;
GRP_AGS6_MIN_CMAXA_DAYS  = 3 ;
end;
otherwise GRP_AGS6_MIN_CMAXA_DAYS  = 4 ; end;
select;
when ( not missing(AGS6_MIN_CMAXA_DUE) and AGS6_MIN_CMAXA_DUE <= 0 ) do;
GRP_AGS6_MIN_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGS6_MIN_CMAXA_DUE ) do;
GRP_AGS6_MIN_CMAXA_DUE  = 2 ;
end;
when ( missing(AGS6_MIN_CMAXA_DUE) ) do;
GRP_AGS6_MIN_CMAXA_DUE  = 3 ;
end;
otherwise GRP_AGS6_MIN_CMAXA_DUE  = 4 ; end;
select;
when ( not missing(AGS6_MIN_CMAXC_DAYS) ) do;
GRP_AGS6_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS6_MIN_CMAXC_DAYS) ) do;
GRP_AGS6_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MIN_CMAXC_DUE) ) do;
GRP_AGS6_MIN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS6_MIN_CMAXC_DUE) ) do;
GRP_AGS6_MIN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS6_MIN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS6_MIN_CMAXI_DAYS) ) do;
GRP_AGS6_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS6_MIN_CMAXI_DAYS) ) do;
GRP_AGS6_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS6_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS6_MIN_CMAXI_DUE) ) do;
GRP_AGS6_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS6_MIN_CMAXI_DUE) ) do;
GRP_AGS6_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS6_MIN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MAX_CMAXA_DAYS) ) do;
GRP_AGS9_MAX_CMAXA_DAYS  = 1 ;
end;
when ( missing(AGS9_MAX_CMAXA_DAYS) ) do;
GRP_AGS9_MAX_CMAXA_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MAX_CMAXA_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MAX_CMAXA_DUE) and AGS9_MAX_CMAXA_DUE <= 6 ) do;
GRP_AGS9_MAX_CMAXA_DUE  = 1 ;
end;
when ( 6 < AGS9_MAX_CMAXA_DUE ) do;
GRP_AGS9_MAX_CMAXA_DUE  = 2 ;
end;
when ( missing(AGS9_MAX_CMAXA_DUE) ) do;
GRP_AGS9_MAX_CMAXA_DUE  = 3 ;
end;
otherwise GRP_AGS9_MAX_CMAXA_DUE  = 4 ; end;
select;
when ( not missing(AGS9_MAX_CMAXC_DAYS) ) do;
GRP_AGS9_MAX_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS9_MAX_CMAXC_DAYS) ) do;
GRP_AGS9_MAX_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MAX_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MAX_CMAXC_DUE) ) do;
GRP_AGS9_MAX_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS9_MAX_CMAXC_DUE) ) do;
GRP_AGS9_MAX_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS9_MAX_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MAX_CMAXI_DAYS) ) do;
GRP_AGS9_MAX_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS9_MAX_CMAXI_DAYS) ) do;
GRP_AGS9_MAX_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MAX_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MAX_CMAXI_DUE) ) do;
GRP_AGS9_MAX_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS9_MAX_CMAXI_DUE) ) do;
GRP_AGS9_MAX_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS9_MAX_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXA_DAYS) and AGS9_MEAN_CMAXA_DAYS <= 14.2 ) do;
GRP_AGS9_MEAN_CMAXA_DAYS  = 1 ;
end;
when ( 14.2 < AGS9_MEAN_CMAXA_DAYS ) do;
GRP_AGS9_MEAN_CMAXA_DAYS  = 2 ;
end;
when ( missing(AGS9_MEAN_CMAXA_DAYS) ) do;
GRP_AGS9_MEAN_CMAXA_DAYS  = 3 ;
end;
otherwise GRP_AGS9_MEAN_CMAXA_DAYS  = 4 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXA_DUE) and AGS9_MEAN_CMAXA_DUE <= 3.5 ) do;
GRP_AGS9_MEAN_CMAXA_DUE  = 1 ;
end;
when ( 3.5 < AGS9_MEAN_CMAXA_DUE ) do;
GRP_AGS9_MEAN_CMAXA_DUE  = 2 ;
end;
when ( missing(AGS9_MEAN_CMAXA_DUE) ) do;
GRP_AGS9_MEAN_CMAXA_DUE  = 3 ;
end;
otherwise GRP_AGS9_MEAN_CMAXA_DUE  = 4 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXC_DAYS) ) do;
GRP_AGS9_MEAN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS9_MEAN_CMAXC_DAYS) ) do;
GRP_AGS9_MEAN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MEAN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXC_DUE) and AGS9_MEAN_CMAXC_DUE <= 3.6666666667 ) do;
GRP_AGS9_MEAN_CMAXC_DUE  = 1 ;
end;
when ( 3.6666666667 < AGS9_MEAN_CMAXC_DUE ) do;
GRP_AGS9_MEAN_CMAXC_DUE  = 2 ;
end;
when ( missing(AGS9_MEAN_CMAXC_DUE) ) do;
GRP_AGS9_MEAN_CMAXC_DUE  = 3 ;
end;
otherwise GRP_AGS9_MEAN_CMAXC_DUE  = 4 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXI_DAYS) ) do;
GRP_AGS9_MEAN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS9_MEAN_CMAXI_DAYS) ) do;
GRP_AGS9_MEAN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MEAN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MEAN_CMAXI_DUE) ) do;
GRP_AGS9_MEAN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS9_MEAN_CMAXI_DUE) ) do;
GRP_AGS9_MEAN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS9_MEAN_CMAXI_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MIN_CMAXA_DAYS) and AGS9_MIN_CMAXA_DAYS <= 11 ) do;
GRP_AGS9_MIN_CMAXA_DAYS  = 1 ;
end;
when ( 11 < AGS9_MIN_CMAXA_DAYS ) do;
GRP_AGS9_MIN_CMAXA_DAYS  = 2 ;
end;
when ( missing(AGS9_MIN_CMAXA_DAYS) ) do;
GRP_AGS9_MIN_CMAXA_DAYS  = 3 ;
end;
otherwise GRP_AGS9_MIN_CMAXA_DAYS  = 4 ; end;
select;
when ( not missing(AGS9_MIN_CMAXA_DUE) and AGS9_MIN_CMAXA_DUE <= 0 ) do;
GRP_AGS9_MIN_CMAXA_DUE  = 1 ;
end;
when ( 0 < AGS9_MIN_CMAXA_DUE ) do;
GRP_AGS9_MIN_CMAXA_DUE  = 2 ;
end;
when ( missing(AGS9_MIN_CMAXA_DUE) ) do;
GRP_AGS9_MIN_CMAXA_DUE  = 3 ;
end;
otherwise GRP_AGS9_MIN_CMAXA_DUE  = 4 ; end;
select;
when ( not missing(AGS9_MIN_CMAXC_DAYS) ) do;
GRP_AGS9_MIN_CMAXC_DAYS  = 1 ;
end;
when ( missing(AGS9_MIN_CMAXC_DAYS) ) do;
GRP_AGS9_MIN_CMAXC_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MIN_CMAXC_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MIN_CMAXC_DUE) ) do;
GRP_AGS9_MIN_CMAXC_DUE  = 1 ;
end;
when ( missing(AGS9_MIN_CMAXC_DUE) ) do;
GRP_AGS9_MIN_CMAXC_DUE  = 2 ;
end;
otherwise GRP_AGS9_MIN_CMAXC_DUE  = 3 ; end;
select;
when ( not missing(AGS9_MIN_CMAXI_DAYS) ) do;
GRP_AGS9_MIN_CMAXI_DAYS  = 1 ;
end;
when ( missing(AGS9_MIN_CMAXI_DAYS) ) do;
GRP_AGS9_MIN_CMAXI_DAYS  = 2 ;
end;
otherwise GRP_AGS9_MIN_CMAXI_DAYS  = 3 ; end;
select;
when ( not missing(AGS9_MIN_CMAXI_DUE) ) do;
GRP_AGS9_MIN_CMAXI_DUE  = 1 ;
end;
when ( missing(AGS9_MIN_CMAXI_DUE) ) do;
GRP_AGS9_MIN_CMAXI_DUE  = 2 ;
end;
otherwise GRP_AGS9_MIN_CMAXI_DUE  = 3 ; end;
select (APP_CHAR_BRANCH );
  when ('Computers')   do;
GRP_APP_CHAR_BRANCH  = 1 ;
end;
  when ('DiY')   do;
GRP_APP_CHAR_BRANCH  = 2 ;
end;
  when ('Fenitures')   do;
GRP_APP_CHAR_BRANCH  = 3 ;
end;
  when ('Radio-TV')   do;
GRP_APP_CHAR_BRANCH  = 4 ;
end;
otherwise GRP_APP_CHAR_BRANCH  = 5 ; end;
select (APP_CHAR_CARS );
  when ('No')   do;
GRP_APP_CHAR_CARS  = 1 ;
end;
  when ('Owner')   do;
GRP_APP_CHAR_CARS  = 2 ;
end;
otherwise GRP_APP_CHAR_CARS  = 3 ; end;
select (APP_CHAR_CITY );
  when ('Big')   do;
GRP_APP_CHAR_CITY  = 1 ;
end;
  when ('Medium')   do;
GRP_APP_CHAR_CITY  = 2 ;
end;
  when ('Large')   do;
GRP_APP_CHAR_CITY  = 3 ;
end;
  when ('Small')   do;
GRP_APP_CHAR_CITY  = 4 ;
end;
otherwise GRP_APP_CHAR_CITY  = 5 ; end;
select (APP_CHAR_GENDER );
  when ('Female')   do;
GRP_APP_CHAR_GENDER  = 1 ;
end;
  when ('Male')   do;
GRP_APP_CHAR_GENDER  = 2 ;
end;
otherwise GRP_APP_CHAR_GENDER  = 3 ; end;
select (APP_CHAR_HOME_STATUS );
  when ('Owner')   do;
GRP_APP_CHAR_HOME_STATUS  = 1 ;
end;
  when ('Rental')   do;
GRP_APP_CHAR_HOME_STATUS  = 2 ;
end;
otherwise GRP_APP_CHAR_HOME_STATUS  = 3 ; end;
select (APP_CHAR_JOB_CODE );
  when ('Permanent')   do;
GRP_APP_CHAR_JOB_CODE  = 1 ;
end;
  when ('Retired')   do;
GRP_APP_CHAR_JOB_CODE  = 2 ;
end;
  when ('Owner company')   do;
GRP_APP_CHAR_JOB_CODE  = 3 ;
end;
  when ('Contract')   do;
GRP_APP_CHAR_JOB_CODE  = 4 ;
end;
otherwise GRP_APP_CHAR_JOB_CODE  = 5 ; end;
select (APP_CHAR_MARITAL_STATUS );
  when ('Maried')   do;
GRP_APP_CHAR_MARITAL_STATUS  = 1 ;
end;
  when ('Widowed')   do;
GRP_APP_CHAR_MARITAL_STATUS  = 2 ;
end;
  when ('Divorced')   do;
GRP_APP_CHAR_MARITAL_STATUS  = 3 ;
end;
  when ('Singiel')   do;
GRP_APP_CHAR_MARITAL_STATUS  = 4 ;
end;
otherwise GRP_APP_CHAR_MARITAL_STATUS  = 5 ; end;
select;
when ( not missing(APP_INCOME) and APP_INCOME <= 379 ) do;
GRP_APP_INCOME  = 1 ;
end;
when ( 379 < APP_INCOME <= 663 ) do;
GRP_APP_INCOME  = 2 ;
end;
when ( 663 < APP_INCOME <= 906 ) do;
GRP_APP_INCOME  = 3 ;
end;
when ( 906 < APP_INCOME <= 1236 ) do;
GRP_APP_INCOME  = 4 ;
end;
when ( 1236 < APP_INCOME <= 3846 ) do;
GRP_APP_INCOME  = 5 ;
end;
when ( 3846 < APP_INCOME ) do;
GRP_APP_INCOME  = 6 ;
end;
when ( missing(APP_INCOME) ) do;
GRP_APP_INCOME  = 7 ;
end;
otherwise GRP_APP_INCOME  = 8 ; end;
select;
when ( not missing(APP_INSTALLMENT) and APP_INSTALLMENT <= 201 ) do;
GRP_APP_INSTALLMENT  = 1 ;
end;
when ( 201 < APP_INSTALLMENT <= 264 ) do;
GRP_APP_INSTALLMENT  = 2 ;
end;
when ( 264 < APP_INSTALLMENT <= 324 ) do;
GRP_APP_INSTALLMENT  = 3 ;
end;
when ( 324 < APP_INSTALLMENT <= 394 ) do;
GRP_APP_INSTALLMENT  = 4 ;
end;
when ( 394 < APP_INSTALLMENT <= 504 ) do;
GRP_APP_INSTALLMENT  = 5 ;
end;
when ( 504 < APP_INSTALLMENT ) do;
GRP_APP_INSTALLMENT  = 6 ;
end;
when ( missing(APP_INSTALLMENT) ) do;
GRP_APP_INSTALLMENT  = 7 ;
end;
otherwise GRP_APP_INSTALLMENT  = 8 ; end;
select;
when ( not missing(APP_LOAN_AMOUNT) and APP_LOAN_AMOUNT <= 1920 ) do;
GRP_APP_LOAN_AMOUNT  = 1 ;
end;
when ( 1920 < APP_LOAN_AMOUNT <= 4824 ) do;
GRP_APP_LOAN_AMOUNT  = 2 ;
end;
when ( 4824 < APP_LOAN_AMOUNT <= 7656 ) do;
GRP_APP_LOAN_AMOUNT  = 3 ;
end;
when ( 7656 < APP_LOAN_AMOUNT <= 8880 ) do;
GRP_APP_LOAN_AMOUNT  = 4 ;
end;
when ( 8880 < APP_LOAN_AMOUNT <= 11376 ) do;
GRP_APP_LOAN_AMOUNT  = 5 ;
end;
when ( 11376 < APP_LOAN_AMOUNT ) do;
GRP_APP_LOAN_AMOUNT  = 6 ;
end;
when ( missing(APP_LOAN_AMOUNT) ) do;
GRP_APP_LOAN_AMOUNT  = 7 ;
end;
otherwise GRP_APP_LOAN_AMOUNT  = 8 ; end;
select;
when ( not missing(APP_NUMBER_OF_CHILDREN) and APP_NUMBER_OF_CHILDREN <= 0 ) do;
GRP_APP_NUMBER_OF_CHILDREN  = 1 ;
end;
when ( 0 < APP_NUMBER_OF_CHILDREN <= 1 ) do;
GRP_APP_NUMBER_OF_CHILDREN  = 2 ;
end;
when ( 1 < APP_NUMBER_OF_CHILDREN ) do;
GRP_APP_NUMBER_OF_CHILDREN  = 3 ;
end;
when ( missing(APP_NUMBER_OF_CHILDREN) ) do;
GRP_APP_NUMBER_OF_CHILDREN  = 4 ;
end;
otherwise GRP_APP_NUMBER_OF_CHILDREN  = 5 ; end;
select;
when ( not missing(APP_N_INSTALLMENTS) and APP_N_INSTALLMENTS <= 12 ) do;
GRP_APP_N_INSTALLMENTS  = 1 ;
end;
when ( 12 < APP_N_INSTALLMENTS <= 24 ) do;
GRP_APP_N_INSTALLMENTS  = 2 ;
end;
when ( 24 < APP_N_INSTALLMENTS ) do;
GRP_APP_N_INSTALLMENTS  = 3 ;
end;
when ( missing(APP_N_INSTALLMENTS) ) do;
GRP_APP_N_INSTALLMENTS  = 4 ;
end;
otherwise GRP_APP_N_INSTALLMENTS  = 5 ; end;
select;
when ( not missing(APP_SPENDINGS) and APP_SPENDINGS <= 160 ) do;
GRP_APP_SPENDINGS  = 1 ;
end;
when ( 160 < APP_SPENDINGS <= 200 ) do;
GRP_APP_SPENDINGS  = 2 ;
end;
when ( 200 < APP_SPENDINGS <= 240 ) do;
GRP_APP_SPENDINGS  = 3 ;
end;
when ( 240 < APP_SPENDINGS <= 1260 ) do;
GRP_APP_SPENDINGS  = 4 ;
end;
when ( 1260 < APP_SPENDINGS <= 2340 ) do;
GRP_APP_SPENDINGS  = 5 ;
end;
when ( 2340 < APP_SPENDINGS ) do;
GRP_APP_SPENDINGS  = 6 ;
end;
when ( missing(APP_SPENDINGS) ) do;
GRP_APP_SPENDINGS  = 7 ;
end;
otherwise GRP_APP_SPENDINGS  = 8 ; end;
run;
