data grp;
set abt.train;
select;
when ( not missing(ACT_CINS_N_STATB) and ACT_CINS_N_STATB <= 0 ) do;
GRP_ACT_CINS_N_STATB  = 1 ;
end;
when ( 0 < ACT_CINS_N_STATB ) do;
GRP_ACT_CINS_N_STATB  = 2 ;
end;
when ( missing(ACT_CINS_N_STATB) ) do;
GRP_ACT_CINS_N_STATB  = 3 ;
end;
otherwise GRP_ACT_CINS_N_STATB  = 4 ; end;
select;
when ( missing(ACT_CINS_N_STATC) ) do;
GRP_ACT_CINS_N_STATC  = 1 ;
end;
when ( not missing(ACT_CINS_N_STATC) and ACT_CINS_N_STATC <= 1 ) do;
GRP_ACT_CINS_N_STATC  = 2 ;
end;
when ( 1 < ACT_CINS_N_STATC ) do;
GRP_ACT_CINS_N_STATC  = 3 ;
end;
otherwise GRP_ACT_CINS_N_STATC  = 4 ; end;
select;
when ( missing(ACT_CINS_SENIORITY) ) do;
GRP_ACT_CINS_SENIORITY  = 1 ;
end;
when ( not missing(ACT_CINS_SENIORITY) ) do;
GRP_ACT_CINS_SENIORITY  = 2 ;
end;
otherwise GRP_ACT_CINS_SENIORITY  = 3 ; end;
select (APP_CHAR_GENDER );
  when ('Female')   do;
GRP_APP_CHAR_GENDER  = 1 ;
end;
  when ('Male')   do;
GRP_APP_CHAR_GENDER  = 2 ;
end;
otherwise GRP_APP_CHAR_GENDER  = 3 ; end;
select (APP_CHAR_JOB_CODE );
  when ('Owner company')   do;
GRP_APP_CHAR_JOB_CODE  = 1 ;
end;
  when ('Permanent')   do;
GRP_APP_CHAR_JOB_CODE  = 2 ;
end;
  when ('Retired')   do;
GRP_APP_CHAR_JOB_CODE  = 3 ;
end;
otherwise GRP_APP_CHAR_JOB_CODE  = 4 ; end;
select;
when ( 4923 < APP_INCOME ) do;
GRP_APP_INCOME  = 1 ;
end;
when ( not missing(APP_INCOME) and APP_INCOME <= 539 ) do;
GRP_APP_INCOME  = 2 ;
end;
when ( 1500 < APP_INCOME <= 4923 ) do;
GRP_APP_INCOME  = 3 ;
end;
when ( 539 < APP_INCOME <= 1500 ) do;
GRP_APP_INCOME  = 4 ;
end;
otherwise GRP_APP_INCOME  = 5 ; end;
select;
when ( 960 < APP_SPENDINGS ) do;
GRP_APP_SPENDINGS  = 1 ;
end;
when ( not missing(APP_SPENDINGS) and APP_SPENDINGS <= 960 ) do;
GRP_APP_SPENDINGS  = 2 ;
end;
otherwise GRP_APP_SPENDINGS  = 3 ; end;
run;
